### ISSUE TITLE
Error Code 100 on Update

### ISSUE THREAD

**Issue by kmarker** [sans-dfir/sift#100]
I'm receiving error code 100 on the following when I try to update sift:

- docker-engine
- elasticsearch
- mantaray
- python-dfvfs
- python-plaso
- pytsk3

 I'm using wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i -s -y to do the update.

I tried the steps outlined in issue #80, but that didn't fix the problem.

Attached is the log.

[sift-install_log.txt](https://github.com/sans-dfir/sift/files/161722/sift-install_log.txt)

Thanks!

**Comment by ekristen** [comment]
@kmarker sorry you are having issues, it appears that your log file doesn't have any errors that I can see. Can you remove the sift-install log and then run the script again? 

For your convenience there should be a script called update-sift that does the process for you.

**Comment by kmarker** [comment]
Erik,  when I use the update-sift script I also get a 'updating dependencies failed' message that I don't get when I manually downloading the bootstrap and run it.  I attached the the wrong log in my first post.  My bad.  Here's the one that was generated from running the update-sift script.

[sift-install_log.txt](https://github.com/sans-dfir/sift/files/161947/sift-install_log.txt)

**Comment by ekristen** [comment]
Maybe run with the wget one more time and give me that log. I'm not seeing what I expect, but my suspicion is that the apt repo isn't getting added correctly, or your machine isn't able to pull down the apt repo listings and therefore can't find the packages it needs, but I'm not seeing the repo information or failures in the logs.

**Comment by kmarker** [comment]
Here's the log using the bootstrap from wget,

[sift-install_log.txt](https://github.com/sans-dfir/sift/files/162104/sift-install_log.txt)

**Comment by ekristen** [comment]
Still not seeing what I expect. How did you originally install?

Can you please tell me what is in /etc/apt/sources.list.d/

**Comment by kmarker** [comment]
The install was from the SIFT 3 VM. 
 
[source_list_d.txt](https://github.com/sans-dfir/sift/files/162169/source_list_d.txt)

**Comment by ekristen** [comment]
Are you on ubuntu 14.04?

Based on what I'm seeing you are missing the GIFT Repo and the Docker Repo which should be added when the script is run 

https://github.com/sans-dfir/sift-bootstrap/blob/master/bootstrap.sh#L164-L197

**Comment by kmarker** [comment]
Yes.  The SIFT 3 VM is Ubuntu 14.04.

**Comment by ekristen** [comment]
When you run the script do you see output like this?

```
 * INFO: Enabling Universal Repository ... 
 * INFO: Enabling Docker Repository ... 
 * INFO: Enabling Elastic Repository ... 
 * INFO: Adding Ubuntu Tweak Repository
 * INFO: Adding SIFT Repository: stable
 * INFO: Adding GIFT Ropository: Stable
 * INFO: Updating Repository Package List ...
```

**Comment by kmarker** [comment]
No.  I only get INFO: Updating your APT Repositories... and then it goes to INFO: Installed Package: aeskeyfind and all the other packages.

It's almost like the wget and the update-sfit script is getting an older version of the bootstrap.

**Comment by ekristen** [comment]
Are you running as root? I see no `sudo` on your `bash`?

You should run it like this, the script is not meant to be run as root. It is meant to be run as the user in which you plan to use all the tools.

`wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -iys`

If you are still having issues, send me the following output.

* `cat /etc/os-release`
* `wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | md5sum`

**Comment by kmarker** [comment]
No I'm running as root.  There is a sudo in my bash.  The command is a copy and paste from the site.

NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

1181dd312e3342e698997482ed862202  -

**Comment by ekristen** [comment]
It's the right file, that hash is correct. What does your prompt look like? 

This is the first I've heard of this problem, and I am unable to reproduce it. The only thing I can suggest next is downloading the bootstrap.sh locally, then `sudo bash bootstrap -iys` and see what happens.

Let me know what the screen output as well as the log output is.

I am unable to reproduce this on **any** test system I have.

**Comment by kmarker** [comment]
the prompt is sansforensics@siftworkstation so I'm definitely not root.

sansforensics@siftworkstation:~$

**Comment by ekristen** [comment]
Download the bootstrap file locally, run it like the previous comments has and let me know the output of both the log and in the console.

**Comment by kmarker** [comment]
Does any of your test system have sift and remnux both installed?

**Comment by ekristen** [comment]
yup ... can you confirm that these lines exist in the bootstrap script you are downloading https://github.com/sans-dfir/sift-bootstrap/blob/master/bootstrap.sh#L164-L197

**Comment by kmarker** [comment]
yup, they do.

**Comment by ekristen** [comment]
But when you run `sudo bash bootstrap.sh -iys` you do not need anything like 

```
 * INFO: Enabling Universal Repository ... 
 * INFO: Enabling Docker Repository ... 
 * INFO: Enabling Elastic Repository ... 
 * INFO: Adding Ubuntu Tweak Repository
 * INFO: Adding SIFT Repository: stable
 * INFO: Adding GIFT Ropository: Stable
 * INFO: Updating Repository Package List ...
```

in the first few dozen lines?

**Comment by kmarker** [comment]
no. As soon as it finishes, I'll post the output.

**Comment by ekristen** [comment]
Oh I think I might have an idea ... 

What do these three lines look like for you?

```
 * INFO: OS: Ubuntu
 * INFO: Arch: 64
 * INFO: Version: 14.04
```

**Comment by kmarker** [comment]
The same as yours.  Ubuntu 64 14.04.

**Comment by ekristen** [comment]
Alright, I the only thing that makes sense is that https://github.com/sans-dfir/sift-bootstrap/blob/master/bootstrap.sh#L166 is failing.

What happens when you run `sudo apt-get update` manually? Do you see any errors?

**Comment by kmarker** [comment]
apt-get updates fails to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release.  It's unable to find 'main/binary-i386/Packages' because of wrong sources.list entry or malformed file.

**Comment by kmarker** [comment]
I removed the google repo and it looks like it's working

**Comment by ekristen** [comment]
I'll try and add some more error handling error messages to make this more apparent in the future.

**Comment by madsumm** [comment]
Hi all,
not sure this helps.
I went into "Software & Updates" and click on Updates.
Unchecked Pre-released updates AND Unsupported Updates.
Run the software updater again from Ubuntu to clear out the old.

After which, run the SIFT wget.
This time round it worked perfectly with zero errors.

Of course, ensure all package managers and updaters have completed prior to start SIFT Wget.
It seems some packages are conflicting?
Reds
Mathew
