### ISSUE TITLE
A lot of broken functions today when creating SIFT3 from ISO

### ISSUE THREAD

**Issue by madsumm** [sans-dfir/sift#104]
Found Volatility not working. Rekall not working. log2timeline.py not working.
Dependencies seems to have changed or missing.

(Rekall seems to be updated to 1.5.0 - after pip install, it worked.)

There could be other functions that are not working as well. Seems the SIFT broke somewhere.

**Comment by ekristen** [comment]
Can you please be a little more detailed? What do you mean from ISO?

**Comment by madsumm** [comment]
Sorry, 

What I means was the detailed ISO install of Ubuntu and then wget way of install.

It used to be working fine, but not the last days. 2 of us having issues creating workable SIFT at this moment.

All install info on screen doesn’t have any errors and completed successfully. Including update-sift. But some functions like volatility is not working due to missing or wrong dependencies like distrom3.
Let me know if you need other info. Will be glad to provide and help,
Rgds

**Comment by ekristen** [comment]
If you can please send me your sift-install.log and any other details. I'll run through another install.

If you can send me the commands you've been running any samples used etc will all help. 

Also the errors you are receiving.

**Comment by ekristen** [comment]
I added `distorm3` back.

**Comment by ekristen** [comment]
`python-dateutil` was installed in `2.5.1` and rekal requires `2.4.2`, pinned it to 2.4.2 for now

**Comment by madsumm** [comment]
This was one of the issue. I did a pip install back for rekall and it fixed that but not the rest.
I will try to reinstall again and test.
Reds

**Comment by madsumm** [comment]
I tried full install again.

Volatility works now- THANKS!

However Rekall does not. I still did a pip install and it resolved it for now.

Rgds
Mathew

**Comment by madsumm** [comment]
log2timeline.py error:

[FAILURE] libewf (pyewf) version : 20130416 is too old, 20131210 or later required.

Reds

**Comment by ekristen** [comment]
Can you send your install log. I cannot duplicate the log2timeline.py issue. The newer library should be installing.

**Comment by ekristen** [comment]
@madsumm are you still having problems? I did identify one issue and resolve it.

**Comment by ekristen** [comment]
If this is still an issue feel free to re-open.
