### ISSUE TITLE
Sansforensics profile as root

### ISSUE THREAD

**Issue by iHax2244** [sans-dfir/sift#105]
I did a manual install of SIFT on Ubuntu 14.0.4 64bit, it seems to have installed perfectly but instructions on the installation page say to log in with user name "sansforensics" and password "forensics". If this isn't the default root can someone enlighten me?

**Comment by JohnEbert** [comment]
That's what I use...

**Comment by ekristen** [comment]
Unless you created that user when and ran the bootstrap script under that user when you install Ubuntu it won't exist. 

The install script purely installs all packages and modifies the current users profile.

**Comment by JohnEbert** [comment]
Well then, I guess I'd try root, and toor

**Comment by iHax2244** [comment]
Looks like the only profile that works is the one I made before installing the packages. Tried everything else and it didn't work guess its okay for now till I learn the way this SIFT workstation works. Thanks guys!

**Comment by ekristen** [comment]
The user doesn't really matter but if you want it to be the exact same as the instructions from SANS Course, just create the sansforensics user and run the install script under that account.

**Comment by iHax2244** [comment]
Thanks ekristen
