### ISSUE TITLE
Error with vol after adding RemNUX to workstation

### ISSUE THREAD

**Issue by DFIR-Zach** [sans-dfir/sift#107]
[This](https://imgur.com/b83gIxo) error occured when trying to run imageinfo against a physical mem file.  I thought the syntax for location may have been incorrect (export VOLATILITY_LOCATION=file:///cases/PhysicalMemory), but also tried that as well and to no avail.  
This also occurred during my SANS FOR508 class a couple weeks ago when myself and others ran updates on the SIFT workstation.

**Comment by ekristen** [comment]
Looks like RemNUX hasn't removed edit box yet. If you run the `update-sift` command it should fix this problem for you. The Editbox plugin isn't compatible with the latest version of Volatility. The `update-sift` command will remove it for you.

**Comment by DFIR-Zach** [comment]
Awesome! Thanks for your fast response :)

**Comment by ekristen** [comment]
Anytime.
