### ISSUE TITLE
SIFT Install - Ubuntu 14.04

### ISSUE THREAD

**Issue by blackice7** [sans-dfir/sift#108]
So I have created a snapshot prior to installing SIFT on my VM, however I keep running into an issue. After installing SIFT and rebooting, I login and get an empty Desktop. I have tried several times, but am not getting anywhere. I installed it from a terminal in the GUI.

I've tried **sudo -su** and **sudo -s** and **sudo wget ......** without any luck. Has anyone seen this before or have any idea what the fix is for this?

**Comment by ekristen** [comment]
Please provide the following information:

* Exact steps you are taking
* The sift-install.log file in your home directory
* Any additional information you might feel is relevant.

**Comment by ekristen** [comment]
@blackice7 if you are still having issues please feel free to re-open.
