### ISSUE TITLE
Rekall 1.5.0 Install Failure

### ISSUE THREAD

**Issue by diogo-fernan** [sans-dfir/sift#109]
Getting the following errors in `sift-install.log` on a brand new SIFT workstation built on a new VirtualBox Ubuntu 14.04.4 VM using the `bootstrap.sh` method:

> Downloading/unpacking rekall
>   Running setup.py (path:/tmp/pip_build_root/rekall/setup.py) egg_info for package rekall
>     
>     warning: no files found matching '*' under directory 'test_data'
>     warning: no previously-included files matching '*.a' found under directory 'tools'
>     warning: no previously-included files matching '*.la' found under directory 'tools'
>     warning: no previously-included files matching '*.lo' found under directory 'tools'
>     warning: no previously-included files matching '*.o' found under directory 'tools'
>     warning: no previously-included files matching '*' found under directory '.git'
>     warning: no previously-included files matching '*' found under directory 'build'
>     warning: no previously-included files matching '*' found under directory 'tools/pmem/.deps'
>     warning: no previously-included files found matching 'tools/pmem/linpmem'
> Downloading/unpacking rekall-core>=1.5.0 (from rekall)
>   Running setup.py (path:/tmp/pip_build_root/rekall-core/setup.py) egg_info for package rekall-core
>     *****************************************************
>       WARNING: You are not installing Rekall in a virtual
>       environment. This configuration is not supported!!!
>       Expect breakage.
>     *****************************************************
>     error in rekall-core setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
>     Complete output from command python setup.py egg_info:
>     *****************************************************
> 
>   WARNING: You are not installing Rekall in a virtual
> 
>   environment. This configuration is not supported!!!
> 
>   Expect breakage.
> 
> *****************************************************
> 
> error in rekall-core setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
> 
> ----------------------------------------
> Cleaning up...
> Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/rekall-core

Is this a Rekall issue? Any ideas?

Thanks.

**Comment by ekristen** [comment]
Did you find what the problem was?

**Comment by diogo-fernan** [comment]
Outdated Python version.
