### ISSUE TITLE
Hello, i have a problem with sift.

### ISSUE THREAD

**Issue by giogke** [sans-dfir/sift#111]
I have installed it, but i dont have the tools and when i try to install , it shows error code 100
[sift-install.log.zip](https://github.com/sans-dfir/sift/files/307120/sift-install.log.zip)

**Comment by ekristen** [comment]
What command did you run?

What OS version?

What packages show error 100?

This log shows no errors installing any packages except a python package.

I need more information.

**Comment by ekristen** [comment]
If you have the following information, please feel free to re-open the issue.
