### ISSUE TITLE
Build Packages for Xenial (16.04)

### ISSUE THREAD

**Issue by ekristen** [sans-dfir/sift#118]
- [x] - bulk-extractor (source: https://github.com/simsong/bulk_extractor)
- [x] - liblightgrep
- [x] - passivedns 
- [x] - plaso (waiting for the plaso team to release 16.04 packages)
- [x] - volatility
- [x] - wireshark

**Comment by ekristen** [comment]
Source: https://github.com/zrlram/afterglow

Continue to build package or just check out the file and drop it into a directory?

**Comment by bergernetch** [comment]
Has there been any progress towards 16.04 LTS support?

**Comment by ekristen** [comment]
Yes. I'll post instructions for you to be able to test today. I'm mobile at the moment.

**Comment by ekristen** [comment]
https://github.com/sans-dfir/sift-saltstack

**Comment by ekristen** [comment]
All necessary packages are built for 16.04
