### ISSUE TITLE
The update-sift script breaks srch_strings

### ISSUE THREAD

**Issue by the-IMOL** [sans-dfir/sift#119]
Summary: began with a fresh install of SIFT 3 (md5:  4cf6276a67f38980065f8563cb49fe46) and opened with VMware 10. Ran a test with srch_strings and it worked as expected.

Ran the update-sift script and (after succesful completion) then ran the same srch_strings command on the same target file and received the error message: 

**\* Error in `srch_strings': double free or corruption (fasttop): 0x00000000024d1250 ***
Aborted (core dumped)

Error is consistent and can be reproduced as described above.

**Comment by ekristen** [comment]
Thanks for the report @the-IMOL, when you say you started with a fresh SIFT 3, do you mean the VM image from the SANS Forensics website?

**Comment by the-IMOL** [comment]
Yes the VM image (in OVF format).

**Comment by 53686f63636f** [comment]
I have the same issue using a fresh install of sift after updating  using update-sift. Running the VM on vmware 12 installed from the OVF

**Comment by MrSecure** [comment]
I'm seeing the same issue.   Followed through the Ubuntu error reporting prompt to submit a report upstream, but I'm not sure what happens with that.

**Comment by efutch** [comment]
Built a fresh Ubuntu 14.04 VM, then installed SIFT with wget.  After running update-sift script, have the same issue with search_strings

**Comment by ekristen** [comment]
I have confirmed this problem. I am unsure as to what the cause is at this time.

**Comment by ekristen** [comment]
As we are no longer supporting 14.04 going forward, 16.04 VM is about to be released, and the [sift-saltstack](https://github.com/sans-dfir/sift-saltstack) is the now preferred method of install, we will re-open this issue if it is still happening there.
