### ISSUE TITLE
Problem updating

### ISSUE THREAD

**Issue by zappeee** [sans-dfir/sift#120]
I'm on the SIFT precompiled VM.
When I'm running "sudo update-sift" I get this error before it quits.

INFO: SIFT VM: Installing SIFT Files
./bootstrap.sh: line 457: cd: /tmp/sift-files: No such file or directory

Also, when running apt-get upgrade there's a lot of packages to be updated.
Can I update everything without breaking SIFT?
Can I do dist-upgrade to?

**Comment by ekristen** [comment]
14.04 is the only distro supported we are working on supporting 16.04

**Comment by zappeee** [comment]
I'm on 14.04.

I noticed this in the logs
"fatal: unable to access 'https://github.com/sans-dfir/sift-files/': Failed to connect to github.com port 443: Connection refused"

I'm able to reach that URL outside the VM, but not inside.
Any clues why?

**Comment by ekristen** [comment]
Proxy? Bad DNS?

**Comment by zappeee** [comment]
I don't use proxy and bad dns how?
It resolves to the same ip as on my host machine.

**Comment by ekristen** [comment]
The only other thing I can think of is a something that is not configured correctly or something wrong with the VM configuration and host setup.

**Comment by zappeee** [comment]
Yeah, but I cannot figure out what.
I found this in the log now

"fatal: unable to access 'https://github.com/sans-dfir/sift-files/': gnutls_handshake() failed: Access was denied"

But if I run "git clone --recursive https://github.com/sans-dfir/sift-files /tmp/sift-files" manually it works.

**Comment by ekristen** [comment]
Check your date/time on your VM? A quick google search shows its possibly a problem with outdate git, maybe openssl or ca certificates, I'd make sure those are up to date.

**Comment by zappeee** [comment]
I tried installing a Ubuntu 14.04 in a new VM then running "wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i -s -y" and now it gives me "Connection refused" error again.
This time on a different network.

**Comment by ekristen** [comment]
Are you using the same host on all these tests?

**Comment by zappeee** [comment]
Yes.

**Comment by ekristen** [comment]
My best guess at this point is it is a host/VM configuration or guest networking problem. From what you have said earlier it seems that TLS connections are not being trusted.

**Comment by zappeee** [comment]
For some reason it worked when I got to the other network today.
I got some parsing/install errors during the update though, where can I update the log?

**Comment by ekristen** [comment]
You can upload where you can, gist, pastebin, google drive, etc and link it here.

**Comment by zappeee** [comment]
http://pastebin.com/h514E27i

**Comment by zappeee** [comment]
Did you have time to look?

**Comment by ekristen** [comment]
Looks like some dependencies didn't get installed for the python libraries. I'll run a build today to validate.

Erik

**Comment by ekristen** [comment]
Just completed a full install on a fresh ubuntu 14.04 desktop and it completely with zero errors.

**Comment by zappeee** [comment]
Alright, what do I need to do to fix mine?

**Comment by ekristen** [comment]
Honestly I'm not sure. I can't duplicate the behavior you are seeing. I went to take a look at your log again but it was deleted. If you can post it again I'll look one more time, to see if I see anything out of the ordinary.

**Comment by zappeee** [comment]
http://pastebin.com/Z0G1FTYk

**Comment by ekristen** [comment]
Looks like we've got some new issues with python modules that weren't surfacing in the install script, so I'll have to take a look at that. 

It also seems like the install script for the sift-files might not be doing all the files properly, so I'll take a look at that as well.

Beyond those two items, all other packages installed properly. What are you looking for specifically that isn't working?

**Comment by zappeee** [comment]
Nothing that I'm aware of at the moment, just those error messages you saw.

Thanks for looking into it!

**Comment by ekristen** [comment]
No problem. There are definitely a few issues I'll address. 

Erik
