### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by AlexandreSanchez** [sans-dfir/sift#121]
Hello !

can't find a way to uninstall it (on Ubuntu) after a bootstrap installation.
I've been looking for a while this information without success.

Can you help me ?

Best Regards.

**Comment by ekristen** [comment]
There is no specific way to uninstall other than to remove all the packages. If you used the `-iys` feature then it would have changed the user's background and setup symlinks etc, you can undo all those. 

You can look at the bootstrap script and the under the sift-files repo you can look at the install script there and manually undo everything they do.

**Comment by AlexandreSanchez** [comment]
Hum... thanks. 
I should have think it before installing with sudo...
I'll try.
BR.
