### ISSUE TITLE
/usr/lib/vmware-tools/sbin/vmware-checkvm high load

### ISSUE THREAD

**Issue by adamziaja** [sans-dfir/sift#129]
if someone have problem on VirtualBox with high load because of `/usr/lib/vmware-tools/sbin/vmware-checkvm` then for fix you can uninstall VMware tools by script `/usr/bin/vmware-uninstall-tools.pl`

**Comment by ekristen** [comment]
Thanks for the info, the VM is definitely build specifically for VMWare at this time.
