### ISSUE TITLE
SIFT login issue

### ISSUE THREAD

**Issue by scrp10nkng** [sans-dfir/sift#130]
Hi, so I just installed SIFT on Ubuntu 14.04 on virtualbox. I run into some issues. I run the wget and piped that into the sudo bash command to configure and it was successful. No issues. After the configuration was complete, I rebooted and tried logging in. The SIFT theme etc are all there, but the only ids that I see listed for login are guest and my initial id. The sans documentation says to login using "sansforensics" but that does not exist. I went through the passwd file and the id does not exist. So I tried running the wget first as my regular id, and second as root. Same results as above. I'm unable to utilize the SIFT workstation currently. Any assistance in remediating this will be greatly appreciated.

**Comment by ekristen** [comment]
Just login using your original ID, everything installed under that user.

**Comment by scrp10nkng** [comment]
Thanks Erik. I looked under the /opt directory and did not see anything and got spooked. I'll search to see where the files might have been installed.

**Comment by ekristen** [comment]
Sift isn't just some files that get installed to /opt.

If you see no visible difference then it most likely didn't install properly.

There is a sift install log in your home directory please upload that.
