### ISSUE TITLE
SIFT installation advocating bad security practice

### ISSUE THREAD

**Issue by joachimmetz** [sans-dfir/sift#133]
Please stop advocating bad security practice

From: http://digital-forensics.sans.org/community/downloads

```
Once installed, open a terminal and run "wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i -s -y"
```

For clarification see:
* https://www.seancassidy.me/dont-pipe-to-your-shell.html
* https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/

**Comment by joachimmetz** [comment]
> In general it's not wise to just pipe a bash script to sudo

or downloading and running a script as sudo without either checking its content or integrity.

> We are not nor are we advocating disabling TLS checks,

Good, but know not every CLI tool will do TLS checks and setting can vary per system.

As indicated per mail, feel free to reach out see what alternative solution we can come up.

**Comment by ekristen** [comment]
## WIP: The Plan 
1. I'm going to start signing every commit
2. I'm going to start signing every release
  * This means that when I tag the salt states for SIFT and the tar.gz file is created by GitHub, I'm going to download and sign it and upload the signature.
3. I'm writing a forensics distro CLI tool that will manage SIFT as well as REMnux in the near future. Might just be a shell script in its first iteration.
  * This tool will download the .tar.gz files from the appropriate repository releases directory and validate the PGP key
  * This tool will then put the downloaded files into a temporary directory
  * This tool will then call saltstack to run all the states to configure the system properly.

**Comment by joachimmetz** [comment]
sounds like a plan; for context

1 and 2 I've been thinking about this is as well for libyal and plaso, but decided to start with 2 first (have a slightly different release process), seeing it is the low hanging fruit

for me a decisions to hold off on 1
* limited commit access to git repo(s) and IMHO it should be used for development
* have some means to include the integrity check of 1 into 2

For 3 let me know if you want sync on extending https://github.com/log2timeline/l2tdevtools
I was thinking adding a gpg package signature (.asc file) check for packages that provide it
we already use it for various different build targets

**Comment by ekristen** [comment]
1. all commits are signed
2. all releases are hashed and signed
3. there is a new [tool](https://github.com/sans-dfir/sift-cli) that can be installed and used to install, update and upgrade to all new releases of SIFT.

**Comment by joachimmetz** [comment]
great, thx for addressing this
