### ISSUE TITLE
duplicates scripts and dead submodules in sift-files

### ISSUE THREAD

**Issue by juju4** [sans-dfir/sift#134]
Some files are present multiples times like  extract_mft_record_slack.py, ShellItems.py, shellbags.py
https://github.com/sans-dfir/sift-files/tree/master/wbtools
https://github.com/sans-dfir/sift-files/tree/master/scripts

Also these submodules links are dead
- Java_IDX_Parser
- PE_Carver

**Comment by ekristen** [comment]
This is all being reworked with https://github.com/sans-dfir/sift-saltstack
