### ISSUE TITLE
[devel] ppa issues

### ISSUE THREAD

**Issue by juju4** [sans-dfir/sift#136]
* current ppa/dev has not all packages right? flowgrep, ntdsextract nok
still appear with xenial filter
https://launchpad.net/~sift/+archive/ubuntu/dev?field.series_filter=xenial

* bulk-extractor : Depends: openjdk-7-jdk but it is not installable
on xenial, choice is between 8 and 9

* will ppa be reviewed for upcoming new LTS ? 17.04 LTS is scheduled for April 2017
https://wiki.ubuntu.com/Releases
from a CI perspective, adding new distribution will be easy. ppa are less, mostly sift and gift.

**Comment by ekristen** [comment]
Some packages will not be in the new 16.04 version or are available from other repos.

I will look at bulk extractor.

17.04 will not be a LTS, those only happen every 2 years.

**Comment by ekristen** [comment]
bulk_extractor installs just fine.

**Comment by juju4** [comment]
Hello @ekristen 

just to be sure, issue was bulk-extractor depends on openjdk-7-jdk whereas there is only openjdk-8-jdk or openjdk-9-jdk at least on xenial.
I did an install this morning and had to use ```dpkg --force-depends -i /root/bulk-extractor_1.5.5-trusty2_amd64.deb```

Currently there is no xenial tagged bulk-extractor package in
https://launchpad.net/~sift/+archive/ubuntu/dev
http://ppa.launchpad.net/sift/dev/ubuntu/pool/main/b/bulk-extractor/

I believe just a dsc edit on "depends" field should be enough

**Comment by ekristen** [comment]
Interesting, I didn't have a problem installing it, but now I am, let me take a closer look.

**Comment by ekristen** [comment]
Ah, yes, we add an openjdk ppa to get java7 on xenial, I've fixed the salt state so the correct dependencies are included to make the state run by itself. The commit is coming shortly.

**Comment by juju4** [comment]
but do you plan to fix the package in the ppa?

also seeing at the diff, I understand it as 
- trusty: use openjdk-6
- xenial: use 7
which is a version below of what available. trusty has 6 (EOL/http://www.oracle.com/technetwork/java/eol-135779.html) and 7, xenial has 8 and 9

**Comment by ekristen** [comment]
Most likely not. The package isn't officially supported and we will most likely move to installing bulk extractor from its Git repo into a virtual env to prevent python dependency collisions.

Erik
