### ISSUE TITLE
update-sift malfuctioning

### ISSUE THREAD

**Issue by DavidMelons** [sans-dfir/sift#139]
Hi guys.
I've downloaded the latest SIFT3 Workstation from SANS Forensics website.
Trying to update the installation with the update-sift script I got some errors:

Cloning into '/tmp/sift-files'...
Submodule '4n6-scripts' (https://github.com/cheeky4n6monkey/4n6-scripts) registered for path '4n6-scripts'
No submodule mapping found in .gitmodules for path 'Java_IDX_Parser'
cp: cannot stat ‘pe_carver/*.py’: No such file or directory
cp: cannot stat ‘page_brute/*.py’: No such file or directory
cp: cannot stat ‘java_idx_parser/*.py’: No such file or directory
cp: cannot stat ‘4n6-scripts/*’: No such file or directory
chmod: cannot operate on dangling symlink ‘/usr/local/bin/l2t_process’
All done. Enjoy your privacy.
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file /etc/rc.local.rej
patch: **** malformed patch at line 10:      +      if stat_object.bkup_time_nano is not None:

from what I saw the `cp: cannot stat [...]` errors are related to directory names  mismatches between the ones created in /tmp/sift-files during the cloning phase and the "path" values in `.gitmodules`
I don't know about the "malformed patch at line 10" issue.
Thank you.
  Davide

**Comment by ekristen** [comment]
Unfortunately a few things have become broken in the script. All new efforts have been put toward a more robust build and update system that will support ubuntu 16.04 and on. 

As for the errors you are seeing, you should be able to ignore them. If you'd like to know for sure please email me off list and I can tell you what specifically failed.

Regards,
Erik

**Comment by DavidMelons** [comment]
thank you Erik. I understand the point.
I'll try the beta sift-saltstack-on-ubuntu16.04 way, than.
ciao
Davide
