### ISSUE TITLE
sift-saltstack missing sift/files/salt-minion/minion config file?

### ISSUE THREAD

**Issue by jlerch** [sans-dfir/sift#141]
Using new ubuntu 16.04 LTS, followed steps in README.md.

`sudo salt-call --local --file-root=/tmp/salt state.sls sift`

returns: 
```
 ID: salt-minion-config
    Function: file.managed
        Name: /etc/salt/minion
      Result: False
     Comment: Source file salt://sift/files/salt-minion/minion not found
     Started: 17:18:37.016508
    Duration: 1.446 ms
     Changes:  
``` 

I created a new folder /tmp/salt/sift/files/salt-minion then copied the default /etc/salt/minion file into this folder and then the install ran to completion.  I'm not confident this was the "right" answer, any suggestions?

Attached file jlsalt.zip contains output of install that failed and then succeeded after my attempt at a workaround.
[jlsalt.zip](https://github.com/sans-dfir/sift/files/819635/jlsalt.zip)

Kind Regards,
James

**Comment by ekristen** [comment]
Definitely a bug, I had this fixed locally, just hadn't pushed it up yet. Resolved in https://github.com/sans-dfir/sift-saltstack/commit/91982b4baad9857224033eca8928a02f6ab9c957
