### ISSUE TITLE
Add pyhindsight

### ISSUE THREAD

**Issue by obsidianforensics** [sans-dfir/sift#142]
Hi Erik,

Thanks for all the work you do maintaining this. I've recently updated Hindsight (https://github.com/obsidianforensics/hindsight) to v2, and as part of that refactored it and made it installable via pip (pyhindsight). Could you please change sift to use that package instead of the standalone script? When installing pyhindsight via pip, it should add hindsight.py and hindsight_gui.py to the system's scripts folder, which is how end users should run Hindsight. 

I'd submit a PR, but I don't understand the sift system well enough and I'd probably end up messing it up more than helping :/. If I need to change pyhindsight in any way to facilitate including it this way, please let me know. It's my first Python package so it might have rough edges.

Thanks!
-Ryan

**Comment by ekristen** [comment]
Done
