### ISSUE TITLE
wget command isn't working properly

### ISSUE THREAD

**Issue by MMULLINIX1** [sans-dfir/sift#147]
When I try to install on top of a 14.04.5 LTS and I copy/paste the command, it asks me for my password but then goes back to command prompt and does nothing. When I try to use the appliance, I can't change the proxy setting from within the appliance. One of these has to work. I'm using this on a workstation within my lab.

**Comment by MMULLINIX1** [comment]
I've tried the gsettings command, I've tried to edit the non-existent etc/environment. Please help :)

**Comment by ekristen** [comment]
https://stackoverflow.com/questions/11211705/setting-proxy-in-wget
