### ISSUE TITLE
sift installation problem on vmplayer for linux ubuntu

### ISSUE THREAD

**Issue by SiThu9** [sans-dfir/sift#148]
hi 
I got the issue when i install the sift on my ubuntu on vmplayer.
![capture](https://cloud.githubusercontent.com/assets/29085408/26616181/4f2d5794-45ff-11e7-9eb5-9fda409eaeab.JPG)
![capture](https://cloud.githubusercontent.com/assets/29085408/26616208/77067bec-45ff-11e7-98ee-538ed0752b85.JPG)

**Comment by SiThu9** [comment]
I got this issue too
![capture2](https://cloud.githubusercontent.com/assets/29085408/26616442/2e44d992-4601-11e7-9e52-b7b4443aab04.JPG)

**Comment by ekristen** [comment]
the bootstrap script is no longer supported, please see https://github.com/sans-dfir/sift-saltstack, a CLI tool to make this process more seamless is in the works.
