### ISSUE TITLE
Saltstack SIFT Install Fails

### ISSUE THREAD

**Issue by esecrpm** [sans-dfir/sift#149]
After installing ubuntu 16.04 and Saltstack per the README, I receive the following error when trying to install the SIFT packages.  Can you please advise what may be causing the error?

Thanks,
Erik

```
sansforensics@siftworkstation:~$ sudo salt-call --local --file-root=/tmp/salt state.sls sift
[ERROR   ] Template was specified incorrectly: False
local:
    Data failed to compile:
----------
    No matching sls found for 'sift' in env 'base'
```

I followed the directions exactly as noted (output in attached txt file).
[SaltstackSIFTInstall.txt](https://github.com/sans-dfir/sift/files/1041833/SaltstackSIFTInstall.txt)

**Comment by malfind2017** [comment]
I have also experienced the same error as posted by Erik. I can run sift.packages but I'm unable to compile the sift package with error "No matching sls found for 'sift' in env 'base'"

**Comment by ekristen** [comment]
Change your command to 

```
sudo salt-call --local --file-root=/tmp/salt state.sls sift.vm
````

OR if you just want the packages without the configs and user setup

```
sudo salt-call --local --file-root=/tmp/salt state.sls sift.pkgs
```

**Comment by The-Betrayer** [comment]
I'm getting the same error on a clean Ubuntu 16.04.02 LTS:

$ sudo salt-call --local --file-root=/tmp/salt state.sls sift.vm
[ERROR   ] Template was specified incorrectly: False
local:
    Data failed to compile:
----------
    No matching sls found for 'sift.vm' in env 'base'


And a very familiar error now for the packages as well:

$ sudo salt-call --local --file-root=/tmp/salt state.sls sift.pkgs
[ERROR   ] Template was specified incorrectly: False
local:
    Data failed to compile:
----------
    No matching sls found for 'sift.pkgs' in env 'base'

**Comment by esecrpm** [comment]
Thanks Erik, this worked for me.
