### ISSUE TITLE
Installation of swift Toolkit on Ubuntu

### ISSUE THREAD

**Issue by dudu500** [sans-dfir/sift#150]
wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i -s -y

gives this error message:

**Comment by ekristen** [comment]
You didn't provide the error message, but the bootstrap script is now deprecated, please see https://github.com/sans-dfir/sift-saltstack, a CLI tool to make this more seamless is in the works.
