### ISSUE TITLE
sift workstation 3

### ISSUE THREAD

**Issue by gargvanshaj** [sans-dfir/sift#151]
I am on Ubuntu 16.04, Python version is 2.7.12. While installing sift workstation it giving error-
The only 3 packages that couldn't be install.
![screenshot from 2017-06-08 02-33-56](https://user-images.githubusercontent.com/23193039/26901813-b20646e6-4bf4-11e7-850b-e1c352458d0c.png)
![screenshot from 2017-06-08 02-34-38](https://user-images.githubusercontent.com/23193039/26901836-c0ec38b4-4bf4-11e7-8810-3dacd40d0df5.png)
![screenshot from 2017-06-08 02-33-12](https://user-images.githubusercontent.com/23193039/26901841-c61b9834-4bf4-11e7-866a-99955601da60.png)

**Comment by ekristen** [comment]
No other logs? All these states have been thoroughly tested and they work. Have you tried subsequent runs?

**Comment by gargvanshaj** [comment]
All other packages installed successfully. I only mentioned the packages that couldn't be installed.
While installing it first time the Internet was not working well so the process went failed at that time but after then i tried to install it second time with the same command and i got this error.
The command that i used:- "sudo salt-call --local --file-root=/tmp/salt state.sls sift.pkgs"

**Comment by ekristen** [comment]
I cannot reproduce, I will need more logs to be able to help troubleshoot this. You can add `-l debug` to the salt-call command.
