### ISSUE TITLE
SIFT download instructions

### ISSUE THREAD

**Issue by nutzin** [sans-dfir/sift#152]
Being that the bootstrap is depreciated, could you please update the sans.org site to reflect the new installation links and instructions?

https://digital-forensics.sans.org/community/downloads

Thanks for the great software and all the time you put into it!

**Comment by ekristen** [comment]
It's in the works! For now the instructions on that website are still valid for downloading the VM image. If you'd like to install on 16.04, please see the README on this repository for the instructions.
