### ISSUE TITLE
CLI Install issue

### ISSUE THREAD

**Issue by dnice77** [sans-dfir/sift#155]
Hi Erik,

Not exactly sure if there is something I'm overlooking but I followed the instructions outlined and for some reason when I move the CLI tools to "/usr/bin/local/sift" the sift commands aren't available. I've also tried compiling from source and nodejs is giving me errors when attempting to run the sift-cli.js
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Any clue what exactly I'm doing wrong or indicator on how to resolve it?

**Comment by ekristen** [comment]
You have to make sure that your path variable includes /usr/local/bin.

**Comment by dnice77** [comment]
I ran this command export PATH=$PATH:/usr/local/bin/ still nothing...I gotta be missing something.

**Comment by ekristen** [comment]
Does it work if you do sudo /usr/local/bin/sift --help

**Comment by dnice77** [comment]
I moved the sift-cli-linux to /usr/local/bin/sift and ran your command. output is "command not found"

**Comment by ekristen** [comment]
The move must not have been successful, can you walk me through all your steps?

**Comment by dnice77** [comment]
Let me say that this was a clean install from an 16.04 VM...
I literally followed the instructions verbatim:
Go to the Latest Releases
Download all the release files
sift-cli-linux
sift-cli-linux.sha256.asc
Import the PGP Key - gpg --keyserver pgp.mit.edu --recv-keys 22598A94
Validate the signature gpg --verify sift-cli-linux.sha256.asc
Validate SHA256 signature sha -a 256 -c sift-cli-linux.sha256.asc
You'll see an error about improperly formatted lines, it can be ignored so long as you see sift-cli-linux: OK before it
Move the file to mv sift-cli-linux /usr/local/bin/sift

**Comment by dnice77** [comment]
Just to see if something was in fact done wrong on my end I replicated the instructions on a legacy build of SIFT and same problem.

**Comment by ekristen** [comment]
What happens when you run ...

'ls -la /usr/local/bin/sift'

**Comment by dnice77** [comment]
It says my local account owns it...do I need to chmod it?

**Comment by ekristen** [comment]
chmod 755 it

**Comment by dnice77** [comment]
Holy shit, you gotta be kidding me...totally fixed it. The most basic Linux permissions bullshit fixed it. Might want to add this to the instructions so you don't waste your time helping others with this issue. Thanks for seeing it through man

**Comment by ekristen** [comment]
I'll add it to the readme.

**Comment by ekristen** [comment]
Glad it's fixed
