### ISSUE TITLE
[CLI]Saltstack failed install SIFT 14.04. Will there be continuing support for SIFT 14.04?

### ISSUE THREAD

**Issue by Fetchered** [sans-dfir/sift#156]
Trying to update my sift, now being told the bootstrap.sh is deprecated. Have to download the bootstrap manually from legacy. So I decided I'll move to the sift-cli. Everything goes great until I do
`sift update` then I get:
`sansforensics@siftworkstation:~$ sudo sift update`
`> sift-cli@1.5.0-beta.0-master.16cfb94`
`> sift-version: notinstalled`

`Installing and configuring SaltStack properly ...`

`Command failed: apt-get install -y salt-minion`
`E: Unable to correct problems, you have held broken packages.`

`Error: Command failed: apt-get install -y salt-minion`
`E: Unable to correct problems, you have held broken packages.`

`    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`
`sansforensics@siftworkstation:~$`

So I tried: `sansforensics@siftworkstation:~$ sudo apt install salt-minion`
`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`Some packages could not be installed. This may mean that you have`
`requested an impossible situation or if you are using the unstable`
`distribution that some required packages have not yet been created`
`or been moved out of Incoming.`
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:`
` salt-minion : Depends: init-system-helpers (>= 1.18~) but 1.14ubuntu1 is to be installed`
`               Depends: lsb-base (>= 4.1+Debian11ubuntu7) but 4.1+Debian11ubuntu6.2 is to be installed`
`               Recommends: debconf-utils but it is not going to be installed`
`E: Unable to correct problems, you have held broken packages.`
`sansforensics@siftworkstation:~$ 
`
The above has occurred on three different SIFT VM's; The Distro version straight from the site, and two VM's provided from SANS classes in various states of update.
I noticed that the sift-cli is in Beta/Pre-release right now. Will there be continued support for SIFT 14.04? If so, shouldn't the bootstrap remain intact until the sift-cli is out of pre-release/beta?
Any assistance would be appreciated.

**Comment by ekristen** [comment]
hi @Fetchered, 14.04 is now over 3 year old and is not longer being supported by SIFT going forward. The old sift-bootstrap script is still available, and is the only way to install SIFT on 14.04.

I highly recommend you switch to using 16.04 and the new SIFT CLI tool.

**Comment by Fetchered** [comment]
Very good, will do.
