### ISSUE TITLE
Request for help with SIFT

### ISSUE THREAD

**Issue by hkoncke** [sans-dfir/sift#158]
Hi, hello everybody and sorry for my basic and elemental request for help.
I used to work on Unix/AIX, but that was more than 20 years ago, so my *nix knowledge is a little bit rusty by now.
I'm trying to install the SIFT tool and then to learn to use it.
I set up an Ubuntu 16.02 machine and I downloaded the sift-cli-linux files. Now there's nothing I can do with them. I guess the sift-cli-linux is a package that should be opened with some tool, but I don't know what should I do. 
Can someone shed some light on me about this?
Thanks a lot in advance.

**Comment by ekristen** [comment]
It's an binary that you need to execute using the command line. Please see https://github.com/sans-dfir/sift-cli for the installation instructions and the usage of the command.
