### ISSUE TITLE
[CLI] Verify signature

### ISSUE THREAD

**Issue by zappeee** [sans-dfir/sift#164]
I didn't get the "sha" command working, it says it was not found.

sansforensics@ubuntu:~/Downloads$ sha -a 256 -c sift-cli-linux.sha256.asc
No command 'sha' found, did you mean:
 Command 'lha' from package 'jlha-utils' (universe)
 Command 'lha' from package 'lhasa' (universe)
 Command 'shc' from package 'shc' (universe)
 Command 'sea' from package 'alliance' (universe)
 Command 'ha' from package 'ha' (universe)
 Command 'shar' from package 'sharutils' (main)
 Command 'aha' from package 'aha' (universe)
 Command 'sma' from package 'sma' (universe)
 Command 'sa' from package 'acct' (main)
 Command 'sh' from package 'dash' (main)
sha: command not found

Working with "shasum" though.

**Comment by min0rchanges** [comment]
The correct command is sudo sha256sum -c sift-cli-linux.sha256.asc. Has to be fixed in the documentation.
