### ISSUE TITLE
Mantaray Install Issues - Ubuntu 16.04.2

### ISSUE THREAD

**Issue by mformal** [sans-dfir/sift#166]
Any updates that allow Mantaray to run on Ubuntu 16.04.2?

I Installed SIFT no problem by doing the following:
Go to the Latest Releases
Download all the release files

sift-cli-linux
sift-cli-linux.sha256.asc
Import the PGP Key - gpg --keyserver pgp.mit.edu --recv-keys 22598A94
Validate the signature gpg --verify sift-cli-linux.sha256.asc
Validate SHA256 signature sha -a 256 -c sift-cli-linux.sha256.asc
You'll see an error about improperly formatted lines, it can be ignored so long as you see sift-cli linux: OK before it
Move the file to mv sift-cli-linux /usr/local/bin/sift
Run chmod 755 /usr/local/bin/sift
Type sift --help to see its usage
I then followed the MantaRay Install Instructions and had the following errors:

sudo add-apt-repository ppa:mantaray/stable
sudo apt-get update

PPA:
$ sudo apt-add-repository ppa:mantaray/stable
$ sudo apt-add-repository ppa:sift/stable
$ sudo apt-get update && sudo apt-get upgrade -y

Error:

W: The repository 'https://apt.dockerproject.org/repo ubuntu-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/mantaray/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/dists/xenial/main/dists/xenial/main/binary-amd64/Packages 404 Not Found [IP: ]
E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-i386/Packages server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Failed to fetch http://ppa.launchpad.net/mantaray/stable/ubuntu/dists/xenial/main/binary-amd64/Packages 404 Not Found [IP: ]
E: Some index files failed to download. They have been ignored, or old ones used instead.

$ sudo apt-get install mantaray

Error:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mantaray

Source from PPA:
$ sudo apt-add-repository ppa:mantaray/stable
$ apt-get source mantaray

Error:

$ apt-get source mantaray
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
$

GitHub:
$ git clone https://github.com/mantarayforensics/mantaray.git
$ cd mantaray

$ git clone https://github.com/mantarayforensics/mantaray.git
fatal: destination path 'mantaray' already exists and is not an empty directory.
$ cd mantaray
bash: cd: mantaray: Not a directory
$ sudo mantaray
sudo: mantaray: command not found

Thank you

**Comment by ekristen** [comment]
Mantaray has not been updated to support Ubuntu 16.04 xenial, therefore it will not install.

I believe Mantaray is no longer being actively maintained
