### ISSUE TITLE
add INDXParser.py

### ISSUE THREAD

**Issue by philhagen** [sans-dfir/sift#171]
Add https://github.com/williballenthin/INDXParse to reflect netwars questions

**Comment by ekristen** [comment]
This is already installed https://github.com/sans-dfir/sift-saltstack/blob/master/sift/python-packages/indxparse.sls

Are you not seeing the scripts?

**Comment by philhagen** [comment]
we have various docs that state it's supposed to run as "INDXParse.py", and there is no file with "indx" installed on the NetWars ova.

**Comment by ekristen** [comment]
Ah netwars.

**Comment by ekristen** [comment]
This was always included, but there was a bug that caused it to not always get installed properly. That was just fixed. I'll push a new release tonight.
