### ISSUE TITLE
add plutil.pl

### ISSUE THREAD

**Issue by philhagen** [sans-dfir/sift#172]
plutil.pl (plist parser) not present.  should not be any harm in having this for mainline sift as well as netwars.

**Comment by philhagen** [comment]
MAYBE this? https://github.com/HearthSim/extract-scripts/blob/master/plutil.pl
check with Sarah E. for confirmation though

**Comment by mac4n6** [comment]
plutil.pl works ok-ish - but also install libimobiledevice https://github.com/libimobiledevice/libplist - it has plistutil which works well and a variety of other useful tools.
