### ISSUE TITLE
Rename or create alias for regripper 'ntuser' list

### ISSUE THREAD

**Issue by mpilking** [sans-dfir/sift#173]
The Netwars SIFT OVA has an issue with rip.pl.  Our class slides, cheat sheets, and Netwars hints say to use "ntuser" as the list of plugins for parsing NTUSER.DAT, but it's named "ntuser-all" in the new SIFT.  Can you either rename it back to ntuser, or create a sym link?

![image](https://user-images.githubusercontent.com/5453480/28755444-c395e9ac-7520-11e7-8ee4-f512315e531e.png)

![image](https://user-images.githubusercontent.com/5453480/28755446-dd6d5374-7520-11e7-8732-98bd5cee3683.png)

**Comment by ekristen** [comment]
The new SIFT distro, there is no `ntuser-all` it is just `ntuser`, not sure how the  current netwars version was built, if we start building it off the base `sift-community` then this won't be a problem anymore.

**Comment by ekristen** [comment]
There is no `ntuser-all` anymore. Hasn't been since at least June 2017.
