### ISSUE TITLE
[CLI]Issue when installing with proxy

### ISSUE THREAD

**Issue by sebnetdev** [sans-dfir/sift#174]
Hi,

I got an issue when I tried to install SIFT using a proxy:

 - Ubuntu 16:04
 - Latest SIFT version 1.5.1

I have exported https_proxy, http_proxy, HTTP_PROXY and HTTPS_PROXY
with "http://172.16.0.1:3128"

The script ended with this message:
~~~~
>> Completed with Failures -- Success: 454, Failure: 34
~~~~~
Here are the first three examples of failure:
~~~~~~~~
  archive_|-sift-scripts-virustotal-search-archive_|-/usr/local/src/virustotal-search-v0.1.4_|-extracted:
    __id__: sift-scripts-virustotal-search-archive
    __run_num__: 408
    __sls__: sift.scripts.virustotal-tools
    changes: {}
    comment: 'Failed to cache https://didierstevens.com/files/software/virustotal-search_V0_1_4.zip:
      Error: [Errno -3] Temporary failure in name resolution reading https://didierstevens.com/files/software/virustotal-search_V0_1_4.zip'
    duration: 2.393
    name: /var/cache/salt/minion/files/base/_files_software_virustotal-search_V0_1_4.zip
    pchanges: {}
    result: false
    start_time: '22:55:46.374719'
  archive_|-sift-scripts-virustotal-submit-archive_|-/usr/local/src/virustotal-submit-v0.0.3_|-extracted:
    __id__: sift-scripts-virustotal-submit-archive
    __run_num__: 410
    __sls__: sift.scripts.virustotal-tools
    changes: {}
    comment: 'Failed to cache https://didierstevens.com/files/software/virustotal-submit_V0_0_3.zip:
      Error: [Errno -3] Temporary failure in name resolution reading https://didierstevens.com/files/software/virustotal-submit_V0_0_3.zip'
    duration: 2.032
    name: /var/cache/salt/minion/files/base/_files_software_virustotal-submit_V0_0_3.zip
    pchanges: {}
    result: false
    start_time: '22:55:46.380979'
  archive_|-sift-tool-densityscout-archive_|-/usr/local/src/densityscout/densityscout_build_45_linux_|-extracted:
    __id__: sift-tool-densityscout-archive
    __run_num__: 266
    __sls__: sift.tools.densityscout
    changes: {}
    comment: 'Failed to cache http://cert.at/static/downloads/software/densityscout/densityscout_build_45_linux.zip:
      Error: [Errno -3] Temporary failure in name resolution reading http://cert.at/static/downloads/software/densityscout/densityscout_build_45_linux.zip'
    duration: 2.987
    name: /var/cache/salt/minion/files/base/_static_downloads_software_densityscout_densityscout_build_45_linux.zip
    pchanges: {}
    result: false
~~~~~~~~~

For me these 3 files have not been downloaded because the command to download zip file did not use  the proxy environment variables described above.

Is there a way to configure a proxy in sift installation script?

Thanks in advance.

Regards,

**Comment by ekristen** [comment]
It looks like an issue with DNS not the proxy. `Failure in name resolution`

**Comment by sebnetdev** [comment]
Hello,

Thanks for your answer, but it does not come from the DNS, this DNS resolution should be done by the proxy not by the SIFT host itself. The DNS resolution failure is just a side effect because the script does not use the proxy.

I had another case with another machine, I ran a tcpdump and I saw the direct connection instead of the connection to the proxy.

As I understood, it could be coming from nodejs that does not use environment variable for proxy settings.
 
Regards,

**Comment by ekristen** [comment]
Everything is downloaded in the same way. The env vars you set for the proxy are correct. 

If it was a problem with the proxy settings you'd have far more errors.

The fact that those three failed I can't explain other than the log clearly states that name resolution failed, which in my experience means DNS failed to resolve.

**Comment by sebnetdev** [comment]
Erik,

I have configured my VM with a DNS resolver, and as you can see the script was not able to download several zip file or deb package, there was a connection timeout.

As I said it does not come from DNS, but from a script that does not get env variables or does not work with a proxy.

Here is the log:
[log.zip](https://github.com/sans-dfir/sift/files/1198259/log.zip)

Here is the information of connection
[process_connection.zip](https://github.com/sans-dfir/sift/files/1198314/process_connection.zip)

As you can see the process that made direct connection is this one (/usr/bin/python /usr/bin/salt-call ...):

~~~~
root      5375  0.0  0.0  55040  4016 pts/0    S+   18:55   0:00  |           \_ sudo -E sift install
root      5388  0.7  0.4 961520 75284 pts/0    Sl+  18:55   0:00  |               \_ sift install
root      5427  5.4  0.8 365976 140580 pts/0   S+   18:55   0:06  |                   \_ /usr/bin/python /usr/bin/salt-call -l debug --local --file-root /var/cache/sift/cli/v2017.29.0/sift-saltstack-2017.29.0 --state-output=terse --out=yaml state.apply sift.vm pillar={sift_user: "sift"}
~~~~~

Hope this helps for debugging.

Regards,

**Comment by iafreerider** [comment]
I have a similar issue with running the binary behind a proxy, but get a timeout directly after issuing the `sift --install` command and no packages get installed. npm does not utilize the linux proxy environment variable, even though it is set on the host, but requires the proxy to be configured through `npm config set proxy` command which I have successfully tested in a test lab with a host that had npm installed on it. Since the sift binary contains the npm package, is there any way for sift to import the http(s)_proxy variables and use the packaged npm to configure the proxy variables?

Error in sift commandline:

# sift install --mode=packages-only
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: notinstalled


connect ETIMEDOUT 192.30.253.117:443
Error: connect ETIMEDOUT 192.30.253.117:443
    at module.exports.__dirname.sendError (/snapshot/sift-cli/node_modules/github/lib/index.js:853:19)
    at /snapshot/sift-cli/node_modules/github/lib/index.js:864:29
    at callCallback (/snapshot/sift-cli/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/snapshot/sift-cli/node_modules/github/lib/index.js:806:17)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

sift process showing a direct connection to the github servers instead of a proxy (the destination should have been a RFC1918 address):

# netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      1 172.17.0.4:49454        192.30.253.117:443      SYN_SENT    1625/sift

Is there further information that would be required to get a solution for running sift behind a proxy environment?

Thanks for all the hard work to port the bootstrap to saltstack!

**Comment by ekristen** [comment]
It already takes proxy settings into account, what env vars are you setting?

**Comment by iafreerider** [comment]
$http_proxy and $https_proxy. Somehow I must have missed that in the source files since I did not see any code that configures the proxy; what vars is the code looking for?

**Comment by ekristen** [comment]
https://github.com/sans-dfir/sift/issues/161
