### ISSUE TITLE
Error on "sudo sift install" on ubuntu

### ISSUE THREAD

**Issue by DFIR-Zach** [sans-dfir/sift#175]
Please see the below error I get after following step by step the directions on https://github.com/sans-dfir/sift-cli#instructions.  After the last step - Run chmod 755 /usr/local/bin/sift, I run the command sudo sift install and get the following error message. FYI I am trying to install this on a fresh Ubuntu 14.04 VM.

![image](https://user-images.githubusercontent.com/15873490/28938817-3251fd24-785d-11e7-99f8-0c1c3d75cc75.png)

**Comment by ekristen** [comment]
Looks like your apt database was broken prior to attempting to install SIFT. Essentially any apt-get install will fail due to something that happened prior to running the sift installer.

You'll need to fix your apt database before you can install.

**Comment by DFIR-Zach** [comment]
I have done this and apt-get seems to be working, however I am still getting the same error.  Any tips? What version of Ubuntu works best for this?

**Comment by ekristen** [comment]
Ubuntu 16.04 is the only supported version.
