### ISSUE TITLE
Map to /cases/ folder from host windows system

### ISSUE THREAD

**Issue by DFIR-Zach** [sans-dfir/sift#177]
Can you explain how to configure the SIFT so that on my local machine (Windows 10) I can go to Windows File Explorer and type "\\siftworkstation" in the address bar in order to access files from the SIFT workstation's \cases and \mount folders?  The VM I got from SANS 508 had this capability already configured, however with the newer version of SIFT, I am unsure how to configure this option. Thanks!

**Comment by ekristen** [comment]
We had a bug in the Samba share setup, the latest version of SIFT fixes this. `sudo sift upgrade` will do the trick from the command line.

**Comment by ekristen** [comment]
All samba issues have been fixed on the latest version.
