### ISSUE TITLE
[CLI] Failures on install

### ISSUE THREAD

**Issue by mat-sec** [sans-dfir/sift#179]
I've run through the CLI install on a fresh 16.04 VM and got Success: 485, Failure: 6.
I ran through the upgrade afterwards and still had 6 failures, and then tried doing a pre-release upgrade, and again...6 failures. 

Not sure what's hanging up.  I've attached the saltstack.log and results.yml.  Any help would be greatly appreciated.

[results.yml.txt](https://github.com/sans-dfir/sift/files/1286118/results.yml.txt)
[saltstack.log.txt](https://github.com/sans-dfir/sift/files/1286120/saltstack.log.txt)

**Comment by ekristen** [comment]
It looks like you are getting `CERTIFICATE_VERIFY_FAILED` when trying to download a few files. Which is causing the failures.

Are you using a proxy server or anything else custom about this system?

**Comment by mat-sec** [comment]
There's nothing unusual on the system but it might be an issue due to the fact that I'm doing the build on the wireless at work.  I'll try it again from home tonight and see if that resolves it.

**Comment by mat-sec** [comment]
You were right.  The issue was a proxy one, but it was due to the way VirtualBox passes the connection to the VM.  I got it sorted thank you.

**Comment by ekristen** [comment]
No problem. Have a good one.
