### ISSUE TITLE
Errors during Install - Completed with Failures

### ISSUE THREAD

**Issue by gedeon8084** [sans-dfir/sift#182]
Hi! My install provides the following error:
**Completed with Failures -- Success: 416, Failure: 75**
This happens regardless of the version, I've tried 31.4, 36.0 an pre-release 36.1-rc2
I'm attaching the log.
[saltstack.txt](https://github.com/sans-dfir/sift/files/1322770/saltstack.txt)

**Comment by ekristen** [comment]
@gedeon8084 unfortunately you've hit problems I've never seen before. The log indicates 

```
Problem encountered installing package(s). Additional info follows:\n\nerrors:\n
      \   - Running scope as unit run-r9ac4691b82c94b97823d51d4c813acfa.scope.\n      E:
      dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct
      the problem.
```

For multiple packages. I'm unsure what would cause the but if you could try running the command it suggests and follow any problems then try re-running the installation, lets see if that fixes it.

**Comment by gedeon8084** [comment]
Thank you Erik! I had a package "half-installed" that was breaking things. After reinstalling that package everything worked. Thanks again

**Comment by Fetchered** [comment]
Regarding this, could you tell us how to find these errors in the saltstack log? IE: What constitutes an accountable error (75 errors)? I've scoured my logs when these errors come up (14 errors) and I usually find a lot more errors than the actual failure count.

**Comment by ekristen** [comment]
Closing this for now ... if you want to follow up just re-open with more comments.
