### ISSUE TITLE
having issues using any of the software in suite

### ISSUE THREAD

**Issue by dheckart** [sans-dfir/sift#184]
i have been trying to mount an image file and it is not working i also tried to open mantaray and it says it cannot find any of it please help

**Comment by ekristen** [comment]
Mantaray is no longer supported as it’s not being maintained and therefore we are not installing it.

**Comment by dheckart** [comment]
okay when this installs does it install the software with it and if it does is it only command line or is there a was to use a gui interface for it

**Comment by ekristen** [comment]
SIFT is a collection of tools and scripts, there is no one command or a GUI. 

Some of the tools are documented here http://sift.readthedocs.io/en/latest/

More information is available here https://digital-forensics.sans.org/community/downloads

**Comment by dheckart** [comment]
i have looked at these and i guess i am just dumb as i cannot figure out on how to mount the image i created and also on how to  run the software for analysis thank you for your help though

**Comment by ekristen** [comment]
@dheckart do you have any training on this subject? What exactly are you attempting to do?

**Comment by dheckart** [comment]
i do have training but not in linux i have created an image using ftk imager e01 and all i am trying to do is mount the image so that i can run software like autospy to anaylsis the drive to look for files that are modified on certain dates and see deleted files and what they contents say. but like i said i am not use to linux so i have not figured out how to use them yet

**Comment by dheckart** [comment]
when i try running the command mount_ewf.py image.E01 mountpoint it says mount_ewf.py:command not found also when i try running the command /mnt/ewf/<RAWFILE> /mnt/mount_location it again says /mnt/ewf/: command not found

**Comment by dheckart** [comment]
also i am putting sudo infront of them
