### ISSUE TITLE
VERIFY SIFT-CLI

### ISSUE THREAD

**Issue by PAULABAILEN** [sans-dfir/sift#185]
Hello,

I'm having difficulties verifying the following. Please help how to resolve this issue.

ubuntu@ubuntu:~$ gpg --keyserver pgp.mit.edu --recv-keys 22598A94
gpg: keyring `/home/ubuntu/.gnupg/secring.gpg' created
gpg: keyring `/home/ubuntu/.gnupg/pubring.gpg' created
gpg: requesting key 22598A94 from hkp server pgp.mit.edu
gpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created
gpg: key 22598A94: public key "SANS Investigative Forensic Toolkit <sift@computer-forensics.sans.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
ubuntu@ubuntu:~$ gpg --verify sift-cli-linux.sha256.asc
gpg: can't open `sift-cli-linux.sha256.asc'
gpg: verify signatures failed: file open error

**Comment by ekristen** [comment]
Sounds like you didn’t download all the files. Make sure they are in the directory you are running the commands from.

**Comment by MrChieL** [comment]
hello, i am having difficulty verifying the follwoing.  Please help.


cosign verify-blob --key sift-cli.pub --signature sift-cli-linux.sig sift-cli-linux
Error: verifying blob [sift-cli-linux]: signature not found in transparency log
main.go:74: error during command execution: verifying blob [sift-cli-linux]: signature not found in transparency log

**Comment by ekristen** [comment]
I'll take a look, that's if you just want to verify the installer. 

You can simply download cast and install sift that way now. It handles everything.
