### ISSUE TITLE
[CLI] Installation 4.Validate the signature - verify signatures failed: file open  error

### ISSUE THREAD

**Issue by eljami** [sans-dfir/sift#187]
Installation steps 1-3 seem ok.
Installation step 4  I get verify signatures failed: file open  error

Please advice how I can fix issue.

![file open error](https://user-images.githubusercontent.com/32746611/31510894-df95b0ee-afc0-11e7-80cc-fc7040b558bc.png)

**Comment by ekristen** [comment]
Doesn’t appear you are in the directly that contains the file.

**Comment by eljami** [comment]
Thanks that was it!
