### ISSUE TITLE
sift: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by richdorfman** [sans-dfir/sift#188]
Running virtualized 32-bit Ubuntu 16.04.3 LTS. Successfully validated SHA256 signature,  move file to mv sift-cli-linux /usr/local/bin/sift and ran chmod 755 /usr/local/bin/sift.

When type sift --help, got error message: "sift: cannot execute binary file: Exec format error"

Is sift-cli-linux compiled for 64-bit? If so, why can I successfully run sift-cli-linux.sha256.asc on it? Is there a 32-bit sift-cli-linux binary? How do I compile for 32-bit? It's just javascript in executable wrapper.

Thanks.

**Comment by ekristen** [comment]
I’m curious why you are running 32 bit?

SIFT is only guaranteed to install in a 64 bit environment and the cli is only compiled in 64 bit. 

Regards,
Erik

**Comment by richdorfman** [comment]
Thank you for answer. Even though I am running 64-bit Windows 7, AMD processor with virtualization supported and enabled in BIOS, install of any 64-bit Linux distro in Oracle VM fails. The VM doesn't seem to recognize BIOS virtualization setting for 64-bit (AMD-V) and only successfully installs 32-bit distros in VM.

Best,

Rich

**Comment by rhondene** [comment]
I'm trying to run fastq-dump from sratoolkit but I get the output: "bash: ./cannot execute binary file: Exec format error". I'm using 64bit windows 7 professional
