### ISSUE TITLE
[CLI] Installation delay?: powershell_6.0.0-alpha.13-1ubuntu1.16.04.1_amd64.deb

### ISSUE THREAD

**Issue by eljami** [sans-dfir/sift#189]
![screen shot 2017-10-13 at 11 28 47 am](https://user-images.githubusercontent.com/32746611/31527812-b5caccfa-b00a-11e7-9c55-cad0666a6384.png)

1) I ran sift install and after a while Ubuntu froze. 
2) I restarted Ubuntu.
3) I resumed the installation by typing sift install again
4) powershell_6.0.0-alpha.13-1ubuntu1.16.04.1_amd64.deb installation has been in "running" mode for sometime but installation does not show "completed"

Q1: How long is an appropriate time to wait to see installation progress?
Q2: What should I do to continue with installation process?

Thanks!

**Comment by ekristen** [comment]
It has to download files depending on your connection this could take a while.

**Comment by eljami** [comment]
![screen shot 2017-10-13 at 1 01 02 pm](https://user-images.githubusercontent.com/32746611/31529817-a8444ffa-b016-11e7-94c3-5d3e44558124.png)

Thanks.  ok. I waited and it shows "Completed with Failures -- Success: 483, Failure: 8

However, I only see the pdf's installed but I do not see SIFT workstation, MantaRay, or any other applications. Also when I click on "cases" I get a "The link "cases" is broken" error.

Q: How can I access the SIFT workstation and other applications?

**Comment by eljami** [comment]
![screen shot 2017-10-13 at 4 29 35 pm](https://user-images.githubusercontent.com/32746611/31534887-c98a285c-b033-11e7-9ac8-6bfe3c658e32.png)

Never mind. I'm now using sift's latest version 1.5.1-beta.0, Build: master-154cb2f

I'll install other applications separately!
