### ISSUE TITLE
Hashes do not match after "sudo sift install"

### ISSUE THREAD

**Issue by elkarcher** [sans-dfir/sift#191]
I was able to successfully follow the how-to guides for installing Ubuntu 16.04.  I was then able to fumble through all of the other steps (sorry not really very Linux savvy yet) and made it to the "sudo sift install" step.  The feedback said that is successfully downloaded the "sift-saltstack-v2017.41.1.tar.gz.*" files but when it attempted to validate the files it had downloaded, it returned an error saying that the hashes do not match and of course also that the "sift-version: notinstalled".  I was fairly meticulous with this installation following your instructions.  Any thoughts on what I am missing here would be appreciated.  Thanks in advance.

**Comment by ekristen** [comment]
Can you provide the output of the command? Does the same result happen every time? Are you behind a proxy server?

**Comment by elkarcher** [comment]
I have attached images of the output of the command.  It is repeatable.  I am not behind a proxy server for the internet connection.  Any help you can offer is greatly appreciated.
![image_1](https://user-images.githubusercontent.com/32847107/31769597-52e8a12e-b4a2-11e7-88d2-d01be3a7e23c.jpg)

**Comment by elkarcher** [comment]
![image_2](https://user-images.githubusercontent.com/32847107/31769622-62e48b9c-b4a2-11e7-8316-16777fbfbe08.jpg)

**Comment by ekristen** [comment]
The only thing I can suggest at this time is for you to ensure that `sift-saltstack-v2017.41.1.tar.gz` is not in the tmp directory and try again.

I've validated all the files and hashes, my only guess is that there is something happening with your internet connection either via proxy or firewall or ISP that might be changing the contents of the file.

**Comment by elkarcher** [comment]
OK I will keep trying, thanks for helping out.

**Comment by cesar-rickinho** [comment]
@elkarcher were you able to install?

I'm having the same problem with a fresh install of Ubuntu 16.04.3.

**Comment by cesar-rickinho** [comment]
If it helps someone later, I managed to install an older version using the command.

`sudo sift install --version=v2017.47.2`

**Comment by ekristen** [comment]
I just checked the hashes of the latest and they match.

**Comment by aoloriz** [comment]
I am getting the same error:
`Error: Hashes for sift-saltstack-v2023.02.06.tar.gz do not match.`
Running `sudo apt-get update` did not resolve this for me. I just completed an install with the sift cli a week ago and did not have this issue. Is it possible that the install script is referencing a different version of saltstack?
Thanks!
