### ISSUE TITLE
[CLI] SIFT "upgrade" Not Working

### ISSUE THREAD

**Issue by 13Cubed** [sans-dfir/sift#192]
I've downloaded the newest version of the SIFT CLI (1.5.1-beta.0-master.154cb2f). If I run "sift list-upgrades" I see this:

> List of available releases
  - v2017.41.1
  - v2017.36.0
  - v2017.31.4
  - v2017.31.3
  - v2017.31.2
  - v2017.29.0

If I run "**sift upgrade**", I see this:

> **sift-cli@1.5.1-beta.0-master.154cb2f**
> **sift-version: v2017.27.2**

**> downloading v2017.41.1**
>> downloading sift-saltstack-v2017.41.1.tar.gz.asc
>> downloading sift-saltstack-v2017.41.1.tar.gz.sha256
>> downloading sift-saltstack-v2017.41.1.tar.gz.sha256.asc
>> downloading sift-saltstack-v2017.41.1.tar.gz
> validating file sift-saltstack-v2017.41.1.tar.gz
> validating signature for sift-saltstack-v2017.41.1.tar.gz.sha256
> extracting update sift-saltstack-v2017.41.1.tar.gz
> performing update v2017.41.1
>> Log file: /var/cache/sift/cli/v2017.41.1/saltstack.log

...
[OUTPUT TRUNCATED]
...

**>> Completed with Failures -- Success: 490, Failure: 3**

I have reviewed the "saltstack.log" in /var/cache/sift/cli/v2017.41.1, but I'm not sure what I'm looking for. I saw nothing obviously wrong.

If I re-run "sift list-upgrades", even after it clearly states I'm still on v2017.27.2.

I seem to be stuck in a loop. Help?

**Comment by ekristen** [comment]
There’s a saltstack log in that directory, can you upload it please or look for result: false to find which ones have failed.

**Comment by 13Cubed** [comment]
[root@siftworkstation v2017.41.1]# **grep -i -A5 -B5 "result: false" saltstack.log** 
    comment: Directory exists where the symlink /usr/share/regripper/plugins should
      be
    duration: 5.031
    name: /usr/share/regripper/plugins
    pchanges: {}
    result: false
    start_time: '13:13:00.931822'
  file_|-sift-scripts-screen-scale_|-/usr/local/bin/set-display-scale_|-managed:
    __id__: sift-scripts-screen-scale
    __run_num__: 399
    __sls__: sift.scripts.screen-scale
--
  file_|-sift-version-file_|-/etc/sift-version_|-managed:
    __run_num__: 492
    __sls__: sift.vm
    changes: {}
    comment: 'One or more requisite failed: sift.scripts.sift-scripts'
    result: false
  file_|-symlinks-cases_|-/home/davisrg/Desktop/cases_|-symlink:
    __id__: symlinks-cases
    __run_num__: 433
    __sls__: sift.config.user.symlinks
    changes: {}
--
  test_|-sift-scripts_|-sift-scripts_|-nop:
    __run_num__: 419
    __sls__: sift.scripts
    changes: {}
    comment: 'One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-plugins-symlink'
    result: false
  test_|-sift-tools_|-sift-tools_|-nop:
    __id__: sift-tools
    __run_num__: 275
    __sls__: sift.tools
    changes: {}

**Comment by ekristen** [comment]
Looks like this is due to a patch we did on regripper. I'll release a fix later this evening. Once I do you'll be able to run `sift upgrade` again.

For now the good news is that everything else installed just fine, but since there was an error it will not mark it as successful. We do not rollback when errors occur.

**Comment by 13Cubed** [comment]
Great - thanks!

**Comment by ekristen** [comment]
@13Cubed I got a little busy last night, wasn't able to test my fix yet. For now to get this working you can go and just delete `/usr/share/regripper/plugins` and run the upgrade and it should put everything where it needs to.

**Comment by 13Cubed** [comment]
@ekristen Thanks - that worked just fine!

**Comment by 13Cubed** [comment]
Looks like there is another issue when attempting to upgrade to v48.0. See "result: false" results below:

[user@siftworkstation v2017.48.0]$ grep -i "result: false" saltstack.log -A5 -B5 | more
      stdout: ''
    comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt"
      run
    duration: 241.598
    name: dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt
    result: false
    start_time: '19:56:25.267629'
  cmd_|-sift-config-theme-gtk_|-gsettings set org.gnome.desktop.interface gtk-theme Arc_|-run:
    __id__: sift-config-theme-gtk
    __run_num__: 459
    __sls__: sift.config.user.theme
--
    duration: 116.207
    name: gsettings set com.canonical.Unity.Launcher favorites "['application://gnome-terminal.desktop',
      'application://firefox.desktop', 'application://org.gnome.Nautilus.desktop',
      'application://unity-control-center.desktop', 'unity://running-apps', 'unity://expo-icon',
      'unity://devices']"
    result: false
    start_time: '19:56:45.181553'
  cmd_|-sift-config-unity-icon-size_|-dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32_|-run:
    __id__: sift-config-unity-icon-size
    __run_num__: 470
    __sls__: sift.config.user.unity
--
      stdout: ''
    comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size
      32" run
    duration: 122.23
    name: dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32
    result: false
    start_time: '19:56:45.297951'
  cmd_|-sift-config-unity-launcher-user_|-gsettings set com.canonical.Unity.Launcher launcher-position Bottom_|-run:
    __id__: sift-config-unity-launcher-user
    __run_num__: 467
    __sls__: sift.config.user.unity
--
      stdout: ''
    comment: Command "gsettings set com.canonical.Unity.Launcher launcher-position
      Bottom" run
    duration: 125.964
    name: gsettings set com.canonical.Unity.Launcher launcher-position Bottom
    result: false
    start_time: '19:56:44.933384'
  ? cmd_|-sift-config-unity-minimize-window_|-dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window
    true_|-run
  : __id__: sift-config-unity-minimize-window
    __run_num__: 471
--
    comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window
      true" run
    duration: 125.414
    name: dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window
      true
    result: false
    start_time: '19:56:45.420915'
  ? cmd_|-sift-package-perl-cpan-configure_|-perl -MCPAN -e 'my $c = "CPAN::HandleConfig";
    $c->load(doit => 1, autoconfig => 1); $c->edit(prerequisites_policy => "follow");
    $c->edit(build_requires_install_policy => "yes"); $c->commit'_|-wait
  : __id__: sift-package-perl-cpan-configure
--
  file_|-sift-version-file_|-/etc/sift-version_|-managed:
    __run_num__: 528
    __sls__: sift.vm
    changes: {}
    comment: 'One or more requisite failed: sift.config.sift-config, sift.packages.sift-packages'
    result: false
  file_|-symlinks-cases_|-/home/davisrg/Desktop/cases_|-symlink:
    __id__: symlinks-cases
    __run_num__: 454
    __sls__: sift.config.user.symlinks
    changes: {}
--
      \       E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily
      unavailable)\n        E: Unable to lock the administration directory (/var/lib/dpkg/),
      is another process using it?\n    stdout:"
    duration: 16409.033
    name: sift-wine-apt-update
    result: false
    start_time: '19:53:13.251681'
  pkg_|-sift-wine_|-wine_|-installed:
    __run_num__: 242
    __sls__: sift.packages.wine
    changes: {}
    comment: 'One or more requisite failed: sift.packages.wine.sift-wine-apt-update'
    result: false
  pkg_|-sleuthkit_|-sleuthkit_|-installed:
    __id__: sleuthkit
    __run_num__: 213
    __sls__: sift.packages.sleuthkit
    changes: {}
--
    __sls__: sift.config.user
    changes: {}
    comment: 'One or more requisite failed: sift.config.user.unity.sift-config-unity-favorites,
      sift.config.user.unity.sift-config-unity-minimize-window, sift.config.user.terminal.sift-config-terminal-profiles-install,
      sift.config.user.unity.sift-config-unity-launcher-user, sift.config.user.unity.sift-config-unity-icon-size'
    result: false
  test_|-sift-config_|-sift-config_|-nop:
    __run_num__: 527
    __sls__: sift.config
    changes: {}
    comment: 'One or more requisite failed: sift.config.user.sift-config-user'
    result: false
  test_|-sift-packages_|-sift-packages_|-nop:
    __run_num__: 249
    __sls__: sift.packages
    changes: {}
    comment: 'One or more requisite failed: sift.packages.wine.sift-wine, sift.packages.wine.sift-wine-apt-update'
    result: false
  test_|-sift-python-packages_|-sift-python-packages_|-nop:
    __id__: sift-python-packages
    __run_num__: 273
    __sls__: sift.python-packages
    changes: {}

**Comment by zpravaiz** [comment]
I am facing same similar issue. Updating my saltstack log 

I would appreciate your help.

Thanks

[saltstack.log](https://github.com/sans-dfir/sift/files/1528184/saltstack.log)

**Comment by ekristen** [comment]
This issue is stale and new releases have been made, please open a new issue if you are still having this problem. Please include the log and results file.
