### ISSUE TITLE
I cannot get past the Validate the signature?

### ISSUE THREAD

**Issue by boho2112** [sans-dfir/sift#193]
I've downloaded the latest CLI files and the import gpg key goes fine but when I verify the signature I get "gpg: can't open `sift-cli-linux.sha256.asc'
gpg: verify signatures failed: file open error.

Is this because I don't have the sift installed yet and this is an upgrade?

**Comment by ekristen** [comment]
Sounds like you aren't running the command from the same directory to which you are downloading the file.

**Comment by boho2112** [comment]
That was it for the signature(doh!) but now I'm running into how do I install the next piece.  Instructions maybe clear for Linux guru's but not for newbies like me....Is there step by step instructions on how to install my SIFT environment on top of my Ubuntu 16.x virtual box vm?
So far I've done this:
     Go to the Latest Releases
      Download all the release files
      sift-cli-linux
      sift-cli-linux.sha256.asc
      Import the PGP Key - gpg --keyserver pgp.mit.edu --recv-keys 22598A94
     Validate the signature gpg --verify sift-cli-linux.sha256.asc
     Validate SHA256 signature shasum -a 256 -c sift-cli-linux.sha256.asc OR sha256sum -c sift-cli-
     linux.sha256.asc
    Note: You'll see an error about improperly formatted lines, it can be ignored so long as you see sift-
    cli-linux: OK before it
    Move the file to mv sift-cli-linux /usr/local/bin/sift
    Run chmod 755 /usr/local/bin/sift
thanks alot Dummy Dan!

**Comment by boho2112** [comment]
Well I tried to install sift and got this crazy output, Anyone seen this??
![image](https://user-images.githubusercontent.com/33035590/31959516-bfb64cba-b8a9-11e7-9fc4-b0d2b49cb8be.png)

**Comment by ekristen** [comment]
Are you on a 32 bit system? Only 64 bit is supported.

**Comment by boho2112** [comment]
My host system is 64-bit but I just looked and I installed a 32-bit Ubuntu…..back to the drawing board…..

Thanks Dan
Dan Beaulieu
Security Sys Admin | IT Information Security
DBeaulieu@icwgroup.com<mailto:DBeaulieu@icwgroup.com>
