### ISSUE TITLE
[CLI] SIFT Installation

### ISSUE THREAD

**Issue by CodeFoxy421** [sans-dfir/sift#194]
![screenshot from 2017-10-23 13-26-26](https://user-images.githubusercontent.com/33040595/31911905-0350f398-b7f7-11e7-934d-2a8965862636.png)

Hello! i am trying to install SIFT on my laptop and cannot seem to make it past the `mv sift-cli-linux /usr/local/bin/sift part` I included a screen shot of my terminal to show the error I'm receiving. 

I am pretty new to Linux and totally sure I'm messing something up. I followed your responses to a user with a similar issue but still to no luck. Thank you ahead of time. I really appreciate your assistance!!!!

**Comment by CodeFoxy421** [comment]
As a side note, I have the two release files located on my desktop

**Comment by ekristen** [comment]
`sudo mv`

**Comment by CodeFoxy421** [comment]
Thank you! I made it through step 7!!! Stupid question: where to now?

**Comment by CodeFoxy421** [comment]
![scrrenshot3](https://user-images.githubusercontent.com/33040595/31912742-bea14880-b7f9-11e7-9419-f933ba64c691.png)

I think I got it??

**Comment by CodeFoxy421** [comment]
One more dumb question: I downloaded SANS SIFT from their website, do i still nee d that zip or can I delete it? Sorry for taking your time and expertise, still new to a lot of this!!

**Comment by ekristen** [comment]
If you are building SIFT yourself, you do not need the file on the SANS website.
