### ISSUE TITLE
rfc.pl - permission denied

### ISSUE THREAD

**Issue by mark-hallman** [sans-dfir/sift#195]
The script rfc.pl has premissions troubles.  It can't be run as the "sansforensics" user nor as root.  

![image](https://user-images.githubusercontent.com/16808320/32135013-5d2c5abe-bbbd-11e7-9849-8bbbd0aa3974.png)

**Comment by ekristen** [comment]
Fixed by https://github.com/sans-dfir/sift-saltstack/commit/1b16d7924ad67852e2d4b7b715376e742c37d9c3
