### ISSUE TITLE
foremost.conf missing

### ISSUE THREAD

**Issue by mark-hallman** [sans-dfir/sift#196]
The file `/usr/local/etc/foremost.conf ` is missing.  This version of the file has additional signatures such as sigs for prefetch.

![image](https://user-images.githubusercontent.com/16808320/32135026-b23f65e6-bbbd-11e7-8db0-39b8c1832ef8.png)

**Comment by ekristen** [comment]
Fixed by https://github.com/sans-dfir/sift-saltstack/commit/1b16d7924ad67852e2d4b7b715376e742c37d9c3
