### ISSUE TITLE
/mnt not working when trying to map network share on Windows Host machine

### ISSUE THREAD

**Issue by NickleB** [sans-dfir/sift#198]
I was watching the working with SIFT demo by Rob Lee this week and he had showed how to get the VM IP address and add this to the Host Windows machine which will allow access the /cases folder and the /mnt folder, \\<IP of VM>, however when Rob tried to access the /mnt folder and entered his credentials if failed, I have tried to do the same on the new SaltSack Sift VM and this also fails. 

Have you a work around please or fix?

**Comment by ekristen** [comment]
I believe we've resolve all windows mount issues in the latest release.
