### ISSUE TITLE
Can Sift be installed on Mint 

### ISSUE THREAD

**Issue by TheCursed** [sans-dfir/sift#199]
Going through the install steps , everything seems to work but when I try to update SIFT I get the message "SIFT not installed, unable to update ". When I try to update mint Ive noticed some of the packages fail  and I receive this message  . Any help would be appreciated thanks
![image](https://user-images.githubusercontent.com/14284502/32870956-9033b60a-ca3b-11e7-9601-b4cef15f652c.png)

**Comment by ekristen** [comment]
Only 64bit installations of 16.04 xenial are supported.
