### ISSUE TITLE
[SALTSTACK] IP conflicts with Docker

### ISSUE THREAD

**Issue by jpbruckler** [sans-dfir/sift#200]
The docker instance that gets setup conflicts with the network we use internally for proxy settings. As a result, the installation doesn't complete.

Saltstack.log is full of:

```
 start_time: '09:59:37.847410'
  pkg_|-xmount_|-xmount_|-installed:
    __id__: xmount
    __run_num__: 243
    __sls__: sift.packages.xmount
--
      \ Could not connect to yourproxy:8080 (172.17.0.n). - connect (113: No route
      to host) [IP: 172.17.0.n 8080]\n      \n      E: Unable to fetch some archives,
      maybe run apt-get update or try with --fix-missing?"
    duration: 13826.185
    name: xmount
    result: false
```

**Comment by ekristen** [comment]
At this time the only fix would be for you to modify the docker daemons configuration.

https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/

**Comment by ekristen** [comment]
@jpbruckler this is not something that's going to be directly addressed at this time, there are too many what if's to sensibly make this something that is configurable. Docker used to (and I thought it still did) look for an IP space that wasn't in use and use it by default.
