### ISSUE TITLE
[CLI] Links to sift-cli-linux are invalid for release 1.5.1

### ISSUE THREAD

**Issue by Cruc1bl3** [sans-dfir/sift#201]
I'm following the installation instructions for installing SIFT onto a clean install of Ubuntu 16.04.03, When I try to download the sift-cli-linux file I get a 404 error from an AWS site. I've also tried transferring the "/usr/local/bin/sift" from the OVA version to the clean ubuntu version but this returns the error:

        connect ECONNREFUSED 0.0.0.0:443

(which looks like it does not find the download site).

Any ideas?

**Comment by ekristen** [comment]
Do you have something overriding DNS in your environment.
