### ISSUE TITLE
Cannot import OVA - sha1 digest hash does not match

### ISSUE THREAD

**Issue by charliepaks** [sans-dfir/sift#206]
![image](https://user-images.githubusercontent.com/25075485/33434089-77574e7c-d5de-11e7-975b-39a83f35d589.png)
  I get that error when importing the ova in both vmware and virtual box. Any help with this please?

**Comment by charliepaks** [comment]
Can anyone please help me with this as i'm still stuck trying to even install sift. Thank you very much in advance.

**Comment by charliepaks** [comment]
I finally got to fix this by eliminating the manifest file from the ova package. It successfully imported, but now on booting, it takes me to grub rescue mode and says "/boot/grub/i386-pc/normal.mod" not found
![image](https://user-images.githubusercontent.com/25075485/33567869-dcb3f858-d924-11e7-93a9-d88866e244b0.png)

**Comment by ekristen** [comment]
If you still are running into this problem please re-open this issue.

**Comment by bathindahelper** [comment]
I"m facing similar issue.

**Comment by bathindahelper** [comment]
![image](https://user-images.githubusercontent.com/49483022/64142791-2fa88680-ce2b-11e9-8ff6-ef37c1b2c02c.png)

**Comment by ekristen** [comment]
@bathindahelper this is the SIFT issue repo, not Kali linux.
