### ISSUE TITLE
[CLI] keyserver timeout when downloading PGP key

### ISSUE THREAD

**Issue by mgg1776** [sans-dfir/sift#210]
When downloading your PGP key as explained in the README, I got the following error:

```
$ gpg --keyserver pgp.mit.edu --recv-keys 22598A94
<...snip...>
gpg: requesting key 22598A94 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

I tried [this suggestion](https://unix.stackexchange.com/questions/75892/keyserver-timed-out-when-trying-to-add-a-gpg-public-key/99122), which worked.

```
$ gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94
gpg: requesting key 22598A94 from hkp server pgp.mit.edu
gpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created
gpg: key 22598A94: public key "SANS Investigative Forensic Toolkit <sift@computer-forensics.sans.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

I recommend you update the README to specify the full domain:port <code>hkp://pgp.mit.edu:80</code>

**Comment by knicholson0** [comment]
For me, as of today, the original README syntax is what is what worked for me, while the suggested syntax is not working. ; )
