### ISSUE TITLE
Ubuntu on Windows 10 install/update

### ISSUE THREAD

**Issue by andrzejsh** [sans-dfir/sift#211]
I have  information "Completed with Failures -- Success: 470, Failure: 59" after install SIFT on Ubuntu on Windows 10. When I make sudo apt-get update
W: Target Packages (multiverse/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (multiverse/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (multiverse/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Translations (multiverse/i18n/Translation-pl_PL) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Translations (multiverse/i18n/Translation-pl) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Translations (multiverse/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (universe/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Packages (universe/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Packages (universe/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Translations (universe/i18n/Translation-pl_PL) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Translations (universe/i18n/Translation-pl) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Translations (universe/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Packages (multiverse/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (multiverse/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (multiverse/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Translations (multiverse/i18n/Translation-pl_PL) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Translations (multiverse/i18n/Translation-pl) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Translations (multiverse/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:4
W: Target Packages (universe/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Packages (universe/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Packages (universe/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Translations (universe/i18n/Translation-pl_PL) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Translations (universe/i18n/Translation-pl) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6
W: Target Translations (universe/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:1 and /etc/apt/sources.list:6

and after sudo apt-get upgrade
1 packet no full install or remove.

Is it normal?

**Comment by ekristen** [comment]
Last I checked windows 10 Ubuntu subsystem was 14.04 which is not supported. However if it is now 16.04 let me know and we can debug further. 

Erik

**Comment by andrzejsh** [comment]
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**Comment by DrVikTroll** [comment]
Hi

Same issue here!

**Comment by ekristen** [comment]
Windows 10 is **NOT** officially supported. However SIFT does not roll back in the face of failure, therefore you can run the install command and any success will be a success. 

As of right now the only thing that I know of that cannot be installed on Windows is any of the GUI/Theming components.

You can use mode=packages-only, but I recently found a bug where this will never mark SIFT as installed even if 100% successful.
