### ISSUE TITLE
Not able to access internet

### ISSUE THREAD

**Issue by gdymondz** [sans-dfir/sift#214]
Installed the sift workstation, however, not able to access internet.  Was able to access internet with Unbuntu VM prior to install.

When it ifconfig command is entered, only get "docker" and "lo"

**Comment by ekristen** [comment]
We've seen this randomly, seems to be an issue with Ubuntu + the hypervisor, generally a restart brings the primary network device back.

**Comment by beleka** [comment]
I have the same problem and can't solve it. I can't get connected my workstation... Using last release of sift on VMware player 12.

**Comment by ekristen** [comment]
Does your vm settings have a network adapter?

**Comment by Fetchered** [comment]
I had this issue at first, I had to run ifconfig -a to get the name of the network adapter that was 'down', then sudo ifconfig <adapter> up, then sudo dhclient and it worked. Seems to always be called 'ens33'.

**Comment by EbolaWare** [comment]
Mine took several restarts, but after running <code> dhclient </code> via sudo, doing a full upgrade (<code> sudo apt upgrade </code>), and restarting one more time, the errors with Xorg-server and networking corrected themselves.

**Comment by ekristen** [comment]
Unfortunately this is a difficult problem to diagnose. We are unable to duplicate when we are testing and building the VM to start with.

**Comment by MrGentry** [comment]
I have been battling this challenge in my classroom. For some reason, SIFT workstation has bound my subnet's network address (172.17.0.1). I can't seem to change it. Its causing serious DNS collisions on my network. Its very confusing why its chosing to bind the docker0 interface to this IP address!

**Comment by z3ndrag0n** [comment]
Google “docker default subnet address” it’s not SIFT per se, it’s Docker and the first match to the above search will tell you how to change it.

Hope this helps.

Cheers,
Barry

**Comment by MrGentry** [comment]
Thanks Barry - I'm curious where I can read more about how this docker0 works and how this happened. Do you have any good resources for this issue specifically, where its binding itself to the network address?

**Comment by ekristen** [comment]
Docker is installed as a part of SIFT, by default it uses 172.17 for its bridge network via docker0. Unfortunately in your case your main network collides.

The fix is to change the default settings for docker in the vm to use a different network. 

I’m mobile right now but a quick google search on how to change the default network for docker should lead you to docs on how to do this.

**Comment by MrGentry** [comment]
Super intriguing...Thanks for the feedback and support! You guys are great!

**Comment by MrGentry** [comment]
So I reinstalled it, again for the umpteenth time, and it decided to take the 172.18.0.1/16 network.... go figure! So i'm just going to clone this VM and run with it!

**Comment by ekristen** [comment]
Docker if installed from scratch attempts to probe the network it's one to try and pick a network that doesn't conflict, unfortunately when I create the VM, 172.17 isn't taken so it uses that. If you purge docker and re-install it it should get a different non-conflicting subnet.

**Comment by ekristen** [comment]
I'm going to lock this discussion because the original issue doesn't pertain to docker per-say. If you have more issues please open a new issue. Thanks.
