### ISSUE TITLE
[Tool] Libpst version

### ISSUE THREAD

**Issue by ctmayhew** [sans-dfir/sift#215]
Could you package up SIFT with the latest version of libpst by default from [here](http://www.five-ten-sg.com/libpst/) rather than the one in the repository? 

For some reason the new version of libpst has not been packaged up and you need to compile and install it manually.

**Comment by ekristen** [comment]
@ctmayhew thanks for bringing this to out attention, we'll take a look at it.

**Comment by ctmayhew** [comment]
No problem. The one from the URL I linked to is the (I think official) forked version that supports 64 bit PST/OST files. 

When I compiled the new version of libpst I could read my 64-bit PST just fine. This is also the same issue in Autopsy when I tested it - shall I make a new issue there?

**Comment by ekristen** [comment]
@ctmayhew generally we try and find authors and sources for the deb packages that have already been built as it reduces the overhead (mainly for me) to track and update deps like these.
