### ISSUE TITLE
Issues when installing SIFT on ubuntu subsystem for Windows 10

### ISSUE THREAD

**Issue by DrVikTroll** [sans-dfir/sift#216]
Hi Team,

After following instructions as per Sift webpage suggested, I am having issues with installation:

Completed with Failures -- Success: 514, Failure: 15

- Windows 10 version 1709 (Build 16299)

- cat /etc/*release
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=16.04
  DISTRIB_CODENAME=xenial
  DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
  NAME="Ubuntu"
  VERSION="16.04.3 LTS (Xenial Xerus)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 16.04.3 LTS"
  VERSION_ID="16.04"
  HOME_URL="http://www.ubuntu.com/"
  SUPPORT_URL="http://help.ubuntu.com/"
  BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
  VERSION_CODENAME=xenial
  UBUNTU_CODENAME=xenial

[saltstack.log](https://github.com/sans-dfir/sift/files/1612132/saltstack.log)

Also I see this at the end of apt upgrade output:

The following packages have been kept back:
  python-dfvfs python-plaso
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@TAKI-HP:/var/cache/sift# apt list --upgradeable
Listing... Done
python-dfvfs/xenial,xenial 20171230-1ppa1~xenial all [upgradable from: 20160108-1ppa1~xenial]
python-plaso/xenial,xenial 20171231-1ppa1~xenial all [upgradable from: 1.4.0-1ppa3~xenial]

Sift version is:

root@TAKI-HP:/var/cache/sift# sift version
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: notinstalled

I have tried with non beta first with same results.

Please advise how to proceed.

Thanks

**Comment by ekristen** [comment]
Alright, looking at the log, I can basically state at this time that SIFT on Ubuntu subsystem for Windows is **not supported**.

- It's not a GUI, so those things fail to get setup properly
- It's missing some critical bus communication setup (so it can't set TZ information) 
- There doesn't seem to be a real init system or services system installed (seeing errors with it trying to setup/stop services like samba)

You can try 
```bash
sudo sift install --mode=packages-only
```

But there's no guarantee from me that'll work.

**Comment by DrVikTroll** [comment]
Thanks, **ekristen**!

One last question.
Since this version of ubuntu supports connecting to an external X server is it possible that you will integrate GUI in windows version in future releases?

X server example: https://sourceforge.net/projects/vcxsrv/
Further info: https://www.slothparadise.com/setup-bash-windows-10-developers-ultimate-setup/

Kind Regards,
DrVikTroll

**Comment by ekristen** [comment]
Anything is possible. However there are no current plans. Pull requests are always welcome.
