### ISSUE TITLE
No plaso or log2time in OVA release

### ISSUE THREAD

**Issue by ajp3979** [sans-dfir/sift#217]
On the website, https://digital-forensics.sans.org/community/downloads, it specifies that plaso and log2timeline are included. I downloaded the OVA and ran with VMWare Workstation and neither was installed. I also conducted a manually install with 16.04 and CLI. This also did not install plaso or log2timeline.

**Comment by ekristen** [comment]
I'll have to check the OVA to confirm but they both are installed and both are installed using the CLI tool. However with that said, it's possible there was a failure to install everything. I would need to see your installation log.

**Comment by ekristen** [comment]
Closed to due inactivity.
