### ISSUE TITLE
ESXI issues

### ISSUE THREAD

**Issue by D1sk0** [sans-dfir/sift#220]
Tried both .ova and also unpacking and adding the .vmdk's and ova to ESXI, getting a "required disk is not present" error followed by "Failed to deploy VM: postNFCData failed: Capacity of uploaded disk is larger than requested"

any thoughts?

**Comment by ekristen** [comment]
We’ve heard of some problems with ESXI.

We are creating a new ova with smaller disk sizes so help with this. 

Erik

**Comment by D1sk0** [comment]
Stupid question, is there a non-ova format that isnt the ubuntu/sift install? i got that working, but I got CLI only, cant get GUI. Super new, so I thought it was just startx on CLI. Just pushes me to a different less workable CLI.

**Comment by ekristen** [comment]
@D1sk0 you can always installed Ubuntu 16.04 Desktop and manually install SIFT. 

We just cut a beta version of a 100GB single filesystem OVA that we are testing for viability in the classroom that should have better success in the ESXi realm. As soon as it can be made available I will update this issue.

**Comment by ekristen** [comment]
We've officially started releasing the OVA's as a single 100GB drive. I'm not certain if this is live on the website yet, but I'm going to close this out.
