### ISSUE TITLE
Vol.py - Please install DPAPIck library

### ISSUE THREAD

**Issue by 13Cubed** [sans-dfir/sift#224]
Just an FYI if anyone else is having this issue when running vol.py. The solution is to "pip uninstall m2crypto" and instead install via "apt install python-m2crypto".

**Comment by th-sid1** [comment]
@13Cubed Thanks for sharing this ... but I can't find the  `python-m2crypto`. Appreciate any help

Error: `Package python-m2crypto is not available, but is referred to by another package.`

**Comment by digitalsleuth** [comment]
Hi @th-sid1 , are you experiencing an issue with volatility in the current SIFT environment? If so, please open a new Issue so we can better assist, and please provide additional detail about the error you're experiencing.
