### ISSUE TITLE
Error in Sift Update

### ISSUE THREAD

**Issue by joeloseiga** [sans-dfir/sift#225]
I am installing SIFT for the first time and ran the sift update command. 
It returns with an error: 

Kindly help.

sudo sift update
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: v2017.48.0

> downloading v2017.48.0
>> downloading sift-saltstack-v2017.48.0.tar.gz.asc
>> downloading sift-saltstack-v2017.48.0.tar.gz.sha256
>> downloading sift-saltstack-v2017.48.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2017.48.0.tar.gz
> validating file sift-saltstack-v2017.48.0.tar.gz
> validating signature for sift-saltstack-v2017.48.0.tar.gz.sha256
> extracting update sift-saltstack-v2017.48.0.tar.gz
> performing update v2017.48.0
>> Log file: /var/cache/sift/cli/v2017.48.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/sift-cli/sift-cli.js:488:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)

**Comment by ekristen** [comment]
Have you run `sudo sift install` yet?

**Comment by ekristen** [comment]
@joeloseiga it looks like you said you are doing it for the first time, you will need to run`sudo sift install` please let me know if you continue to run into issues.

**Comment by mr-brody** [comment]
A bit of an old thread but I was seeing a similar error while installing and was able to push past it. 
What led me to the answer was tailing the log file contained in the error output: /var/cache/sift/cli/v2017.48.0/saltstack.log
It turns out the openssl wasn't properly installed. I ran the below command and re-ran the install script:
sudo python -m easy_install --upgrade pyOpenSSL
sudo sift install

**Comment by UncleRaymondo** [comment]
> 
> 
> A bit of an old thread but I was seeing a similar error while installing and was able to push past it.
> What led me to the answer was tailing the log file contained in the error output: /var/cache/sift/cli/v2017.48.0/saltstack.log
> It turns out the openssl wasn't properly installed. I ran the below command and re-ran the install script:
> sudo python -m easy_install --upgrade pyOpenSSL
> sudo sift install

Yep - this fixed my issue right now as well; seems to be installing after fixing OpenSSL per the above.

**Comment by jonanathan** [comment]
I am having the same issue of the following error. I saw it when I initially installed sift. When I upgrade OpenSSL, and attempted to install again, it showed as already installed. Ran the upgrade command and see the same error message.

Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/sift-cli/sift-cli.js:488:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
