### ISSUE TITLE
[CLI] Installation Completed with Failures

### ISSUE THREAD

**Issue by hackdefendr** [sans-dfir/sift#226]
I started with vanilla Ubuntu Server 16.04.

The installation ends with:

>  Completed with Failures -- Success: 517, Failure: 12

How can I find out which 12 failed?  Is there a log of the installation beyond STDOUT?

**Comment by hackdefendr** [comment]
So apparently the Ubuntu desktop is required.  After installing that I now have this:

> Completed with Failures -- Success: 525, Failure: 4

I did find where things are logged, but I do not know what to search for...I am going to trying a few things. If someone can help before I get it right...please chime in.

Thanks,

**Comment by ekristen** [comment]
@hackdefendr basically looking for `result: false` in the install log. You can post it here or you can review it. 

The CLI uses saltstack and we do not roll back in the face of an error, so there were 525 successes and that won't change, that means that for all intents and purposes SIFT is installed.

I've opened https://github.com/sans-dfir/sift/issues/230 as an issue for me to track to get better support into the CLI tool to show errors.

**Comment by milshtyn** [comment]
I had the same issue when running installation on Ubuntu Server 16.04 in AWS as @hackdefendr with the exact same number of failures. I've pulled the logs with the failures (attached here). 
[SIFTInstallFailures.txt](https://github.com/sans-dfir/sift/files/1731340/SIFTInstallFailures.txt)
Note: One failure is missing I think. Didn't have time to figure out which one I missed.

The important thing here is that after install, running **sift upgrade**, I get an error saying that SIFT is not installed.

**Comment by ekristen** [comment]
Only Ubuntu desktop is supported with full install as full install includes GUI tweaks, PDFs and more. 

Erik

**Comment by milshtyn** [comment]
Thanks, Erik. What's interesting is that SANS published a whitepaper on
Digital Forensic Analysis of Amazon Linux EC2 Instances, which describes
steps to install SIFT on an Ubuntu AMI suggesting to do it on an Ubuntu
Server.
Weird.

Link to paper:
https://www.sans.org/reading-room/whitepapers/cloud/digital-forensic-analysis-amazon-linux-ec2-instances-38235


Thanks,
Ilya

**Comment by ekristen** [comment]
There’s nothing stopping you from using AWS, but you have to use 16.04 not 17.01 and realize that certain things won’t be successful on a server version. 

I’m working on figuring out how detect install targets a bit better and make it more clear.

Erik

**Comment by MMULLINIX1** [comment]
Thank you Eric, I will keep an eye out for that as I am starting to work on
the same thing. I would also like to use this in a teaching environment.

Michelle

**Comment by MMULLINIX1** [comment]
The SIFT on AWS that is. :)

**Comment by milshtyn** [comment]
Michelle,
Despite the failures, I was still able to get some of my forensics activities done using the "partial" install. Seems most of the tools were working (e.g. log2timeline.py, fls, mactime, foremost).
