### ISSUE TITLE
[CLI] notinstalled after installation

### ISSUE THREAD

**Issue by bergernetch** [sans-dfir/sift#228]
I am having issues with the sift cli installation.

Fresh Ubuntu 16.04 LTS with all updates installed.
Then SIFT using CLI `sudo sift install --mode=packages-only`. sift-cli indicated that v2017.48.0 was going to be installed.
Everything looked fine and the result was: `>> COMPLETED SUCCESSFULLY -- Success: 274, Failure: 0`

However, it seems like it is not installed:
> dfir@laptop:~$ sudo sift version
> [sudo] password for dfir: 
> \> sift-cli@1.5.1-beta.0-master.154cb2f
> \> sift-version: notinstalled

The same happens when executing sift update:
>dfir@laptop:~$ sudo sift update
\> sift-cli@1.5.1-beta.0-master.154cb2f
\> sift-version: notinstalled
>
> 
> SIFT not installed, unable to update
> Error: SIFT not installed, unable to update
>     at Object.<anonymous> (/snapshot/sift-cli/sift-cli.js:630:13)
>     at Generator.next (<anonymous>)
>     at Generator.tryCatcher (/snapshot/sift-cli/node_modules/bluebird/js/release/util.js:16:23)
>     at PromiseSpawn.module.exports.PromiseSpawn._promiseFulfilled (/snapshot/sift-cli/node_modules/bluebird/js/release/generators.js:97:49)
>     at Promise.module.exports.Promise._settlePromise (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:574:26)
>     at Promise.module.exports.Promise._settlePromise0 (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise.module.exports.Promise._settlePromises (/snapshot/sift-cli/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/snapshot/sift-cli/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/snapshot/sift-cli/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.__dirname.Async.drainQueues (/snapshot/sift-cli/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:672:20)
>     at tryOnImmediate (timers.js:645:5)
>     at processImmediate [as _immediateCallback] (timers.js:617:5)

I did it on a second laptop with the same result.

I found a closed issue that seems to be very similar: https://github.com/sans-dfir/sift/issues/181

**Comment by ekristen** [comment]
hi @bergernetch FWIW it's definitely installed. SIFT gets install piece by piece, and it does not rollback in case of error. However what you've found is a bug that I will fix as soon as possible.  The bug is that in packages-only mode, there is an instruction file that is skipped, this file is what is used to determine if "SIFT" is already installed or not. 

Just so you know the SIFT CLI is an abstracted layer on top of a technology called SaltStack, it's a very powerful configuration management tool that has allowed us to build out SIFT and keep it up-to-date very easily.

**Comment by ekristen** [comment]
https://github.com/sans-dfir/sift/issues/229

**Comment by bergernetch** [comment]
The same happens when executing a "full" installation with (no mode param set)
> sudo sift install

The file /etc/sift-version is missing then as well.

**Comment by ekristen** [comment]
You probably have failures on the full install. Upload the log from the full install and I’ll tell you why it failed.

**Comment by sharpie2018** [comment]
Hi, I'm having the same problem. After installing sudo sift install and sudo packages-only I still don't have any of the tools in the command line (vol.py or rip.pl). Can you please look at my log?
[saltstack.log](https://github.com/sans-dfir/sift/files/1732006/saltstack.log)

**Comment by ekristen** [comment]
@sharpie2018 only 16.04 is supported. You are attempting to install on 17.01.

@sharpie2018 there's a bug, packages-only will NEVER mark the install as complete (I'm working to fix this at this time)

**Comment by ekristen** [comment]
hi @Theokom 

If an install fails then an update will not be possible as it doesn't know what was installed. This is expected behavior. When this happens just run install again.

Your log seems to indicate that some python installs failed but at a glance I didn't see a reason.

Try running the install command again.

I am working on a new version of the tool that will attempt to retry failed portions if possible and at the very least try and provide more insight when something fails. Sorry for the problems.

**Comment by Theokom** [comment]
@ekristen Thank you for your reply.
I've started from scratch with a fresh 16.04 install, updated only.
Installed sift and this time finished ok with 0 errors.
After my first smile I did snapsot of vm and continued with a `sudo sift update` which returned 49 failures. (smile gone).
Is this something that can be explained? 
Attached is the new log file after the update.
[saltstack.log](https://github.com/sans-dfir/sift/files/1836758/saltstack.log)
Any thoughts?
Theo

**Comment by ekristen** [comment]
Don't start from scratch, just type `sudo sift install` again. The installer will only install what is missing.

**Comment by ekristen** [comment]
My test environment just ran 100% successfully.

Please make sure your OS is 16.04 Desktop, Unity (not Gnome) -- Once logged in to the desktop, open terminal and run commands. It will fail under any other scenario.

**Comment by mandykaandorp** [comment]
my sift installation failed with an error, (AttributeError: 'module' object has no attribute 'SSL_ST_INIT')

the comment of Jodumont on this page fixed it for me: https://github.com/brocaar/loraserver-setup/issues/13
