### ISSUE TITLE
[SALTSTACK] Packages Only Mode Fails to Mark as Installed

### ISSUE THREAD

**Issue by ekristen** [sans-dfir/sift#229]
When in packages-only mode, Saltstack doesn't record that it has been installed, this causes the CLI to act like it is not installed.

**Comment by stevogabe7** [comment]
Is there a solution to solve this?

**Comment by ekristen** [comment]
You can create /etc/sift-version and populate it with the value of the version attempted to be installed, then the update will work. 

I have to make a patch to fix it though.

**Comment by ekristen** [comment]
This is fixed. Pre-Release 2018.13.0-rc4
