### ISSUE TITLE
[CLI] install with failures

### ISSUE THREAD

**Issue by bergernetch** [sans-dfir/sift#231]
When executing a full install, it finishes with:
> \>\> Completed with Failures -- Success: 525, Failure: 4

I checked the log for errors, but couldn't find any (looked for error and failure).
I looked for result:false and found that 

- the poster sift-pdf-poster-network-forensics did not match the sha256 sum

- sift.config.sift-config failed

- sift.config.users.pdfs.sift-pdfs-poster-network-forensics failed (seems to be a duplicate of the first error)

- sift.config.users.sift-config-user failed

So it looks like there a more side effects of installing it on an Ubuntu compared to the SIFT VM.
[saltstack.log](https://github.com/sans-dfir/sift/files/1720404/saltstack.log)

At least the same problem, as described in https://github.com/sans-dfir/sift/issues/226 exists, as /etc/sift-version is missing after the full installation as well.

**Comment by blancast** [comment]
Just had the same result.
>> Completed with Failures -- Success: 525, Failure: 4
Fresh install of Ubuntu Desktop 16.04.3 on Dell hardware.

[saltstack.log.gz](https://github.com/sans-dfir/sift/files/1740768/saltstack.log.gz)

**Comment by ekristen** [comment]
You can always search the log file for `result: false` to find out what failed. 

It looks like a new PDF was uploaded and our hashes don't match, I'll kick a new update out tonight to resolve the issue.

**Comment by Fetchered** [comment]
Temporarily 'fixed' by downloading a copy of the poster and placing it on the Desktop. Downloaded from the SANS Posters page <https://www.sans.org/security-resources/posters/dfir/network-forensics-poster-145)

**Comment by ekristen** [comment]
We have a pre release that fixes it. Not officially released yet 

Erik

**Comment by ekristen** [comment]
Official release is out, 2018.8.0
