### ISSUE TITLE
sift-cli cannot execute binary file error

### ISSUE THREAD

**Issue by clausing** [sans-dfir/sift#242]
Brand new Ubuntu 16.04 install, trying to run the sift-cli, I wasn't able to download the GPG key, but the sha256 signature checked out (see below). I followed the directions, copied it to /usr/local/bin and changed the permissions.

investigator@sift4-reyn$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
investigator@sift4-reyn$ uname -a
Linux sift4-reyn 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:02:25 UTC 2018 i686 i686 i686 GNU/Linux

investigator@sift4-reyn$ shasum -a 256 -c sift-cli-linux.sha256.asc
sift-cli-linux: OK

investigator@sift4-reyn$ sift --help
bash: /usr/local/bin/sift: cannot execute binary file: Exec format error
investigator@sift4-reyn$ sudo sift --help
/usr/local/bin/sift: 1: /usr/local/bin/sift: cannot create XAï¿½@XÍ¸@@$@@@@@ï¿½ï¿@@@@ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½
                                                                                      ï¿½
                                                                                       ï¿½ï¿½H
 ï¿½ï¿½ï¿½ï¿½ï¿½
      ï¿½ï¿½
ï¿½ï¿½  0@@DDPï¿½td@ï¿½@ï¿½ï¿½@ï¿½ï¿½DBDBQï¿½td/lib64/ld-linux-x86-64.so.2GNUGNUwï¿½ï¿½ï¿½+ï¿½+I+Z9ï¿½oï¿½ï¿½.
  "Ä›ï¿½ï¿½ï¿½ï¿½
3C
4ï¿½(ï¿½Pï¿½0ï¿½ï¿½@b,ï¿½ïï¿½ï¿½Dhï¿½"ï¿½$ï¿½ï¿½HAï¿½ï¿½!)ï¿½/pï¿½cï¿½Bï¿½GHDï¿½0Pï¿½ï¿½Bï¿½`Eï¿½ï¿½ï¿½A&0Hï¿½ï¿½ï¿½xï¿½ï¿½ ï¿½ï¿½"òŒ±€rIï¿½!"@ï¿½ï¿½@ï¿½ï¿½s"+ï¿½Aï¿½ï¿½ H Dhhï¿Lï¿½ï¿½(ï¿½ï¿½ï¿½@P A"ï¿½ï¿½ï¿½ï¿½4     @@1ï¿½ï¿½gH5
ï¿½ ï¿½pGï¿½ï¿½ï¿1ï¿½ï¿½A,Dï¿½@ dï¿½<ï¿½aï¿½&ï¿½&ï¿½Xï¿½ï¿½ÎŒï¿½pï¿½ï¿½Nï¿½
$ï¿ Lï¿½ ï¿½&C10ï¿½A$ï¿½ï¿½vï¿½C!ï¿½ &`ï¿½b/`Mmï¿½ï¿½aTï¿½0ï¿½Cï¿½
ï¿½ï¿½ ï¿½(ï¿½Tï¿½ï¿½Mï¿½Xï¿½Rï¿½ï¿½ï¿ï¿½cE<ï¿½!ï¿½ï¿½ï¿½ÄŠ#8ï¿½VJ!ï¿½ï¿½ztï¿½Uï¿½Qht ï¿½2 0/ï¿½Jï¿½ï¿½ï¿½Â°ï¿½;ï¿½ï¿½L)`dq@Iqï¿ï¿½ ï¿½ï¿½5.ï¿½&ï¿½ï¿½pï¿½ï¿½ï¿½%ï¿½ï¿½ï¿½eï¿½
ï¿½ï¿½`DE ï¿½Pï¿½ï¿½
         ï¿½ï¿½@ï¿½ ï¿½ $ï¿½ï¿½ï¿½#\Aï¿½sï¿½2ï¿½ï¿½ï¿½B&
"ï¿½3
Fï¿½½ï¿½0ï¿½" ï¿½! ï¿½@dï¿½ï¿½Èƒ ½ï¿½ï¿½hï¿½ J`ï¿½F:@U9ï¿½D@

ï¿½fï¿½"@Dï¿½ï¿½Rï¿½
          FBï¿½O:L:cï¿½Hï¿½"ï¿½4i&E,1(ï¿½ï¿HA,70ï¿½ï¿½ï¿½$ï¿½D"(ï¿½ï¿½@ï¿½ï¿½ ï¿½ï¿½Qï¿½ï¿½jï¿})ï¿½!dï¿½1P\Tï¿½ï¿½ï¿½5Xï¿½0Tï¿½Dï¿½ï¿½(
ï¿½ï¿½Eï¿½7ï¿½$ ï¿½ ï¿½P%&2#        aï¿½aJï¿½Krrï¿½D.ï¿½ï¿½+ï¿½pï¿½*#
*HyPï¿½dï¿½ 
ï¿½
   h@Bï¿½pï¿½Dï¿½tK&ï¿½0ï¿½ï¿½ ï¿½ï¿½
#ï¿½ï¿½AL
Ä‘â¶´Uï¿½qPPï¿½+xï¿½L$ï¿½ï¿½ï¿½CT%ï¿½aï¿½ï¿½ï¿½ï¿½       ï¿½
ï¿ï¿½(($,X +bxï¿½ï¿½`ï¿½t$ï¿½V$Hï¿½b ï¿½ï¿½ï¿½Dï¿½ï¿½ï¿½ï¿½ï¿½U!ï¿½ï¿½ï¿½Bl1ï¿½       ï¿½abï¿½Ñ³ï¿½() btAK c\!Nï¿½@&ï¿½ï¿½Iï¿½ï¿½D%9sï¿½ï¿½$XÙ‘ï¿½ï¿½M Hï¿½Lï¿½ïï¿½@: Directory nonexistent¿½@BPï¿½a
/usr/local/bin/sift: 1: /usr/local/bin/sift: ELF: not found

**Comment by ekristen** [comment]
Hi @clausing 

Only 64bit systems are supported.

Unfortunately your ubuntu system is 32bit and is not supported and there are no plans to support 32 bit systems.

**Comment by clausing** [comment]
oops, I thought I had installed a 64-bit system, just noticed that said i686, sorry for bothering you, I'll rebuild the VM

**Comment by ekristen** [comment]
No bother at all.
