### ISSUE TITLE
[CLI] SIFT install fails

### ISSUE THREAD

**Issue by sohsec** [sans-dfir/sift#245]
sift install
> sift-cli@1.5.1-beta.0-master.154cb2f
Warning: You are running as root.
Error: You cannot install as root without specifying the --user option.

The install user specified with --user must not be the root user

sift --user=ubuntu install
> sift-cli@1.5.1-beta.0-master.154cb2f
Warning: You are running as root.
> sift-version: notinstalled

**Comment by ekristen** [comment]
You cannot run as root. Running as root and specifying a user isn't allowed either.

You must use sudo.
