### ISSUE TITLE
Hashes for sift-saltstack-v2018.08.0.tar.gz do not match

### ISSUE THREAD

**Issue by glennbarrett** [sans-dfir/sift#246]
Trying a sift upgrade to 2018.08.0 results in a hash mismatch:

$ sudo sift upgrade
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: v2017.48.0

> downloading v2018.08.0
>> downloading sift-saltstack-v2018.08.0.tar.gz.asc
>> downloading sift-saltstack-v2018.08.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.08.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.08.0.tar.gz
> validating file sift-saltstack-v2018.08.0.tar.gz

Hashes for sift-saltstack-v2018.08.0.tar.gz do not match. Expected: ed4459b9440c41e5b89e408853662f524b2b928f70a90b0de9bae3ce351f1f57  /tmp/sift-saltstack-v2018.08.0.tar.gz
, Actual: 47e200e56c7622078d006e0bc8b756882fca5f3ea17f6c30c65ad6c13f910692  /tmp/sift-saltstack-v2018.08.0.tar.gz

Error: Hashes for sift-saltstack-v2018.08.0.tar.gz do not match. Expected: ed4459b9440c41e5b89e408853662f524b2b928f70a90b0de9bae3ce351f1f57  /tmp/sift-saltstack-v2018.08.0.tar.gz
, Actual: 47e200e56c7622078d006e0bc8b756882fca5f3ea17f6c30c65ad6c13f910692  /tmp/sift-saltstack-v2018.08.0.tar.gz

**Comment by ekristen** [comment]
Try with —no-cache option sounds like a bad download.

**Comment by glennbarrett** [comment]
Looks like that worked.
