### ISSUE TITLE
SIFT Installation Inside Docker Fails

### ISSUE THREAD

**Issue by nov3mb3r** [sans-dfir/sift#248]
I'm trying to install SIFT packages on an Ubuntu 16.04 docker container. 
At first, i had to make a new user (in this case: sift), as sift doesn't let root be the installation target. But even after specifying this new user, this error appears, although clearly I'm executing as root. 
```
root@6e9dccdde3bd:/data# useradd sift
root@6e9dccdde3bd:/data# sift install --mode=packages-only --user sift
> sift-cli@1.5.2-master.2035949
Warning: You are running as root.
> sift-version: notinstalled

> Error! You must be root to execute this.
```

**Comment by ekristen** [comment]
@nov3mb3r docker really isn't the correct medium for install sift.

**Comment by nov3mb3r** [comment]
Most of the forensics tool are command line based, so why waste resources on a VM ? I find docker to be more efficient in such cases and both SANS and the forensic community would benefit a lot if a docker image was built

**Comment by ekristen** [comment]
@nov3mb3r I couldn't agree more, however your approach is wrong. 

Each tool or a small subset of tools should be created in their own docker image using a Dockerfile or a build tool.

Trying to install sift inside of docker to create an image would result in a multi-gigabyte image that basically defaults the purpose.

Remnux has already started doing this with some tools, you can look them for examples. 

https://hub.docker.com/r/remnux/

**Comment by nov3mb3r** [comment]
@ekristen Well i builded an image with some of the most used SIFT packages. It's lightweight too. https://github.com/nov3mb3r/dfir . I find it's best to contain some tools together (like volatility and regripper) rather than having them installed on different containers.

**Comment by ekristen** [comment]
Hey @nov3mb3r it looks like I never submitted my original response to your latest comment.  I think what you are doing is great, docker is definitely the way to go. 

The image you've created looks pretty heavy from it's build file, but I haven't have had a chance to actually download it yet.

There are many ways to use docker, just remember it's not a virtual machine and shouldn't be treated as such.

I'm going to close this issue for now, feel free to continue commenting.
