### ISSUE TITLE
[SALTSTACK] Enhancement - Ballenthin/FireEye Tools

### ISSUE THREAD

**Issue by esecrpm** [sans-dfir/sift#250]
Please add the following Ballenthin/FireEye tools to the SIFT CLI build

INDXParse
python-sdb
EVTXtract
srum-dump
shellbags
Lfle

python-cim

**Comment by ekristen** [comment]
INDXParse, Shellbags are already included for sure. I'll have to verify the others.

**Comment by esecrpm** [comment]
[saltstack_2018.08.0.log](https://github.com/sans-dfir/sift/files/1884848/saltstack_2018.08.0.log)
Hi Erik,

I see the shellbags.sls and indxparse.sls files in /var/cache/sift/cli/v2018.08.0/sift-saltstack-2018.08.0/sift/python-packages, but I cannot either tool from the command line.  

I don't recall if there were any failures during the install, but there's no mention of either package in the saltstack.log file.  I'm performing sift update now, will follow with sift upgrade, then build a new VM if these don't work.  I'll report my findings shortly.

Thanks,
Erik

**Comment by ekristen** [comment]
They should all be in /usr/local/bin

**Comment by esecrpm** [comment]
Hi Erik,

I ran sift update and got the following results. I've also included the saltstack.log file for review.
>> Completed with Failures -- Success: 256, Failure: 276

When I ls the /usr/local/bin directory, I don't see either INDXParse.py or shellbags.py.

I'm building a new SIFT VM now.  I'll let you know if these packages are installed once it's finished.

Thanks again,
Erik
[saltstack_2018.08.0_update.log](https://github.com/sans-dfir/sift/files/1885006/saltstack_2018.08.0_update.log)

**Comment by ekristen** [comment]
```salt-call --versions```

**Comment by esecrpm** [comment]
On the previous build:

$ salt-call --versions
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-37-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by esecrpm** [comment]
On today's build (still no INDXParse.py or shellbags.py):

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by ekristen** [comment]
Yeah it seems that salt isn't being pinned properly so it upgraded to a new version that's incompatible. I'll have to look at how to fix this tonight. 

FYI if you have any failures in the output then the sift update/upgrade/install is not complete and things will be wrong/missing, especially on a new install.

**Comment by esecrpm** [comment]
Ok, thanks!

Erik

**Comment by ekristen** [comment]
@esecrpm this shoudl be fixed, please test by manually downloading the CLI - https://github.com/sans-dfir/sift/issues/251

**Comment by esecrpm** [comment]
Hi Erik,

I was able to download CLI 1.6.0 and update a 2017.48.0 and 2018.08.0 SIFT VM, but INDXparse and shellbags did not get installed with the update.  I confirmed the salt package versions and CLI version on both SIFT systems after install:

# dpkg -s salt-minion salt-common | grep 'Version'
Version: 2017.7.5+ds-1
Version: 2017.7.5+ds-1
# sift -v
Version: 1.5.1-beta.0, Build: master-154cb2f

I also tried to install SIFT using CLI 1.6.0 on a clean ubuntu 16.04 VM and received an error about a missing '/etc/apt/sources.list.d/saltstack.list' file.  I have included the stdout, saltstack.log and /usr/local/bin listing for both SIFT VM updates, plus the clean ubuntu install error in the attached zip.  Please let me know if there's anything else I can do/provide.

Thanks,
Erik
[troubleshooting.zip](https://github.com/sans-dfir/sift/files/1890577/troubleshooting.zip)
