### ISSUE TITLE
SIFT Will Not Open

### ISSUE THREAD

**Issue by NewGuy02** [sans-dfir/sift#253]
I downloaded the SIFT file twice and received the following error message: 
"Error while converting to a virtual machine: Did not find an .ovf file at the beginning of the OVA package."

I have VMware Workstation 14 installed on my laptop.

**Comment by ekristen** [comment]
Did you compare hashes?

**Comment by NewGuy02** [comment]
No, I did not. I'll check it now.

**Comment by ekristen** [comment]
Let me know if you are still having issues.
