### ISSUE TITLE
[CLI] Update issues

### ISSUE THREAD

**Issue by zappeee** [sans-dfir/sift#254]
Tried to update my sift a few times but it runs into a few issues, see attached

[saltstack.txt](https://github.com/sans-dfir/sift/files/1898907/saltstack.txt)

**Comment by ekristen** [comment]
Looks like a few different packages failed, including libxslt-dev, works just fine for me.

What happens when you run `apt-get install libxslt-dev`

**Comment by zappeee** [comment]
> $ sudo apt-get install libxslt-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
libxslt1-dev is already the newest version (1.1.28-2.1ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Also, a lot more errors today when running update, see attached
[saltstack.log](https://github.com/sans-dfir/sift/files/1915694/saltstack.log)

**Comment by nov3mb3r** [comment]
I ran into the same problems. libxslt-dev didn't fix anything.
@ekristen volatility community and sift plugins are missing too :(
Check attached.
[saltstack.log](https://github.com/sans-dfir/sift/files/1925610/saltstack.log)

**Comment by ekristen** [comment]
@nov3mb3r @zappeee can you please make sure you grab the latest sift-cli and run with the --pre-elease flag.

I've been noticing some inconsistencies within the last few days. I'm seeing some weird pip install issues that are in your logs.

It's possible that something has changed with python2/3 and pip or something with saltstack underneath that's causing issues. I'm trying to track it down, but haven't had much success just yet.

**Comment by ekristen** [comment]
@nov3mb3r if you ran `sift install --pre-release` and you got v1.5.1 then that tells me the sift-cli wasn't updated properly.

Do this
```
curl -Lo /tmp/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.6.1/sift-cli-linux
sudo mv /tmp/sift /usr/local/bin/sift
sudo chmod +x /usr/local/bin/sift
```
then this
```
sudo sift install --pre-release
```

**Comment by zappeee** [comment]
Upgraded to 1.6.1 and still have a fair amount of issues.
Do you want me to try upgrade --pre-release also?
[saltstack.log](https://github.com/sans-dfir/sift/files/1927104/saltstack.log)

**Comment by nov3mb3r** [comment]
@ekristen Followed the instructions but still 53 errors appear

> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled

**Comment by ekristen** [comment]
@nov3mb3r I'll need your log.

**Comment by nov3mb3r** [comment]
[saltstack.log](https://github.com/sans-dfir/sift/files/1928194/saltstack.log)

**Comment by ekristen** [comment]
@zappeee it seems there is something wrong with your pip.  It might be broken past what I can solve using the sift-cli and install scripts. You can try the following, otherwise you might have to start fresh, or do some further troubleshooting to see if can get get `pip` working. You need version 9.0.3 or less. If 10.* gets installed things go south.

This is the common error in your log @zappeee ```An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.```

If you already have 1.6.1 cli installed then do the following.

```
sudo apt-get remove python-pip
sudo apt-get install python-pip
sudo sift install --pre-release
```

**Comment by ekristen** [comment]
@nov3mb3r same error, so try the instructions above. If that doesn't work you might need to start over, or if you are willing troubleshoot python and python pip, that's where the problem is.

**Comment by nov3mb3r** [comment]
Just freshed install Ubuntu 16.04 and followed your instructions. 
> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled

> downloading v2018.16.0
>> downloading sift-saltstack-v2018.16.0.tar.gz.asc
>> downloading sift-saltstack-v2018.16.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.16.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.16.0.tar.gz
> validating file sift-saltstack-v2018.16.0.tar.gz

Hashes for sift-saltstack-v2018.16.0.tar.gz do not match. Expected: b629b8d5d77ac5ad877085437321c7dbaec74047e778317689c993f6258ad03a  /tmp/sift-saltstack-v2018.16.0.tar.gz
, Actual: 439160abc3f77ada73932b2cf03c9a47c0adf67e6d69b6b57934dcd510918476  /tmp/sift-saltstack-v2018.16.0.tar.gz
Error: Hashes for sift-saltstack-v2018.16.0.tar.gz do not match. Expected: b629b8d5d77ac5ad877085437321c7dbaec74047e778317689c993f6258ad03a  /tmp/sift-saltstack-v2018.16.0.tar.gz

**Comment by ekristen** [comment]
try with --no-cache and try again.

**Comment by zappeee** [comment]
There's something strange with SIFT.
It said it was back to 1.5.1.
I tried to do a install --pre-install but it says it was up to date.
I rebooted, it now showed 1.6.1
I then tried an upgrade to 2018.16.0 but after a reboot is was back to 2018.08.0
Also the pip issues is still there.

Nothing to do but start fresh?

**Comment by krisgelijkaan** [comment]
might this be part of the issue:
cat /var/cache/sift/cli/v2018.16.0/sift-saltstack-2018.16.0/sift/packages/libxslt-dev.sls
libxslt-dev:
  pkg.installed

apt-cache policy libxslt-dev
libxslt-dev:
  Installed: (none)
  Candidate: (none)
  Version table:

apt-cache policy libxslt1-dev
libxslt1-dev:
  Installed: 1.1.28-2.1ubuntu0.1
  Candidate: 1.1.28-2.1ubuntu0.1
  Version table:
 *** 1.1.28-2.1ubuntu0.1 500
        500 http://be.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.28-2.1 500
        500 http://be.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by krisgelijkaan** [comment]
3 remaining errors concerning pip3 not being installed (while it was):
sudo apt-get -y remove python3-pip
sudo apt-get -y install python3-pip

sift version
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.16.0

**Comment by ekristen** [comment]
@nov3mb3r I think you issue stems from you have pip 10.x installed. If you force it back down to 9.0.3 and then run your install it should all be good.

**Comment by nov3mb3r** [comment]
@ekristen That did the trick!!
Still some minor errors appear, but volatility works fine!

**Comment by zappeee** [comment]
I did a fresh install now and it's all good

sansforensics@ubuntu:~/Downloads$ sudo sift version
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.16.0
