### ISSUE TITLE
Volatility failing due to DPAPICK failure 

### ISSUE THREAD

**Issue by whiteknight21** [sans-dfir/sift#256]
Further to previous comment, seem to have fixed other problems however I cannot get main vol.py modules to run due to this error : 
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : Please install DPAPIck library: https://bitbucket.org/jmichel/dpapick

The module is installed : 
$ pip install dpapick
Requirement already satisfied: dpapick in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from dpapick)
Requirement already satisfied: M2Crypto>=0.21.1 in /usr/local/lib/python2.7/dist-packages (from dpapick)
Requirement already satisfied: CFPropertyList in /usr/local/lib/python2.7/dist-packages (from dpapick)
Requirement already satisfied: python-registry>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from dpapick)
Requirement already satisfied: typing in /usr/local/lib/python2.7/dist-packages (from M2Crypto>=0.21.1->dpapick)
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (from python-registry>=1.0.4->dpapick)

Please advise ..

**Comment by ekristen** [comment]
DPAPIck definitely gets installed. Can you confirm you've had a 100% successful install? 

This is the install file -- https://github.com/sans-dfir/sift-saltstack/blob/master/sift/python-packages/dpapick.sls
