### ISSUE TITLE
[cli] connection refused by pgp.mit.edu when I request key for sift linux client install

### ISSUE THREAD

**Issue by dwebb27604** [sans-dfir/sift#258]
I'm getting connection refused when I attempt:

gpg --keyserver pgp.mit.edu --recv -keys 22598A94

**Comment by ekristen** [comment]
You can try 

```
gpg --keyserver hkp://pgp.mit.edu --recv-keys 22598A94
```

```
gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94
```

**Comment by dwebb27604** [comment]
Thanks... the 2nd one worked for me:
gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94

without :80 it still refused connection...

**Comment by dwebb27604** [comment]
Thanks again...

**Comment by jwilczek** [comment]
Even trying port 80 isn't currently working for me.

**Comment by ekristen** [comment]
Hi @jwilczek sorry you are having issues. I've listed the commands that do and don't work for me.

Are you using a proxy? Have you checked your network in general?

This works
```
gpg --keyserver pgp.mit.edu --recv-keys 22598A94
```

This does **not**:
```
gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94
```

This works
```
gpg --keyserver hkp://pgp.mit.edu --recv-keys 22598A94
```

You can always go to http://pgp.mit.edu/ search and download the key from there.
