### ISSUE TITLE
[CLI] Ubuntu 18.04 Bionic Support

### ISSUE THREAD

**Issue by KadeG** [sans-dfir/sift#265]
What needs to happen for 18.04 support?

**Comment by ekristen** [comment]
Thanks for asking! 

I haven’t yet investigated that fully but in verbal this is what has to happen.

All the packages we depend on from the SIFT and GIFT repos will have to be rebuilt for 18.04.

Ubuntu switched back to gnome from unity so we’ll have to potentially redo any of the UI alterations we did for unity for gnome. 

We will have to check and see if any of the packages we install from the normal public repos have been renamed or replaced and adjust accordingly.

Then it’s test test and test some more.

Erik

**Comment by KadeG** [comment]
Sounds good!

Any idea what's going on here? I think something is wrong with the package descriptions.

https://launchpad.net/ubuntu/bionic/+source/sift

https://launchpad.net/ubuntu/+source/sift/4.0.3b-6
