### ISSUE TITLE
sift install & sift update

### ISSUE THREAD

**Issue by life-long-learner** [sans-dfir/sift#267]
As a beginner to Linux and SIFT I can't figure out why the SIFT install is not working.

I have installed Ubuntu 16.04 on VMware, then installed SIFT - no problems on box1
I have also downloaded the SIFT .ova file and installed it on VMware - no problems on box2
On box3 I am running into the following issues with installing SIFT:
I have attached the standard output for the SIFT install & have also attached the saltstack.log file.
I searched for twelve errors, failures and anything that was false, but I found more that 12.  

Is there something that is simple that I am missing, overlooking or is there a configuration problem, or do I need to start over again?
 
[StdOutput.txt](https://github.com/sans-dfir/sift/files/1957584/StdOutput.txt)
[saltstack.log](https://github.com/sans-dfir/sift/files/1957585/saltstack.log)

**Background -** 
On the following OS:
Edition  Windows 10 Pro
Version  1709
Build:     16299.321

**Installed Ubuntu 16.04.3 from MS Store on WSL:**
After a successful install of Ubuntu I ran the following:
# apt-get update
# apt-get upgrade
# apt-get dist-upgrade

**then, downloaded the sift-cli and followed the instructions** 
/home/forensicator# sift install
> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled
Installing and configuring SaltStack properly ...
>> Completed with Failures -- Success: 527, Failure: 12

/home/forensicator# sift update
> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled

NOTICE: Fixing incorrect Saltstack configuration.
Installing and configuring Saltstack properly ...

SIFT not installed, unable to update
Error: SIFT not installed, unable to update
143:10)
    at Immediate.__dirname.Async.drainQueues (/snapshot/Users/ekristen/Development/sift/sift-cli/node_modules/bluebird/j
s/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**The following commands show:**
$ uname -r
4.4.0-43-Microsoft
$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l
$ sift version
> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled

Thank you.

**Comment by ekristen** [comment]
We do not currently support installing in the Linux subsystem on windows. 

You can attempt using the flag —packages-only but no guarantees.

If you don’t get a 100% install you cannot upgrade. 

Erik

**Comment by life-long-learner** [comment]
ahhh, that makes sense why it is not working. 

Thank you for your time and input, I appreciate it.
