### ISSUE TITLE
Shared folders not available

### ISSUE THREAD

**Issue by Enz197** [sans-dfir/sift#270]
InSIFT 3 I enabled shared folders in vmware but /mnt/hgfs is empty.
The command /usr/bin/vmware-hgfsclient show the shared folder name.
How can I enable and access the shared folder from SIFT to my Windows host?
Thanks.

Enz

**Comment by philhagen** [comment]
This is common with certain versions of VMware (and, more specifically, vmware-tools).  Try disabling the shared folders, closing the dialog box, re-enabling them, and then open a new terminal/file window in `/mnt/hgfs/`

**Comment by Enz197** [comment]
Thank you Phil, you solved my problem.
I close this issue.

**Comment by ekristen** [comment]
Thanks @philhagen for fielding the question!
