### ISSUE TITLE
[CLI] Xenial sift repos states are disabling main repository on some cases

### ISSUE THREAD

**Issue by ptitdoc** [sans-dfir/sift#271]
1/ Start with the following source.list file:
```
deb http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted
deb http://archive.canonical.com/ubuntu xenial partner
deb http://archive.ubuntu.com/ubuntu xenial-security main universe multiverse restricted 
deb http://archive.ubuntu.com/ubuntu xenial-updates main universe multiverse restricted 
```
2/ Running sift.repos state 
`sudo salt-call -l info --local --file-root=/home/user/sift-saltstack-2018.16.0 state.apply sift.repos`

3/ The source.list file has been modified disabling main repository. In consequence, most packages are failing to install because of missing dependencies:
```
deb http://archive.ubuntu.com/ubuntu xenial multiverse
deb http://archive.canonical.com/ubuntu xenial partner
deb http://archive.ubuntu.com/ubuntu xenial-security multiverse
deb http://archive.ubuntu.com/ubuntu xenial-updates main universe multiverse restricted
deb http://archive.ubuntu.com/ubuntu xenial universe
```

The current workaround is to ensure that main, universe, and multiverse repositories are on separate lines in /etc/apt/sources.list.

**Comment by ekristen** [comment]
Hi @ptitdoc, thanks for the report. I'm not sure I can agree with your assessment. 

The states do not disable main specifically, and on a fresh install of SIFT using the CLI tool. Main is still enabled. Please see below the entirety of the `sources.list` minus commented out lines.

```
deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
deb http://us.archive.ubuntu.com/ubuntu/ xenial universe
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe
deb http://us.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
deb http://us.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu xenial-security multiverse
deb http://archive.ubuntu.com/ubuntu xenial multiverse
deb http://archive.ubuntu.com/ubuntu xenial-security multiverse
deb http://archive.ubuntu.com/ubuntu xenial universe
```

**Comment by ptitdoc** [comment]
Yes I recognize that my install is not fresh (the sources.list has already be modified by third party scripts).

However if there is the following line:
`deb http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted`

Running the following salt state:
```
  pkgrepo.managed:
    - name: deb http://archive.ubuntu.com/ubuntu/ {{ grains['lsb_distrib_codename'] }} universe
```
will cause `main`, `multiverse` and `restricted` to be removed.

Quoting saltstack documentation:

> On apt-based systems this [the name parameter] must be the complete entry as it would be seen in the sources.list file. This can have a limited subset of components (i.e. 'main') which can be added/modified with the comps option.

This means that saltstack apparently does not provide a way to deal with this specific problem.

**Comment by ekristen** [comment]
I see. So you have a completed altered non-default sources.list file then a default ubuntu 16.04 is that correct?

**Comment by ptitdoc** [comment]
Sorry, I dont understand your question. I have a fresh Ubuntu however it is installed and slighly customized using some kind of build scripts instead of using the installer.
In the end, source.list is modified in order to enable all repositories which is why I ends with this issue.
I see there is a comps parameter for pkgrepo.managed. I will check if it is a potential solution. If not, I think the issue could be closed as fixing source.list to use only one repository per line solves the problem.

**Comment by ekristen** [comment]
@ptitdoc no problem. 

Basically you have a non-default sources.list file, which is causing the problem. In a fresh non-modified version when we ensure that the repos we need are managed it is no problem. It seems that with your custom version it is a problem.

I'll leave this issue open and look for a possible solution in the future.
