### ISSUE TITLE
[CLI] sift --install breaks systems on which salt is already used

### ISSUE THREAD

**Issue by ptitdoc** [sans-dfir/sift#272]
`sift --install` can break systems that are actively using salt because:
1/ It stops and disable salt-minion daemon in the sift.config.salt-minion state
2/ It re-install salt by first removing salt-minion and then installing new salt packages, thus removing all third party packages depending on salt.

A workaround for 1/ is to add an option to ensure that sift cli tool is not managing the salt configuration.

The solution for 2/ is to ensure that sift-cli.js is only updating salt instead of removing it and reinstalling it.

**Comment by ekristen** [comment]
@ptitdoc thank you for the information. I'd definitely consider this an advanced use case.

Your best bet would be to use the states directly. We might be able to make some tweaks to allow for more configs to disable/enable certain things, but first and foremost we need to make sure things continue to work for the classroom.

Pull Requests welcome, but the current behavior has to be the default.

**Comment by ptitdoc** [comment]
The previous commit allows add sift_manage_salt pillar option allowing to skip salt-minion state if set to False. It however only fixes case 1/.

The default behavior is still to disable salt-minion service.

In the same time, I added pillar.example documentation that can be used as reference for people looking for available pillar options.
