### ISSUE TITLE
[CLI] sift Install Fails / Unable to update sift

### ISSUE THREAD

**Issue by jwilczek** [sans-dfir/sift#273]
I've installed sift using the steps provided (exactly). I've tried multiple times and always get 4 failures.

`>> Completed with Failures -- Success: 535, Failure: 4`

In reviewing the command line output, I cannot pinpoint the errors that occurred.

From reading other issues, I'm assuming the 4 failures are why, when trying to update sift, i get the error

```
$ sudo sift update
> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled
SIFT not installed, unable to update
```

This is on Ubuntu 16.04.4 Desktop x64.

**Comment by sansstudent** [comment]
same here. exact the same here.

**Comment by sansstudent** [comment]
[saltstack.log](https://github.com/sans-dfir/sift/files/2047415/saltstack.log)

**Comment by ekristen** [comment]
This is an easy fix. Looks like one of the PDFs was updated. Let me update things and cut a release.

**Comment by sansstudent** [comment]
thank you, i will provide the feedback after testing
best regards

**Comment by jwilczek** [comment]
I'm still seeing the same issue after re-running the install.

**Comment by ekristen** [comment]
an install can’t have any failures or it’s not installed, therefore an update won’t work.

Run the install again, see what errors you get.

Installs don’t uninstall anything in the event of failure.

**Comment by jwilczek** [comment]
sift update output:
`
> sift-cli@1.6.1-master.bde3e23
> sift-version: notinstalled
...
>> Completed with Failures -- Success: 485, Failure: 54
`

**Comment by ekristen** [comment]
Can you look for result: false in the saltstack log in the sift install cache folder? We need to identify what’s failing.

**Comment by jwilczek** [comment]
I see many...

[saltstack.log](https://github.com/sans-dfir/sift/files/2081127/saltstack.log)

**Comment by sansstudent** [comment]
it works for me now :-) just redo sift --install

**Comment by jwilczek** [comment]
Yeah, after redoing that, I'm still getting the same errors.

>> Completed with Failures -- Success: 485, Failure: 54

**Comment by jwilczek** [comment]
Still seeing issues after pulling down latest. I've been trying to research these issues, but haven't found a fix yet.

`>> Incomplete due to Failures -- Success: 532, Failure: 7

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 261
        Comment: Error installing 'machinae': Access denied to /usr/bin/pip3, could not find a pip binary
      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 473
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 487
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 488
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 489
        Comment: One or more requisite failed: sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-minimize-window
      - ID: undefined
        SLS: sift.config
        Run#: 544
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.config.sift-config`

**Comment by Resistor52** [comment]
I am seeing the same issue, but it dies at Plaso.  Here is the steps that reproduce it:

Downloaded Ubuntu (http://releases.ubuntu.com/xenial/ubuntu-16.04.5-desktop-amd64.iso) and launched it on VMWARE.  Ran the following commands:

# apt update
# apt upgrade
# apt install curl
# curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.7.1/sift-cli-linux
# chmod +x /usr/local/bin/sift
# sift install
...

>> Completed: /etc/foremost.conf (Took: 20.959 ms)
>> Completed: /usr/local/etc/foremost.conf (Took: 29.987 ms)
>> Completed: sift-config-tools (Took: 0.925 ms)
>> Completed: sift-config (Took: 6.839 ms)

>> Incomplete due to Failures -- Success: 535, Failure: 4

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: python-plaso
        SLS: sift.packages.python-plaso
        Run#: 153
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-rebd587741e95413594e9164eaaad9e1a.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: undefined
        SLS: sift.packages.plaso-tools
        Run#: 154
        Comment: One or more requisite failed: sift.packages.python-plaso.python-plaso
      - ID: undefined
        SLS: sift.packages
        Run#: 254
        Comment: One or more requisite failed: sift.packages.python-plaso.python-plaso
      - ID: undefined
        SLS: sift.vm
        Run#: 547
        Comment: One or more requisite failed: sift.packages.sift-packages
root@ubuntu:/home/ken#

**Comment by ekristen** [comment]
I will take a look at plaso this week.

**Comment by siuchark** [comment]
hi there i've got some errors a little bit different as below.  Based on ubuntu-16.04.5-desktop-amd64

```
$ sudo sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2018.35.0
>> downloading sift-saltstack-v2018.35.0.tar.gz.asc
>> downloading sift-saltstack-v2018.35.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.35.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.35.0.tar.gz
> validating file sift-saltstack-v2018.35.0.tar.gz
> validating signature for sift-saltstack-v2018.35.0.tar.gz.sha256
> extracting update sift-saltstack-v2018.35.0.tar.gz
> performing update v2018.35.0
>> Log file: /var/cache/sift/cli/v2018.35.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by hfakar** [comment]
Same here. 164 packages failed.

**Comment by ekristen** [comment]
The output of the command line tool will tell you the first failure, this is generally the root cause.
