### ISSUE TITLE
[SALTSTACK] pescanner fails in v2018.22.0

### ISSUE THREAD

**Issue by esecrpm** [sans-dfir/sift#276]
pescanner.py is not configured with yara or userdb files

pydams is not installed, see http://code.google.com/p/libdasm/
Traceback (most recent call last):
  File "/usr/local/bin/pescanner.py", line 495, in <module>
    pescan = PEScanner(files, '/path/to/rules.yara', '/path/to/userdb.txt')
  File "/usr/local/bin/pescanner.py", line 129, in __init__
    self.rules = yara.compile(yara_rules)
yara.Error: (2, 'No such file or directory')

After adding the capabilities.yara and userdb.txt files from REMnux to pescanner.py, the script fails with the following error:
 
pydams is not installed, see http://code.google.com/p/libdasm/
Traceback (most recent call last):
  File "/usr/local/bin/pescanner.py", line 496, in <module>
    pescan.collect(verb)
  File "/usr/local/bin/pescanner.py", line 370, in collect
    i = pydasm.get_instruction(data[offset:], pydasm.MODE_32)
NameError: global name 'pydasm' is not defined

Attempted installing libdasm from the Google Code link and still received the same error.

**Comment by ekristen** [comment]
@esecrpm I'm starting to collect artifacts and example usage of commands where possible so I can built tests out against tools when we build the VM, any chance you could help out with that? Thanks.

**Comment by esecrpm** [comment]
Hi Erik,

I would be happy to help! Please let me know what I can do, or if you have a template for building test plans.

Thanks,
Erik

**Comment by ekristen** [comment]
Common command options with source artifacts and expected output is mainly what is needed. I don’t have a specific format for this yet.

**Comment by esecrpm** [comment]
Erik,

I have attached a sample XML file with basic tool input/options/output data.  Is this the type of data and is it in a format that you can use?

Thanks,
Erik

**Comment by ekristen** [comment]
The attachment didn't come through.

Lets make it more simple for now.

Lets do `state-name.command.txt`, `state-name.input.txt`, and `state-name.output.txt` to start.

So in this case it would be `pescanner.command.txt`, `pescanner.input.txt` and `pescanner.output.txt`

**Comment by esecrpm** [comment]
Erik,

Here are some examples, plus another attempt at the XML file.  Please let me know how I can modify the files to better suit your testing needs.

Thanks,
Erik

[pescanner.command.txt](https://github.com/sans-dfir/sift/files/2178546/pescanner.command.txt)
[pescanner.input.txt](https://github.com/sans-dfir/sift/files/2178547/pescanner.input.txt)
[pescanner.output.txt](https://github.com/sans-dfir/sift/files/2178548/pescanner.output.txt)
[test.xml.txt](https://github.com/sans-dfir/sift/files/2178555/test.xml.txt)

**Comment by dougkoster** [comment]
Hi Erik,

I am getting the same error from the 16.04 SIFT .ova VM. Is there a solution that I can implement to get pescanner.py  to work?
