### ISSUE TITLE
SIFT on Zorin OS

### ISSUE THREAD

**Issue by nivekko** [sans-dfir/sift#280]
Any experience with installing SIFT in Zorin OS? I keep getting a Saltstack error log
[saltstack.txt](https://github.com/sans-dfir/sift/files/2116531/saltstack.txt)

**Comment by nivekko** [comment]
This is also trying to installed the latest SIFT version v1.6.1

**Comment by ekristen** [comment]
16.04 Ubuntu is the only supported OS. 18.04 is being worked on.
