### ISSUE TITLE
[CLI] Issues with updating

### ISSUE THREAD

**Issue by zappeee** [sans-dfir/sift#282]
From the log file:

```
>   file_|-sift-version-file_|-/etc/sift-version_|-managed:
>     __run_num__: 545
>     __sls__: sift.vm
>     changes: {}
>     comment: 'One or more requisite failed: sift.python-packages.sift-python-packages'
>     duration: 0.032
>     result: false
>     start_time: '07:50:02.088349'
> 
>   pip_|-sift-python-packages-machinae_|-machinae_|-installed:
>     __id__: sift-python-packages-machinae
>     __run_num__: 261
>     __sls__: sift.python-packages.machinae
>     changes: {}
>     comment: "Failed to install packages: machinae. Error: Collecting machinae\n  Downloading
>       https://files.pythonhosted.org/packages/e1/32/fcf173886cb51cbba843a9eb4e6550d71c8f5f9aefec08dc08359232e022/machinae-1.4.0.tar.gz\nCollecting
>       dnspython3 (from machinae)\n  Downloading https://files.pythonhosted.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip\n
>       \   Complete output from command python setup.py egg_info:\n    Traceback (most
>       recent call last):\n      File \"<string>\", line 1, in <module>\n      File
>       \"/tmp/pip-build-3Xcvvq/dnspython3/setup.py\", line 25\n        \"\"\"+\"=\"*78,
>       file=sys.stdout)\n                        ^\n    SyntaxError: invalid syntax\n
>       \   \n    ---------------------------------------- The directory '/home/sansforensics/.cache/pip/http'
>       or its parent directory is not owned by the current user and the cache has been
>       disabled. Please check the permissions and owner of that directory. If executing
>       pip with sudo, you may want sudo's -H flag.\nThe directory '/home/sansforensics/.cache/pip'
>       or its parent directory is not owned by the current user and caching wheels
>       has been disabled. check the permissions and owner of that directory. If executing
>       pip with sudo, you may want sudo's -H flag.\nCommand \"python setup.py egg_info\"
>       failed with error code 1 in /tmp/pip-build-3Xcvvq/dnspython3/\nYou are using
>       pip version 9.0.1, however version 10.0.1 is available.\nYou should consider
>       upgrading via the 'pip install --upgrade pip' command."
>     duration: 9539.937
>     name: machinae
>     result: false
>     start_time: '07:48:22.418053'
> 
>   test_|-sift-python-packages_|-sift-python-packages_|-nop:
>     __run_num__: 280
>     __sls__: sift.python-packages
>     changes: {}
>     comment: 'One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae'
>     duration: 0.034
>     result: false
>     start_time: '07:49:21.605613'
```

**Comment by zappeee** [comment]
Tried to Upgrade to 2018.26.1 and got the same, I think, issues.

`
>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 261
        Comment: Failed to install packages: machinae. Error: Collecting machinae
  Downloading https://files.pythonhosted.org/packages/e1/32/fcf173886cb51cbba843a9eb4e6550d71c8f5f9aefec08dc08359232e022/machinae-1.4.0.tar.gz
Collecting dnspython3 (from machinae)
  Downloading https://files.pythonhosted.org/packages/f0/bb/f41cbc8eaa807afb9d44418f092aa3e4acf0e4f42b439c49824348f1f45c/dnspython3-1.15.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QHzM6n/dnspython3/setup.py", line 25
        """+"="*78, file=sys.stdout)
                        ^
    SyntaxError: invalid syntax
    
    ---------------------------------------- The directory '/home/sansforensics/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sansforensics/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QHzM6n/dnspython3/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
      - ID: undefined
        SLS: sift.python-packages
        Run#: 280
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages
`

**Comment by zappeee** [comment]
I tried "pip3 install machinae" and it went successful.

Though still the same issues when trying upgrade.

Probably related to https://github.com/sans-dfir/sift/issues/285

**Comment by ekristen** [comment]
Looks like a bug with dnspython3

**Comment by crahan** [comment]
Could this be related to pip (Python2) trying to install dnspython3 (which is for Python3)? The version for Python2 is dnspython I believe.

**Comment by ekristen** [comment]
Could very well be. It’s the theory I’m working on right now.

**Comment by ekristen** [comment]
Closing in favor of one issue https://github.com/sans-dfir/sift/issues/287 for tracking.
