### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by jbutkus26** [sans-dfir/sift#286]
When attempting to upgrade my sift workstation with the "Sift upgrade" Command I receive the following error.  

>> Incomplete due to Failures -- Success: 528, Failure: 11

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: python3-pip
        SLS: sift.packages.python3-pip
        Run#: 207
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r3e620b07472a4ac2adafb876994cff18.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: undefined
        SLS: sift.packages
        Run#: 254
        Comment: One or more requisite failed: sift.packages.python3-pip.python3-pip
      - ID: undefined
        SLS: sift.python-packages.machinae
        Run#: 261
        Comment: One or more requisite failed: sift.packages.python3-pip.python3-pip
      - ID: rekall-symlink
        SLS: sift.python-packages.rekall
        Run#: 271
        Comment: File exists where the symlink /usr/local/bin/rekall should be
      - ID: undefined
        SLS: sift.python-packages
        Run#: 280
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae, sift.python-packages.rekall.rekall-symlink
      - ID: sift-scripts-regripper-plugins-symlink
        SLS: sift.scripts.regripper
        Run#: 400
        Comment: Directory exists where the symlink /usr/share/regripper/plugins should be
      - ID: undefined
        SLS: sift.scripts
        Run#: 432
        Comment: One or more requisite failed: sift.scripts.regripper.sift-scripts-regripper-plugins-symlink
      - ID: undefined
        SLS: sift.config.user.rekall
        Run#: 461
        Comment: One or more requisite failed: sift.python-packages.rekall.rekall-symlink
      - ID: undefined
        SLS: sift.config.user
        Run#: 482
        Comment: One or more requisite failed: sift.config.user.rekall.sift-config-user-rekall-rc
      - ID: undefined
        SLS: sift.config
        Run#: 537
        Comment: One or more requisite failed: sift.config.user.sift-config-user
[saltstack.log](https://github.com/sans-dfir/sift/files/2155402/saltstack.log)

**Comment by ekristen** [comment]
You’ll need to check your apt, it says there are held and broken packages so nothing else can continue. 

Erik

**Comment by jbutkus26** [comment]
Thanks! Not sure how I overlooked that.
