### ISSUE TITLE
SIFT Exits Non-Zero with SSL_ST_INIT (OpenSSL) Error

### ISSUE THREAD

**Issue by skonopka** [sans-dfir/sift#289]
I have installed Ubuntu in several environments (VM) and each time I run "sudo sift install" and first time it runs but with failures.  Subsequent "sudo sift install" wipes out saltstack.log from prior install and does not run with the following results.  Also cannot run upgrade or update as never finished.  The install ran with 11 failures initially and trying to rerun install to finish but cannot as seen below.  Again this is happening after initial run and then subsequent execution.

sift install
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

> downloading v2018.28.0
>> downloading sift-saltstack-v2018.28.0.tar.gz.asc
>> downloading sift-saltstack-v2018.28.0.tar.gz.sha256
>> downloading sift-saltstack-v2018.28.0.tar.gz.sha256.asc
>> downloading sift-saltstack-v2018.28.0.tar.gz
> validating file sift-saltstack-v2018.28.0.tar.gz
> validating signature for sift-saltstack-v2018.28.0.tar.gz.sha256
> extracting update sift-saltstack-v2018.28.0.tar.gz
> performing update v2018.28.0
>> Log file: /var/cache/sift/cli/v2018.28.0/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.update.on (/snapshot/Users/ekristen/Development/sift/sift-cli/sift-cli.js:520:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Here is latest: saltstack.log
head -100 /var/cache/sift/cli/v2018.28.0/saltstack.log
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 386, in salt_call
    import salt.cli.call
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 9, in <module>
    import salt.cli.caller
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 19, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 90, in <module>
    import salt.pillar
  File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 18, in <module>
    import salt.fileclient
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 29, in <module>
    import salt.utils.templates
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 31, in <module>
    import salt.utils.http
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 71, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

Attached is initial install saltstack.log.
[saltstack_20170712_1030a_test.log](https://github.com/sans-dfir/sift/files/2189699/saltstack_20170712_1030a_test.log)

**Comment by ekristen** [comment]
Try `pip install -U pyOpenSSL`

**Comment by skonopka** [comment]
Ran the command "pip install -U pyOpenSSL"and now "sift install" starts running without error.  I am now waiting for all installs to finish.  I am correct in running "sift install" again until no failures?  Also, is "sift install" correct command for ubuntu server w/o desktop?

**Comment by skonopka** [comment]
Sudo install ran to completion but still have failures.  What next?

`>> Incomplete due to Failures -- Success: 533, Failure: 6

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 473
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 487
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 488
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 489
        Comment: One or more requisite failed: sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-minimize-window
      - ID: undefined
        SLS: sift.config
        Run#: 544
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.config.sift-config
`

**Comment by ekristen** [comment]
I went ahead and hid your last comment so I can draw attention to the solution for now and you already opened another issue for the desktop aspects.

**Comment by skonopka** [comment]
Thanks.  I am opening another issue related to upgrading pip and it breaking sift install further.
