### ISSUE TITLE
Error upgrading from version 2018.22.0 to 2018.28.0

### ISSUE THREAD

**Issue by dwizel** [sans-dfir/sift#294]
>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-python-packages-machinae
        SLS: sift.python-packages.machinae
        Run#: 261
        Comment: Error installing 'machinae': Could not find a `pip` binary
      - ID: undefined
        SLS: sift.python-packages
        Run#: 280
        Comment: One or more requisite failed: sift.python-packages.machinae.sift-python-packages-machinae
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.python-packages.sift-python-packages

Please note that I am using the latest sift-cli to perform this upgrade.

**Comment by ekristen** [comment]
Please go download the latest release of the SIFT CLI and upgrade to it and then attempt upgrade.

**Comment by ekristen** [comment]
@dwizel any luck?

**Comment by dwizel** [comment]
Apologies ekristen, been swarmed at work and uni. I've tried to run an update again and still no luck. Is there a way to remove sift and re-install it again?. Still getting the same error.

**Comment by dwizel** [comment]
So I've been at this and I decided to go back to my first error which had to do with the pip installation. This helped me fix it with no errors. By gedeon8084

Ok. Problem solved!
In the forum, there was a post by @johnmccash, that gave the solution.
To summarize, after:
$ pip installpip==9.0.3
I performed:
apt-get install python3-pip --reinstall
That solved the problem for me.
