### ISSUE TITLE
Ubuntu v18.04

### ISSUE THREAD

**Issue by mikec0713** [sans-dfir/sift#295]
Is there a SIFT-WORKSTATION that works with Ubuntu version 18.04? I've been trying to install it through the CLI, it doesn't work. I tried using the ova but the un and pw doesn't work for that neither.

**Comment by ekristen** [comment]
18.04 is not yet supported.

What username and password are you using?

**Comment by mikec0713** [comment]
It was the sans forensics: forensics 

Michael Cofield

**Comment by ekristen** [comment]
user: `sansforensics`
pass: `forensics`
