### ISSUE TITLE
[CLI] Problem with Install 

### ISSUE THREAD

**Issue by magrossm** [sans-dfir/sift#297]
Dear Community, 

attached is the saltstack.log, seemingly I had some issues. What do I need to do since update with not be possible.

Thank you for any advice.
[saltstack.log](https://github.com/sans-dfir/sift/files/2260311/saltstack.log)

**Comment by magrossm** [comment]
@ekristen 

I researched and did that now. If I reinstall i get this 6 errors.

>> Incomplete due to Failures -- Success: 533, Failure: 6

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-scripts-virustotal-search-archive
        SLS: sift.scripts.virustotal-tools
        Run#: 434
        Comment: [Errno 1] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
      - ID: undefined
        SLS: sift.scripts.virustotal-tools
        Run#: 435
        Comment: One or more requisite failed: sift.scripts.virustotal-tools.sift-scripts-virustotal-search-archive
      - ID: sift-scripts-virustotal-submit-archive
        SLS: sift.scripts.virustotal-tools
        Run#: 436
        Comment: [Errno 1] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
      - ID: undefined
        SLS: sift.scripts.virustotal-tools
        Run#: 437
        Comment: One or more requisite failed: sift.scripts.virustotal-tools.sift-scripts-virustotal-submit-archive
      - ID: undefined
        SLS: sift.scripts
        Run#: 439
        Comment: One or more requisite failed: sift.scripts.virustotal-tools.sift-scripts-virustotal-search-archive, sift.scripts.virustotal-tools.sift-scripts-virustotal-submit-archive, sift.scripts.virustotal-tools.sift-scripts-virustotal-search-script, sift.scripts.virustotal-tools.sift-scripts-virustotal-submit-script
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.scripts.sift-scripts

**Comment by magrossm** [comment]
@ekristen 

i did a sift upgrade and it fixed the problem. Thx for the help on a sunday! 

I will enjoy the usage and respect for your work!

**Comment by ekristen** [comment]
Glad to be of service.
