### ISSUE TITLE
log2timeline-sift command missing

### ISSUE THREAD

**Issue by fligi7** [sans-dfir/sift#3]
When issuing "log2timeline-sift" command, it returns a "command not found" error. 

This is on the default install (unzip SIFT 3.0 to Virtual Machine directory, open Virtual machine, start it up, issue command in terminal).

**Comment by DrexxL** [comment]
Thanks for this guys! I've been meaning to write my feedback for a while now, but yes I concur with "fligi7" in using log2timeline.py for the processing of dd'ed images.

**Comment by ekristen** [comment]
@fligi7 I'll make note to update the documentation.

**Comment by ekristen** [comment]
Resolved https://github.com/sans-dfir/sift-docs/commit/f6581ecf98dba1e61014e9e054a8520823b0c030
