### ISSUE TITLE
sift errors whilst installing

### ISSUE THREAD

**Issue by rohitbhardwaj00** [sans-dfir/sift#301]
Have following errors:

>> Incomplete due to Failures -- Success: 527, Failure: 12

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-pdf-poster-dfir-threat-intel
        SLS: sift.config.user.pdfs
        Run#: 456
        Comment: Specified sha256 checksum for /home/ubuntu/Desktop/DFIR-Threat-Intel-Poster.pdf (c18b226d3d29f07136822bb5c555e8d71dae02ee4a0ba69c6a3588f95324481f) does not match actual checksum (e221bc427061602c29a1b1250ee76e3f3adb4aace5ff4f41e1d3918ad6d9abb4)
      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 473
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-theme-gtk
        SLS: sift.config.user.theme
        Run#: 476
        Comment: Command "gsettings set org.gnome.desktop.interface gtk-theme Arc" run
      - ID: sift-config-theme-icon
        SLS: sift.config.user.theme
        Run#: 477
        Comment: Command "gsettings set org.gnome.desktop.interface icon-theme Arc-Icons" run
      - ID: sift-config-unity-launcher-user
        SLS: sift.config.user.unity
        Run#: 484
        Comment: Command "gsettings set com.canonical.Unity.Launcher launcher-position Bottom" run
      - ID: sift-config-unity-disable-scopes
        SLS: sift.config.user.unity
        Run#: 485
        Comment: Command "gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"" run
      - ID: sift-config-unity-favorites
        SLS: sift.config.user.unity
        Run#: 486
        Comment: Command "gsettings set com.canonical.Unity.Launcher favorites "['application://gnome-terminal.desktop', 'application://firefox.desktop', 'application://org.gnome.Nautilus.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 487
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 488
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 489
        Comment: One or more requisite failed: sift.config.user.pdfs.sift-pdf-poster-dfir-threat-intel, sift.config.user.theme.sift-config-theme-icon, sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.unity.sift-config-unity-favorites, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-launcher-user, sift.config.user.unity.sift-config-unity-disable-scopes, sift.config.user.theme.sift-config-theme-gtk, sift.config.user.unity.sift-config-unity-minimize-window

**Comment by ekristen** [comment]
Looks like the PDF contents were updated. I'll cut a new version soon.
