### ISSUE TITLE
[CLI] - Readme update GPG command

### ISSUE THREAD

**Issue by VernMcC** [sans-dfir/sift#302]
Like the saltstack instructions, the gpg command needs to be updated in the readme to include the key url and port:

Import the PGP Key - gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94

I got failures trying to follow the instructions exactly, but modifying it like the way it was modified in the saltstack instructions allowed me to add the keys and follow the instructions.

**Comment by ekristen** [comment]
I'll take a look. I've had mixed results with all the various tweaks to the command. I don't know if it is a network problem or gpg just varying per system or what, but the original instructions still work just fine for me, so it's weird.

**Comment by VernMcC** [comment]
Myself and my TA both just hit the same thing with a fresh Ubuntu 16.04 so I thought it was worth posting the issue and noted the fix posted in the sift saltstack readme worked for us.

**Comment by ekristen** [comment]
I’ll definitely update it

**Comment by ekristen** [comment]
It seems that no matter what everyone experiences this command failing no matter what the method is. :/ I don't understand why one command works for someone and not for another and visa versa.
