### ISSUE TITLE
[CLI] Updating the OVA version

### ISSUE THREAD

**Issue by VernMcC** [sans-dfir/sift#303]
Updating the ova version SIFT with the sudo sift update command generates the following error:
sansforensics@siftworkstation -> ~ 
$ sudo sift update
> sift-cli@1.6.1-master.bde3e23
> sift-version: v2018.16.0

NOTICE: Fixing incorrect Saltstack configuration.
Installing and configuring Saltstack properly ...

Command failed: apt-get remove -y salt-minion salt-common
E: Held packages were changed and -y was used without --allow-change-held-packages.

Error: Command failed: apt-get remove -y salt-minion salt-common
E: Held packages were changed and -y was used without --allow-change-held-packages.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I found by manually executing:
sudo apt-get remove -y --allow-change-held-packages salt-minion salt-common

I was able to get the CLI tool to run update as expected.

**Comment by VernMcC** [comment]
I had to do this whether upgrading or updating using the sift command line tool the first time on a new import of the OVA.

**Comment by ekristen** [comment]
Please upgrade to the latest sift cli tool manually. It’ll fix that error

**Comment by VernMcC** [comment]
TY

**Comment by ekristen** [comment]
@VernMcC as always if you have any more issues please feel free to reach out. I'll be pushing some more updates to the CLI tool to help with self-update, overriding certain settings and the like in the near future.
