### ISSUE TITLE
[cli] Incomplete due to Failures -- Success: 486, Failure: 53

### ISSUE THREAD

**Issue by jacobiusg** [sans-dfir/sift#304]
I have re-run this install once already, updated all my packages, updated pip as it seemed to be a problem but no luck. Any assistance would be helpful.

[output_sift_update.txt](https://github.com/sans-dfir/sift/files/2330581/output_sift_update.txt)
[saltstack_errors.txt](https://github.com/sans-dfir/sift/files/2330573/saltstack_errors.txt)

**Comment by ekristen** [comment]
The first log indicates updates aren’t allowed if an install hasn’t been successful.

The second log indicates there is something wrong with your python install. As I’m unable to reproduce this locally it’s hard for me to troubleshoot.

Can you seen if python is installed? Can you run python -v

**Comment by jacobiusg** [comment]
$ python --version
Python 2.7.12
silence@siftworkstation -> ~ 
$ python -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
import _locale # builtin
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so", 2);
import readline # dynamically loaded from /usr/lib/python2.7/lib-dynload/readline.x86_64-linux-gnu.so

**Comment by jacobiusg** [comment]
[python_output.txt](https://github.com/sans-dfir/sift/files/2330640/python_output.txt)

**Comment by ekristen** [comment]
What version of pip is installed

**Comment by jacobiusg** [comment]
v 9.01

**Comment by ekristen** [comment]
salt-call —versions-report

**Comment by jacobiusg** [comment]
[saltcall.txt](https://github.com/sans-dfir/sift/files/2332295/saltcall.txt)

**Comment by ekristen** [comment]
Try running, you might need to alter the file-root, I'm going from memory at the moment, but I think that path is right.

```salt-call --local --file-root=/var/cache/sift/cli/v2018.28.0 state.sls sift.python-packages.colorama```

**Comment by jacobiusg** [comment]
path was right i double checked

[state.txt](https://github.com/sans-dfir/sift/files/2332475/state.txt)

**Comment by ekristen** [comment]
Try ..

```
salt-call --local --file-root=/var/cache/sift/cli/v2018.28.0/sift-saltstack-2018.28.0 state.sls sift.python-packages.colorama
```
If that doesn't work look for the subfolder that has the sift folder in it.

**Comment by jacobiusg** [comment]
Still seems to be a problem with pip.. I may just attempt to re-install python and pip see if that works

[salt_state.txt](https://github.com/sans-dfir/sift/files/2332575/salt_state.txt)

**Comment by ekristen** [comment]
Add `-l debug` to the command.

**Comment by jacobiusg** [comment]
[salt_debug.txt](https://github.com/sans-dfir/sift/files/2332647/salt_debug.txt)

**Comment by ekristen** [comment]
Try installing pip 9.0.3 if that doesn't work let me know. It looks like this might have been a bug in salt-stack, but according to everything it shouldn't behaving this way, but we can try upgrading salt-stack next (without using the sift-cli) to see if we can't get it working.

**Comment by jacobiusg** [comment]
unfortunately it's still not working.

**Comment by ekristen** [comment]
You can try and update to 2017.7.6, `apt-get install sift-minion=2017.7.6` and then retry re-running the command.

**Comment by davidep** [comment]
same issue here, @ekristen was the above supposed to be `apt-get install **salt**-minion=2017.7.6`  ?
if so, isn't salt-minion=2017.7.5+ds-1 the newest version?

**Comment by ekristen** [comment]
I didn’t check the exact version syntax but 2017.7.6 was released end of May. Actually 2017.7.7 is our try installing that.

**Comment by Folii** [comment]
Having the same issues.

Installing sift on a fresh VM through virtual box running Ubuntu Desktop 16.04.5. Installing it on a VM shouldn't effect anything?

I have been randomly selecting older versions and trying to install them.

When I installed v2018.26.0 

> Completed with Failures -- Success: 534, Failure: 5

Reinstalling v2018.28.0, but it does not list what failed below.

> Completed with Failures -- Success: 534, Failure: 5

I had been previously getting Success: 486, Failure: 53 before trying older versions.

**Comment by ekristen** [comment]
Logs would help to determine what’s broken.

**Comment by davidep** [comment]
my issue with salt-minion version was an hardcoded pointer to 2017.7.5 in source.list, 
I changed that to latest, ran again sift upgrade, this time it ended with only 3 failed, (mainly only sift-python-package-machinae) "could not find a `pip` binary"

checking the /etc/apt/sources.list.d/saltstack.list now it is back to "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2017.7.5 xenial main" so I guess that hardcoded version comes from the sift-cli script

**Comment by ekristen** [comment]
@Folii you are 99% installed, I need to push an update to account for that poster as it's contents changed. SIFT doens't think it's installed because it wants 100% of everything to work, but you are there. Just so you know the CLI helper doesn't roll back anything in the face of failure so all the tools and such are installed.

@davidep welcome to the wonderful world of python breaking. As you can see @Folii managed to not get any python errors, but you are. The CLI is hardcoded but I will be adding an option to allow people to override it. If you got edit the source list and change the 2017.7.5 to 2017.7.7 and upgrade the salt-minion using apt, then run salt manually like 

```
salt-call --local --file-root=/var/cache/sift/cli/v2018.28.0/sift-saltstack-2018.28.0 state.sls sift.python-packages.machinae
```

We can see if that fixes the issue.

**Comment by toastr** [comment]
I had similar issues with updating/upgrading on a fresh VM for FOR508 which an updated copy was provided on 7/16/18. I have the VM snapshotted so I can easily roll back.
> sift-cli@1.5.1-beta.0-master.154cb2f
> sift-version: v2017.27.0
updating the current version (2017.27.0) presents errors as does upgrading to v2018.28.0
Attached is a log for

`salt-call --local --file-root=/var/cache/sift/cli/v2018.28.0/sift-saltstack-2018.28.0 state.sls sift.packages`

[salt-call.log](https://github.com/sans-dfir/sift/files/2341397/salt-call.log)

when i issue and apt-get -f install a number of issues are resolved. After running the same salt-call command again the number of issues drops down to 5 with them revolving around python-dfvfs, python-plaso, and python3-pip

> The following packages have unmet dependencies:
>  python3-pip : Depends: python-pip-whl (= 8.1.1-2) but 8.1.1-2ubuntu0.4 is to be installed
>                Recommends: python3-dev (>= 3.2) but it is not going to be installed
>                Recommends: python3-setuptools but it is not going to be installed
>                Recommends: python3-wheel but it is not going to be installed

> [ERROR   ] Command '['systemd-run', '--scope', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'python-dfvfs=latest']' failed with return code: 100
> [ERROR   ] stdout: Reading package lists...
> Building dependency tree...
> Reading state information...
> [ERROR   ] stderr: Running scope as unit run-r995c5fcb31a54a8e96302b552e948518.scope.
> E: Version 'latest' for 'python-dfvfs' was not found
> [ERROR   ] retcode: 100
> [ERROR   ] Problem encountered installing package(s). Additional info follows:
> 
> errors:
>     - Running scope as unit run-r995c5fcb31a54a8e96302b552e948518.scope.
>       E: Version 'latest' for 'python-dfvfs' was not found
> 

No apt-get update or upgrades have been run on this vm.

**Comment by VernMcC** [comment]
When I install with 

> --mode=packages-only

`sudo sift install --mode=packages-only --user=${currentUser}`

 I am not getting any errors and the tools I need work just fine.
