### ISSUE TITLE
siftworkstation always on in terminal

### ISSUE THREAD

**Issue by Arconapalus** [sans-dfir/sift#306]
I have a problem with sift-workstation always being used while in terminal. For instance, I see my username@siftworkstation in terminal and can't update or upgrade Ubuntu distro. I have installed sift-cli using salt, sudo -s to install files but now I think that the siftworkstation is the new home dir that I'm currently logged in as. This is on my Ubuntu desktop and not a VM, and would like to only use sift when need be. How could I logout or uninstall to fix this problem. I could install it on VM for alternative measure. 
I search Github and Google for answers and nothing related to this, has shown what to do.

**Comment by ekristen** [comment]
Hi Paul, I’m not really sure what you are trying to get at here.

The sift cli doesn’t get installed with salt, the cli comes first.

You probably want to use the packages-only mode with the cli so that it doesn’t interfere with your user setup.

Erik

**Comment by Arconapalus** [comment]
I'll clarify, the siftworkstation is the hostname when I login. Preventing me from executing commands and updates. I would I change the hostname from siftworkstation back to ubuntu? 
Sorry for the confusion, lost in vocabulary to explain my problem.
