### ISSUE TITLE
I am new and I want to update SIFT

### ISSUE THREAD

**Issue by Alghamdi12** [sans-dfir/sift#307]
I am new to linux and I want to update SIFT to last version, I used the following command but did not work.
Please can you help me...
wget –quiet -O -https://raw.github.com/sans-dfir/sift-bootstrsp/master/bootstrsp.sh | sudo bash -s — -i -s -y

Thank you

**Comment by ekristen** [comment]
Please see the updated instructions, https://github.com/sans-dfir/sift-cli
