### ISSUE TITLE
SIFT install on Ubuntu 18.04.1 LTS Incomplete due to Failures

### ISSUE THREAD

**Issue by qiMakur** [sans-dfir/sift#312]
I'm trying to install SIFT on Ubuntu 18.04.1 LTS and getting the following results. 
--------------------------------------
>> Incomplete due to Failures -- Success: 199, Failure: 82

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: python-software-properties
        SLS: sift.packages.python-software-properties
        Run#: 0
        Comment: Problem encountered installing package(s). Additional info follows:
--------------------------------------
It appears the failure is due to python-software-properties so I tried to find and install this package manually and found...
--------------------------------------
$ apt-get install python-software-properties
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-software-properties is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  software-properties-common

E: Package 'python-software-properties' has no installation candidate
--------------------------------------
When I tried to install the replacement (software-properties-common), I got...
--------------------------------------
$ apt-get install software-properties-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.24.32.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
---------------------------------------
Is there something I can do to work around these errors and package changes or is this something that needs to be fixed on the SIFT package end of things?

**Comment by ekristen** [comment]
18.04 is not yet supported.

**Comment by qiMakur** [comment]
any idea when it will be?

**Comment by jma4227** [comment]
I'm having the same issues with 18.04. I am going to try to use an earlier version of ubuntu. I did re read the instructions and it does state to download ubuntu 16.04

**Comment by ekristen** [comment]
18.04 is still not supported 100%.

**Comment by DataLoreSpecialist** [comment]
When can we expect 18.04 to be supported?

**Comment by ekristen** [comment]
Beta is up. Instructions are at https://github.com/teamdfir/sift-saltstack
