### ISSUE TITLE
SIFT Install incomplete on Ubuntu 16.04

### ISSUE THREAD

**Issue by gatopardos90** [sans-dfir/sift#313]
>> Incomplete due to Failures -- Success: 529, Failure: 11

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 474
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-theme-gtk
        SLS: sift.config.user.theme
        Run#: 477
        Comment: Command "gsettings set org.gnome.desktop.interface gtk-theme Arc" run
      - ID: sift-config-theme-icon
        SLS: sift.config.user.theme
        Run#: 478
        Comment: Command "gsettings set org.gnome.desktop.interface icon-theme Arc-Icons" run
      - ID: sift-config-unity-launcher-user
        SLS: sift.config.user.unity
        Run#: 485
        Comment: Command "gsettings set com.canonical.Unity.Launcher launcher-position Bottom" run
      - ID: sift-config-unity-disable-scopes
        SLS: sift.config.user.unity
        Run#: 486
        Comment: Command "gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"" run
      - ID: sift-config-unity-favorites
        SLS: sift.config.user.unity
        Run#: 487
        Comment: Command "gsettings set com.canonical.Unity.Launcher favorites "['application://gnome-terminal.desktop', 'application://firefox.desktop', 'application://org.gnome.Nautilus.desktop', 'application://unity-control-center.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']"" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 488
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 489
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 490
        Comment: One or more requisite failed: sift.config.user.theme.sift-config-theme-icon, sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.unity.sift-config-unity-favorites, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-launcher-user, sift.config.user.unity.sift-config-unity-disable-scopes, sift.config.user.theme.sift-config-theme-gtk, sift.config.user.unity.sift-config-unity-minimize-window
      - ID: undefined
        SLS: sift.config
        Run#: 547
        Comment: One or more requisite failed: sift.config.user.sift-config-user

**Comment by WhistleMaster** [comment]
Same issue here:

```
>> Incomplete due to Failures -- Success: 533, Failure: 6

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 473
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run
      - ID: sift-config-unity-icon-size
        SLS: sift.config.user.unity
        Run#: 487
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/icon-size 32" run
      - ID: sift-config-unity-minimize-window
        SLS: sift.config.user.unity
        Run#: 488
        Comment: Command "dconf write /org/compiz/profiles/unity/plugins/unityshell/launcher-minimize-window true" run
      - ID: undefined
        SLS: sift.config.user
        Run#: 489
        Comment: One or more requisite failed: sift.config.user.unity.sift-config-unity-icon-size, sift.config.user.terminal.sift-config-terminal-profiles-install, sift.config.user.unity.sift-config-unity-minimize-window
      - ID: undefined
        SLS: sift.config
        Run#: 544
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.vm
        Run#: 545
        Comment: One or more requisite failed: sift.config.sift-config
```

**Comment by ekristen** [comment]
@answer-hub please make sure you are using `sudo sift install`

There is a log file associated with the install attempt, it's path is in the output when you run the command. Can you please locate and upload for review.

**Comment by answer-hub** [comment]
[Ubuntu16.txt](https://github.com/sans-dfir/sift/files/2479946/Ubuntu16.txt)
There is some garbage in log..Sorry

**Comment by ekristen** [comment]
@answer-hub that's not what I was asking for. When you run sift install there's a log file path that's output. I need the contents of that.

**Comment by answer-hub** [comment]
Sorry. Whats the correct path if its not?
[saltstack.log](https://github.com/sans-dfir/sift/files/2480022/saltstack.log)
