### ISSUE TITLE
SIFT installation is failing in Linux Mint 19 (Please add support for Mint)

### ISSUE THREAD

**Issue by ruchirarya** [sans-dfir/sift#314]
>> Incomplete due to Failures -- Success: 189, Failure: 92

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-docker-repo
        SLS: sift.repos.docker
        Run#: 2
        Comment: Failed to configure repo 'deb https://apt.dockerproject.org/repo ubuntu-tara main': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
      - ID: sift-gift-repo
        SLS: sift.repos.gift
        Run#: 4
        Comment: Failed to configure repo 'gift': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
      - ID: sift-repo
        SLS: sift.repos.sift
        Run#: 6
        Comment: Failed to configure repo 'sift-repo': Unable to add PPA 'sift/stable'. '['apt-add-repository', '-y', 'ppa:sift/stable']' exited with status 1: '' 
      - ID: sift-repo-noobslab-themes
        SLS: sift.repos.noobslab
        Run#: 8
        Comment: Failed to configure repo 'noobslab-themes': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
      - ID: sift-repo-noobslab-icons
        SLS: sift.repos.noobslab
        Run#: 9
        Comment: Failed to configure repo 'noobslab-icons': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
      - ID: openjdk-repo
        SLS: sift.repos.openjdk
        Run#: 10
        Comment: Failed to configure repo 'openjdk-repo': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
      - ID: sift-multiverse-repo
        SLS: sift.repos.ubuntu-multiverse
        Run#: 11
        Comment: Failed to configure repo 'deb http://archive.ubuntu.com/ubuntu/ tara multiverse': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
E: The repository 'http://archive.ubuntu.com/ubuntu tara Release' does not have a Release file.
      - ID: sift-multiverse-repo-security
        SLS: sift.repos.ubuntu-multiverse
        Run#: 12
        Comment: Failed to configure repo 'deb http://archive.ubuntu.com/ubuntu/ tara-security multiverse': E: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-tara/InRelease  403  Forbidden [IP: 143.204.146.108 443]
E: The repository 'https://apt.dockerproject.org/repo ubuntu-tara InRelease' is not signed.
E: The repository 'http://archive.ubuntu.com/ubuntu tara Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu tara-security Release' does not have a Release file.
      - ID: undefined
        SLS: sift.repos
        Run#: 14
        Comment: The following requisites were not found:
                   require:
                       sls: sift.repos.ubuntu-universe

      - ID: afterglow
        SLS: sift.packages.afterglow
        Run#: 19
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r6ab2b0f9c9fa4c188b343c0bb655a739.scope
      E: Unable to locate package afterglow

**Comment by ekristen** [comment]
Ubuntu 16.04 is the only OS supported at this time. Efforts to support 18.04 are underway. There are no plans to support any other OS at this time.
