### ISSUE TITLE
Plugins problem -'ImportError: No module named'

### ISSUE THREAD

**Issue by mathurin68** [sans-dfir/sift#316]
Just getting started working with Volatility and these plugins look super interesting...  trying to add them to my volatility_plugins directory but when I run them I seem to get the following errors 

`python2 vol.py --plugins=/mnt/c/Users/money/Documents/volatility/volatility_plugins -f memdump --profile=Win2012R2x64_18340 pstotal`

*** Failed to import volatility.plugins.openioc_scan (ImportError: No module named ioc_writer)
*** Failed to import volatility.plugins.mimikatz (ImportError: No module named construct)

Even if I 'pip install ioc_writer' it sill seems to have problems.  

Any suggestions?  Or is there an even better list of plugins for volatility I could play around with?  Thanks!

**Comment by mathurin68** [comment]
Never mind forgot I python2 and python3 on here - let that be a lesson to you kids!!!

**Comment by ekristen** [comment]
@mathurin68 great! glad you got it working!
