### ISSUE TITLE
Disable auto-login and lightdm breaks?

### ISSUE THREAD

**Issue by cgisecurity** [sans-dfir/sift#318]
Using the .ova file and ESXi setup. Deploy .ova, update image, make sure it can reach internal smb share with correct creds, and then go to user settings and disable autologin. After rebooting, lightdm doesn't start and you're presented with CLI. Login using default creds and try to use startx and it errors out trying to lock the file. Try rebooting, still get CLI. Login using default creds, run sudo systemctl enable lightdm, reboot, and get GUI login with SANSFORENSICS as user name and asking for password. When I type the password, it acts like it wants to login but then displays login screen again. Entering a wrong password displays as a wrong password. Any ideas? I can redeploy .ova and try disabling auto-login another way if that's easier than fixing this issue, but I've reproduced this twice now.

**Comment by ekristen** [comment]
Sounds like a permissions issue. I’ve seen the behavior before but haven’t been able reproduce it.

**Comment by cgisecurity** [comment]
Fixed.

**Comment by ekristen** [comment]
What was the fix?

**Comment by cgisecurity** [comment]
Disable auto login first and then reboot the machine before doing anything
else.

Not really a fix, just didn't break it on my third try. It seems to happen
when you disable auto login, set a static ip, and change host name before
rebooting.
