### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by OGSnoop** [sans-dfir/sift#321]
I am a new user to sift and was coming across this issue through installation both on Ubuntu 16.04 and 18.04.  Currently I am booting Ubuntu from a live-usb, could that be the issue, otherwise I am going to try out the ova.

me:/$ sudo sift install
sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Unable to correct problems, you have held broken packages.

Error: Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Unable to correct problems, you have held broken packages.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)

I have tried going through and obtaining multiple other package requirements for salt-minion and salt-common, but with no succes of installation.  I have also tried to figure out what packages are broken with zero display from dpkg -l | grep ..^r
I no longer have any other ideas on what I am doing wrong and any sense of direction would be appreciated.

**Comment by ekristen** [comment]
Sounds like your apt is broken. Try installing something like `apt-get install curl` to see if there's a problem and try to correct it.

**Comment by OGSnoop** [comment]
Cool, thanks for the insight.
