### ISSUE TITLE
Installation issues in ubuntu 16.04

### ISSUE THREAD

**Issue by leaenbinario** [sans-dfir/sift#322]
Hi,
I'm trying to install sift in my ubuntu but i have some problems.

I downloaded
    sift-cli-linux
    sift-cli-linux.sha256.asc
and
**curl -Lo /usr/local/bin/sift https://github.com/sans-dfir/sift-cli/releases/download/v1.7.1/sift-cli-linux
chmod +x /usr/local/bin/sift**

It's ok but when I tried to do import key I get errors
**gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94**
gpg: requesting key 22598A94 from hkp server pgp.mit.edu
gpgkeys: key 22598A94 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm

**sudo sift install**
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get update
W: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
W: https://minergate.com/repo/deb/dists/stable/InRelease: Signature by key 33BDA78F1D398B52D01438F603F0D99C2EC4C39D uses weak digest algorithm (SHA1)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/binary-amd64/Packages  404  Not Found [IP: 2001:67c:1562::16 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

Error: Command failed: apt-get update
W: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
W: https://minergate.com/repo/deb/dists/stable/InRelease: Signature by key 33BDA78F1D398B52D01438F603F0D99C2EC4C39D uses weak digest algorithm (SHA1)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/binary-amd64/Packages  404  Not Found [IP: 2001:67c:1562::16 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)

But
**sift -v**
Version: 1.7.1, Build: master-f1177e4

and If I tried to do
**sudo sift update**
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get update
W: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
W: https://minergate.com/repo/deb/dists/stable/InRelease: Signature by key 33BDA78F1D398B52D01438F603F0D99C2EC4C39D uses weak digest algorithm (SHA1)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/binary-amd64/Packages  404  Not Found [IP: 2001:67c:1560:8001::14 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

Error: Command failed: apt-get update
W: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
W: https://minergate.com/repo/deb/dists/stable/InRelease: Signature by key 33BDA78F1D398B52D01438F603F0D99C2EC4C39D uses weak digest algorithm (SHA1)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/binary-amd64/Packages  404  Not Found [IP: 2001:67c:1560:8001::14 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by ekristen** [comment]
Zesty is not supported.
