### ISSUE TITLE
[CLI] - Key Server Issue

### ISSUE THREAD

**Issue by SaintHeimFyrstr** [sans-dfir/sift#326]
I don't know if this is going to be a long term issue, but just trying to do a fresh build of SIFT using the instructions on the CLI page and the key server listed there (pgp.mit.edu) is really tempremental. 

Anyway, to cut a long story short, according to an article from March 2017, this seems to be a common occurrence ([https://github.com/nginxinc/docker-nginx/issues/156](https://github.com/nginxinc/docker-nginx/issues/156)) .

As per that article, may I suggest that you change the instructions to reference the pool of PGP servers rather than just the MIT one specifically. This would mean that installation instruction three would read:

3. Import the PGP Key - `gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 22598A94`

I understand that there may be a valid reason for solely referencing the MIT server, but for those who have also been experiencing this issue, I have tested this successfully and can now continue with the build.

![sift_cli_keyserver_issue](https://user-images.githubusercontent.com/44983181/48373614-3dcdc080-e6ba-11e8-9cfa-9e1cece644df.PNG)

If you are wanting to stick with a single server, maybe the Ubuntu one might be more stable, in which case:

3. Import the PGP Key - `gpg --keyserver hkp://keyserver.ubuntu.com:11371 --recv-keys 22598A94`

Kind regards

Gavin

[Information on the different types of SKS pools](https://sks-keyservers.net/overview-of-pools.php)
[SKS pool server status page](https://sks-keyservers.net/status/)

P.S. Just for clarification, I have no affiliation with the SKS setup at all :-)

**Comment by ekristen** [comment]
@SaintHeimFyrstr what type of network are you on? IPv4 or IPv6?

**Comment by SimonSK** [comment]
I'm on IPv4, and I was able to import the key from `hkp://keyserver.ubuntu.com:11371`, but not from `hkp://pgp.mit.edu:80` and `hkp://pool.sks-keyservers.net`.
```
~$ date -u
Tue Mar 26 10:41:21 UTC 2019
~$ gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94
gpg: keyserver receive failed: No data
~$ gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 22598A94
gpg: keyserver receive failed: No data
~$ gpg --keyserver hkp://keyserver.ubuntu.com:11371 --recv-keys 22598A94
gpg: /home/<username>/.gnupg/trustdb.gpg: trustdb created
gpg: key 15B9AD7122598A94: public key "SANS Investigative Forensic Toolkit <sift@computer-forensics.sans.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
