### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by socengsoc** [sans-dfir/sift#334]
Hello
i have installed fresh version of Ubuntu and follow all instruction of SIFT installation .   i typed the command apt-get update and it's  complete successful 

i have face the following error   , is that  connection  issue   ?  

`lab@lab:~$ sudo sift install
[sudo] password for lab: 
> sift-cli@1.7.1-master.f1177e4
> sift-version: notinstalled

Installing and configuring SaltStack properly ...

Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-stdlib_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-minimal_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7-minimal_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/p/python-defaults/python-minimal_2.7.15~rc1-1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/p/python-defaults/libpython-stdlib_2.7.15~rc1-1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/p/python-defaults/python_2.7.15~rc1-1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/u/underscore/libjs-underscore_1.8.3~dfsg-1_all.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/universe/libp/libpgm/libpgm-5.2-0_5.2.122~dfsg-2_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2017.7.5/pool/main/s/salt/salt-common_2017.7.5+ds-1_all.deb  Connection failed [IP: 138.197.226.47 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

Error: Command failed: apt-get install -y --allow-change-held-packages salt-minion
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-stdlib_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/libpython2.7-minimal_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7-minimal_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/p/python-defaults/python-minimal_2.7.15~rc1-1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/python2.7/python2.7_2.7.15~rc1-1ubuntu0.1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/p/python-defaults/libpython-stdlib_2.7.15~rc1-1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/p/python-defaults/python_2.7.15~rc1-1_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/main/u/underscore/libjs-underscore_1.8.3~dfsg-1_all.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://ye.archive.ubuntu.com/ubuntu/pool/universe/libp/libpgm/libpgm-5.2-0_5.2.122~dfsg-2_amd64.deb  403  Forbidden [IP: 91.189.88.162 80]
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2017.7.5/pool/main/s/salt/salt-common_2017.7.5+ds-1_all.deb  Connection failed [IP: 138.197.226.47 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by ekristen** [comment]
Sounds like an issue with your network.
