### ISSUE TITLE
Checksum Poster issue in OVA build

### ISSUE THREAD

**Issue by MMULLINIX1** [sans-dfir/sift#336]
Erik, just wanted to let you know the following errors occurred with a new OVA install of SIFT.

It had issues with the SIFT Wine update - took long time, fix was to run command sudo apt-get -f install and it fixed all but 4 errors. The 4 errors were related to the SHA-256 checksum for the PDF cheatsheets.

Run#: 461
        Comment: Specified sha256 checksum for https://digital-forensics.sans.org/media/DFIR-Smartphone-Forensics-Poster.pdf (156ff07624c4a40a01b4a89174e083ff90af15353699805bc646d22e946b7e4f) does not match actual checksum (1b2d79a2abb9d2122f77e682a61bc5b85ae2e5f58e846c49424080226e50d393). If the 'source_hash' value refers to a remote file with multiple possible matches, then it may be necessary to set 'source_hash_name'.
      - ID: undefined
        SLS: sift.config.user
        Run#: 490
        Comment: One or more requisite failed: sift.config.user.pdfs.sift-pdf-poster-dfir-smartphone
      - ID: undefined
        SLS: sift.config
        Run#: 545
        Comment: One or more requisite failed: sift.config.user.sift-config-user
      - ID: undefined
        SLS: sift.vm
        Run#: 546
        Comment: One or more requisite failed: sift.config.sift-config, sift.packages.sift-packages

**Comment by ekristen** [comment]
Must have just changed. I did a full install last night without error.

I’ll update.

**Comment by ekristen** [comment]
It's already updated in the latest version of the SIFT configs, but it would be a mismatch on the OVA, you'd need to upgrade to get the latest configs to resolve this.
