### ISSUE TITLE
Got these errors running "sift install"

### ISSUE THREAD

**Issue by fadagost** [sans-dfir/sift#338]
>> Incomplete due to Failures -- Success: 445, Failure: 93

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: python-software-properties
        SLS: sift.packages.python-software-properties
        Run#: 0
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-r0d1cd958ef8d4778bd0cffb67e96cf53.scope
      E: Package 'python-software-properties' has no installation candidate
      - ID: undefined
        SLS: sift.repos.docker
        Run#: 2
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.gift
        Run#: 4
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.sift
        Run#: 6
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos.openjdk
        Run#: 10
        Comment: One or more requisite failed: sift.packages.python-software-properties.python-software-properties
      - ID: undefined
        SLS: sift.repos
        Run#: 14
        Comment: The following requisites were not found:
                   require:
                       sls: sift.repos.ubuntu-universe

      - ID: afterglow
        SLS: sift.packages.afterglow
        Run#: 19
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit: run-ra8a0568d2b55409a999dd47b0925ad74.scope
      E: Unable to locate package afterglow
      - ID: undefined
        SLS: sift.packages.bitpim
        Run#: 25
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bitpim-lib
        Run#: 26
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bulk-extractor
        Run#: 31
        Comment: One or more requisite failed: sift.repos.sift.sift-repo, sift.repos.openjdk.openjdk-repo

**Comment by ekristen** [comment]
I'll need the full logs of the cli, should be in your home directory.
