### ISSUE TITLE
Failed to configure repo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main

### ISSUE THREAD

**Issue by rgsec** [sans-dfir/sift#339]
>> Incomplete due to Failures -- Success: 344, Failure: 196

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-docker-repo
        SLS: sift.repos.docker
        Run#: 2
        Comment: Failed to configure repo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main': Error: key retrieval failed: Executing: /tmp/tmp.SBBO009QuC/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--logger-fd
1
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
      - ID: undefined
        SLS: sift.repos
        Run#: 15
        Comment: One or more requisite failed: sift.repos.docker.sift-docker-repo
      - ID: autopsy
        SLS: sift.packages.autopsy
        Run#: 24
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-reae25fc5739e4a23a3f36737114c6972.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: undefined
        SLS: sift.packages.docker-engine
        Run#: 44
        Comment: One or more requisite failed: sift.repos.docker.sift-docker-repo
      - ID: ettercap-graphical
        SLS: sift.packages.ettercap-graphical
        Run#: 52
        Comment: Problem encountered installing package(s). Additional info follows:

**Comment by ekristen** [comment]
Without more, sounds like a networking problem. If you can provide logs that show otherwise please do so.

**Comment by rgsec** [comment]
>> Incomplete due to Failures -- Success: 344, Failure: 196

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-docker-repo
        SLS: sift.repos.docker
        Run#: 2
        Comment: Failed to configure repo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main': Error: key retrieval failed: Executing: /tmp/tmp.SBBO009QuC/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--logger-fd
1
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D can't be retrieved
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
      - ID: undefined
        SLS: sift.repos
        Run#: 15
        Comment: One or more requisite failed: sift.repos.docker.sift-docker-repo
      - ID: autopsy
        SLS: sift.packages.autopsy
        Run#: 24
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-reae25fc5739e4a23a3f36737114c6972.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: undefined
        SLS: sift.packages.docker-engine
        Run#: 44
        Comment: One or more requisite failed: sift.repos.docker.sift-docker-repo
      - ID: ettercap-graphical
        SLS: sift.packages.ettercap-graphical
        Run#: 52
        Comment: Problem encountered installing package(s). Additional info follows:

**Comment by rgsec** [comment]
I tried to install it on AWS instance, then it is giving this error.

**Comment by rgsec** [comment]
Just to give some reference, At the start of installation also at the import PGP key step. It was failing with similar error for following command:

Import the PGP Key - gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 22598A94

But when I removed **hkp://** prefix and port **80** from the keyserver path and it imported the PGP key fine:

Import the PGP Key - gpg --keyserver pgp.mit.edu --recv-keys 22598A94

But as the installation progresses, I am not finding anyway to modify the similar command line for pgp key for dockerproject.

**Comment by ekristen** [comment]
This is an ongoing discussion between a lot of people. With our without hkp and port 80 works for some, others require it. Why, I am not sure yet. The installation process handles pulling the key, you can try and install it manually head of time though and retry.

**Comment by rgsec** [comment]
I tried pulling the key manually ahead of time. Now it is failing with below error:

>> Incomplete due to Failures -- Success: 346, Failure: 194

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: autopsy
        SLS: sift.packages.autopsy
        Run#: 24
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-rea89978268f4465e926ebe954c7875b7.scope.
      E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
      - ID: docker-engine
        SLS: sift.packages.docker-engine
        Run#: 44
        Comment: Problem encountered installing package(s). Additional info follows:

**Comment by ekristen** [comment]
This is an known issue that I'm attempting to reproduce to troubleshoot. See https://github.com/sans-dfir/sift/issues/337

**Comment by Cl0nex** [comment]
I'm new to sfit. 
Trying to get SIFT runnning on a t2.large EC2 instance.

I'm using CIS Ubuntu Linux 16.04 LTS Benchmark v1.0.0.6 - Level 1-2ba49cfb-babd-43d3-81f6-3657aeb0f101-ami-015ce07051469d4ab.4 - ami-0f335ce28b726f993
SSD Volume Type: gp2
Size: 80 GiB

Errored out the last three times as follows:

> Incomplete due to Failures -- Success: 522, Failure: 20

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-docker-repo
        SLS: sift.repos.docker
        Run#: 2
        Comment: Failed to configure repo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main': Error: key retrieval failed: Executing: /tmp/tmp.nXADsIqK1p/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--logger-fd
1
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
      - ID: openjdk-repo
        SLS: sift.repos.openjdk
        Run#: 12
        Comment: Failed to configure repo 'openjdk-repo': Unable to add PPA 'openjdk-r/ppa'. '['apt-add-repository', '-y', 'ppa:openjdk-r/ppa']' exited with status 1: 'gpg: keyring `/tmp/tmpoatz0coe/secring.gpg' created
gpg: keyring `/tmp/tmpoatz0coe/pubring.gpg' created
gpg: requesting key 86F44E2A from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpoatz0coe/trustdb.gpg: trustdb created
gpg: key 86F44E2A: public key "Launchpad OpenJDK builds (all archs)" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)'
      - ID: undefined
        SLS: sift.repos
        Run#: 17
        Comment: One or more requisite failed: sift.repos.docker.sift-docker-repo, sift.repos.openjdk.openjdk-repo
      - ID: undefined
        SLS: sift.packages.bulk-extractor
        Run#: 34
        Comment: One or more requisite failed: sift.repos.openjdk.openjdk-repo
      - ID: undefined
        SLS: sift.packages.docker-engine
        Run#: 46
        Comment: One or more requisite failed: sift.repos.docker.sift-docker-repo
      - ID: undefined
        SLS: sift.packages.openjdk
        Run#: 139
        Comment: One or more requisite failed: sift.repos.openjdk.openjdk-repo
      - ID: undefined
        SLS: sift.packages
        Run#: 257
        Comment: One or more requisite failed: sift.packages.bulk-extractor.bulk-extractor, sift.packages.openjdk.openjdk, sift.packages.docker-engine.docker-engine
      - ID: undefined
        SLS: sift.scripts.vshot
        Run#: 441
        Comment: One or more requisite failed: sift.packages.bulk-extractor.bulk-extractor
      - ID: undefined
        SLS: sift.scripts
        Run#: 442
        Comment: One or more requisite failed: sift.scripts.vshot.sift-scripts-vshot
      - ID: sift-config-terminal-profiles-install
        SLS: sift.config.user.terminal
        Run#: 476
        Comment: Command "dconf load /org/gnome/terminal/ < /usr/share/sift/terminal-profiles.txt" run

This time I tried 
gpg --keyserver hkp://keyserver.ubuntu.com:11371 --recv-keys 22598A94

Errored out as follows:

>> Incomplete due to Failures -- Success: 452, Failure: 90

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: sift-docker-repo
        SLS: sift.repos.docker
        Run#: 2
        Comment: Failed to configure repo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main': Error: key retrieval failed: Executing: /tmp/tmp.DiKymb71FD/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--logger-fd
1
--recv-keys
58118E89F3A912897C070ADBF76221572C52609D
gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
      - ID: sift-gift-repo
        SLS: sift.repos.gift
        Run#: 4
        Comment: Failed to configure repo 'gift': Unable to add PPA 'gift/stable'. '['apt-add-repository', '-y', 'ppa:gift/stable']' exited with status 1: 'gpg: keyring `/tmp/tmpj16kwwlo/secring.gpg' created
gpg: keyring `/tmp/tmpj16kwwlo/pubring.gpg' created
gpg: requesting key 10C598B8 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpj16kwwlo/trustdb.gpg: trustdb created
gpg: key 10C598B8: public key "Launchpad PPA for Google Investigative Forensic Toolkit" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)'
      - ID: sift-repo
        SLS: sift.repos.sift
        Run#: 7
        Comment: Failed to configure repo 'sift-repo': Unable to add PPA 'sift/stable'. '['apt-add-repository', '-y', 'ppa:sift/stable']' exited with status 1: 'gpg: keyring `/tmp/tmp7_gyv5xs/secring.gpg' created
gpg: keyring `/tmp/tmp7_gyv5xs/pubring.gpg' created
gpg: requesting key 0744BEC3 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp7_gyv5xs/trustdb.gpg: trustdb created
gpg: key 0744BEC3: public key "Launchpad PPA for SANS Investigative Forensics Toolkit" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)'
      - ID: sift-repo-noobslab-themes
        SLS: sift.repos.noobslab
        Run#: 10
        Comment: Failed to configure repo 'noobslab-themes': Unable to add PPA 'noobslab/themes'. '['apt-add-repository', '-y', 'ppa:noobslab/themes']' exited with status 1: 'gpg: keyring `/tmp/tmp3v149v1z/secring.gpg' created
gpg: keyring `/tmp/tmp3v149v1z/pubring.gpg' created
gpg: requesting key F59EAE4D from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3v149v1z/trustdb.gpg: trustdb created
gpg: key F59EAE4D: public key "Launchpad PPA for NoobsLab" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)'
      - ID: sift-repo-noobslab-icons
        SLS: sift.repos.noobslab
        Run#: 11
        Comment: Failed to configure repo 'noobslab-icons': Unable to add PPA 'noobslab/icons'. '['apt-add-repository', '-y', 'ppa:noobslab/icons']' exited with status 1: 'gpg: keyring `/tmp/tmp0wejl7n0/secring.gpg' created
gpg: keyring `/tmp/tmp0wejl7n0/pubring.gpg' created
gpg: requesting key F59EAE4D from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp0wejl7n0/trustdb.gpg: trustdb created
gpg: key F59EAE4D: public key "Launchpad PPA for NoobsLab" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)'
      - ID: openjdk-repo
        SLS: sift.repos.openjdk
        Run#: 12
        Comment: Failed to configure repo 'openjdk-repo': Unable to add PPA 'openjdk-r/ppa'. '['apt-add-repository', '-y', 'ppa:openjdk-r/ppa']' exited with status 1: 'gpg: keyring `/tmp/tmp7_t_mgkd/secring.gpg' created
gpg: keyring `/tmp/tmp7_t_mgkd/pubring.gpg' created
gpg: requesting key 86F44E2A from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp7_t_mgkd/trustdb.gpg: trustdb created
gpg: key 86F44E2A: public key "Launchpad OpenJDK builds (all archs)" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)'
      - ID: undefined
        SLS: sift.repos
        Run#: 17
        Comment: One or more requisite failed: sift.repos.openjdk.openjdk-repo, sift.repos.sift.sift-repo, sift.repos.gift.sift-gift-repo, sift.repos.noobslab.sift-repo-noobslab-icons, sift.repos.noobslab.sift-repo-noobslab-themes, sift.repos.docker.sift-docker-repo
      - ID: undefined
        SLS: sift.packages.bitpim
        Run#: 28
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bitpim-lib
        Run#: 29
        Comment: One or more requisite failed: sift.repos.sift.sift-repo
      - ID: undefined
        SLS: sift.packages.bulk-extractor
        Run#: 34
        Comment: One or more requisite failed: sift.repos.sift.sift-repo, sift.repos.openjdk.openjdk-repo

Is there a way to get SIFT running on EC2? Would it be an option to provide a pre-build AMI on AWS, that could be simply used on AWS marketplace?

Please adivse?

Thank you for your help.

**Comment by ekristen** [comment]
Please do not comment on close issues. Please open a new issue.
