### ISSUE TITLE
Error running sift install

### ISSUE THREAD

**Issue by sgrenier55** [sans-dfir/sift#340]
Getting this error during installation:

>> Incomplete due to Failures -- Success: 535, Failure: 5

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: autopsy
        SLS: sift.packages.autopsy
        Run#: 24
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-re5983b82b83649b391883eb41995a13c.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: sleuthkit
        SLS: sift.packages.sleuthkit
        Run#: 219
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r27c2282f13c043d8bdb2f738a9bf81bd.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: xmount
        SLS: sift.packages.xmount
        Run#: 252
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r2bcf773d4f4f41099bdd060863e5855d.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: undefined
        SLS: sift.packages
        Run#: 255
        Comment: One or more requisite failed: sift.packages.autopsy.autopsy, sift.packages.sleuthkit.sleuthkit, sift.packages.xmount.xmount
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.packages.sift-packages

**Comment by ekristen** [comment]
See https://github.com/sans-dfir/sift/issues/337
