### ISSUE TITLE
Received these errors during sift installation

### ISSUE THREAD

**Issue by wdsharp** [sans-dfir/sift#341]
Ubuntu 16 VM 

>> Completed: sift-config (Took: 0.888 ms)

>> Incomplete due to Failures -- Success: 535, Failure: 5

>>>> List of Failures (first 10 only)

     NOTE: First failure is generally the root cause.

     IMPORTANT: If opening a ticket, please include this information.

      - ID: autopsy
        SLS: sift.packages.autopsy
        Run#: 24
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r38b5fffcd28b46468153681a75a39236.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: sleuthkit
        SLS: sift.packages.sleuthkit
        Run#: 219
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r2657888ce2064bb29912d8100ac69eda.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: xmount
        SLS: sift.packages.xmount
        Run#: 252
        Comment: Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r9f935f9c62434316b0556941c0aaa427.scope.
      E: Unable to correct problems, you have held broken packages.
      - ID: undefined
        SLS: sift.packages
        Run#: 255
        Comment: One or more requisite failed: sift.packages.autopsy.autopsy, sift.packages.sleuthkit.sleuthkit, sift.packages.xmount.xmount
      - ID: undefined
        SLS: sift.vm
        Run#: 548
        Comment: One or more requisite failed: sift.packages.sift-packages

**Comment by ekristen** [comment]
Please search issues for possible related ones before opening a new issue in the future. Thank you.

This is covered by https://github.com/sans-dfir/sift/issues/337
