### ISSUE TITLE
sift-files project massively violating FOSS licenses and copyright

### ISSUE THREAD

**Issue by joachimmetz** [sans-dfir/sift#342]
Sift files scripts https://github.com/sans-dfir/sift-files/tree/master/scripts seems to contain scripts with various FOSS licenses.

1. I don't see the corresponding license files provided in e.g. a licenses sub directory, therefore I suspect that this project violates several of the license of these script by redistributing them without complying to the original license e.g. https://github.com/sans-dfir/sift-files/blob/master/scripts/GA-Parser.py is GPLv3+ but I don't see a file LICENSE.GPLv3. See here for more detail: https://www.gnu.org/licenses/gpl-howto.html
2. https://github.com/sans-dfir/sift-files/blob/master/regripper/plugins/aim.pl e.g does not has a FOSS license (since it was added in 2014 see https://github.com/keydet89/RegRipper2.8/commits/master/license.txt and https://github.com/keydet89/RegRipper2.8/issues/4 for additional context) and therefore sift-files is violating regular copyright as well.

**Comment by ekristen** [comment]
This hasn't been used in years, it was archived, I just deleted it.

**Comment by joachimmetz** [comment]
> it was archived

Archived or not, FOSS and copyright still apply

> I just deleted it.

thx for correcting this.
