### ISSUE TITLE
sift-cli failure: sift.packages.xmount

### ISSUE THREAD

**Issue by MrGentry** [sans-dfir/sift#346]
ID: xmount
SLS: sift.packages.xmount
Run#: 252
Comment: Problem encountered installing package(s). Additional info follows:

errors:
- Running scope as run-r8de604821aa348d3a8004027d0567380.scope.
E: Unable to correct problems, you have held broken packages.
- ID: undefined
SLS: sift.packages
Run#: 255
Comment: One or more requisite failed: sift.packages.xmount.xmount
- ID: undefined
SLS: sift.vm
Run#: 548
Comment: One or more requisite failed: sift.packages.sift-packages
ubuntu:~$

**Comment by MrGentry** [comment]
Pretty sure its not using the current/stable version of sleuthkit, it says SleuthKit Version: 4.2.0

**Comment by ekristen** [comment]
Works for me.

**Comment by ekristen** [comment]
Standby, you might need an update to apt preferences too. Be sure to remove libewf2 as well.

**Comment by ekristen** [comment]
I'll post follow up instructions later this evening, I'm mobile at the moment.

**Comment by ekristen** [comment]
v2019.05.01-rc1 is out, you can use the `--upgrade` cli option to pick it up. This will adjust apt priorities. You might have to try and back out any changes you made, definitely make sure libewf2 is not installed.

**Comment by MrGentry** [comment]
I will try this

**Comment by ekristen** [comment]
`--pre-release` option. sorry I did a typo in the first.

**Comment by ekristen** [comment]
I'm also doing a full test right now to confirm.

**Comment by ekristen** [comment]
xmount is still a problem.

**Comment by MrGentry** [comment]
its still wanting libewf2 from the output I got.

**Comment by ekristen** [comment]
Sorry we don't want libewf2 from ubuntu's repos. We want it from GIFT.

**Comment by ekristen** [comment]
New xmount is being published to sift/stable right now.

**Comment by ekristen** [comment]
The latest prelease rc2 has it all fixed by my tests. Let me know if you still run into issues. If you get a chance to test with the `--pre-release` and let me know, I'll cut an official new release in the morning.

**Comment by MrGentry** [comment]
>> COMPLETED SUCCESSFULLY -- Success: 542, Failure: 0
$ sift version
sift-cli@1.7.1-master.f1177e4
sift-version: v2019.05-rc2
