### ISSUE TITLE
In need of SIFT with smaller pre-allocated disks

### ISSUE THREAD

**Issue by ize1** [sans-dfir/sift#35]
I need to install a SIFT workstation on an ESXi server which doesn't have a whole lot of space. Since the two virtual disks are preallocated at 500Gb each, ESXi tries to reserve 1 Tb for them when powering up the VM, and it doesn't have near that much space. I haven't been able to find anything on the Internet that says anything other than ' you cannot reduce the maximum size of preallocated disks.' Would it be possible to get a SIFT image with maybe 100GB total preallocated space?

**Comment by ekristen** [comment]
@ize1 I suggest you build your image using ubuntu 14.04 desktop image and then bootstrap it with the script that is used to make the prebuilt image. https://github.com/sans-dfir/sift-bootstrap
