### ISSUE TITLE
Ex01 with compression support

### ISSUE THREAD

**Issue by ruben03** [sans-dfir/sift#353]
Hello,

Sorry if this is not the correct place to ask this question.

I will like to know if there is any tool in the SIFT that supports mounting Ex01 with compression?
I started trying with a SIFT from the SANS course I took last year (version 2017 x) without any success, I thought that it might be because it was not updated. However I didn't have any luck with a clean Ubuntu were I installed the latest release of the SIFT (without any problem).

Is there support for this format? 

Kind regards,
Rubén

**Comment by ekristen** [comment]
You are probably best asking on the DFIR mailing list about what tools can handle that.

**Comment by ruben03** [comment]
Thanks I will try that.

**Comment by ruben03** [comment]
What I found is that SIFT uses libewf and this format requires libewf2, do you know if there is a way to change the library without breaking everything?

**Comment by ekristen** [comment]
There is a lot of confusion and headache around libewf due to ubuntu packaging older versions. However SIFT installs the latest libewf from https://launchpad.net/~gift/+archive/release which is the official distribution of libewf. 

You can verify this using `dpkg -l` and `apt-cache showpkg` commands.

**Comment by ruben03** [comment]
Thanks ekristen, what I haven't been able to find out is if this library (the version that is used by the SIFT, the official) supports the compressed format, in theory (I haven't test it), the one that Ubuntu includes with name libewf2 supports it.

**Comment by ekristen** [comment]
libewf is for the expert witness compression format but I don’t use it, I would expect it to support compression. 

I’m going to close this. This repo is really for tracking issues with SIFT installation or upgrades.
