### ISSUE TITLE
SANS typical menu missing from along the top in 3.0 download vmware appliance

### ISSUE THREAD

**Issue by wrkrbee** [sans-dfir/sift#38]
I downloaded the appliance from the 3.0 page. Opened it using VMware Workstation 10.0.30 build -1895310 and I have no Sans menu along the top.

**Comment by ekristen** [comment]
It sounds like a driver or VM version issue.

@SANS-SIFT might be able to comment, as they build the VM. However you can install a vanilla 14.04 install of ubuntu and then run the bootstrap script https://github.com/sans-dfir/sift-bootstrap/ and you will get everything that is in the VM.

**Comment by ekristen** [comment]
Closing this out. If you still are having problems feel free to re-open it.
