### ISSUE TITLE
please dont close this issue I didnt got resolved this issue when i tried to purge that pyopenssl in ubuntu 16.04 which is in aws ec2 its giving error!

### ISSUE THREAD

**Issue by ForensicsEnthusiastRL** [sans-dfir/sift#394]
root@ip-:/var/cache/sift/cli/v2019.06.0# sudo apt --purge remove pyopenssl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package pyopenssl

**Comment by ekristen** [comment]
Dupe of https://github.com/teamdfir/sift/issues/393
