### ISSUE TITLE
yarascan volatility plugin on SIFT Workstation 3.0

### ISSUE THREAD

**Issue by mattulm** [sans-dfir/sift#40]
Hello, I had been using the SIFT Workstation provided to me from the Memory Forensics couse, and I have been having an issue, where i could not get yarascan to work properly. I have finally been able to resolve this and I figured I would share, in case anyone else is having this issue.

Found from the web: (https://code.google.com/p/volatility/issues/detail?id=446)
"""
There are different versions of yara. One you would install through apt-get, yum, source, etc., and this would work. You could also download yara through the python utility “pip” (This command: “sudo pip install yara”) The problem is that this actually installs yara-ctypes which is slightly different. The reason it breaks within volatility is that yara-ctypes is a third party wrapper for libyara and appears to use slightly different APIs than yara-python
"""

Ok, the fix I did on the SANS workstation.
Sudo pip uninstall yara
Sudo apt-get install yara

For me, yarascan plugin starts working with no problems……
Cheers!

**Comment by ekristen** [comment]
@SANS-SIFT any thoughts on this?

**Comment by z3ndrag0n** [comment]
Will try and replicate tonight (see if it's still an issue with latest versions and if so if the proposed workaround still works). If so, I recommend we implement and flag for upstream.

Cheers,
Barry

**Comment by ekristen** [comment]
bump
