### ISSUE TITLE
Mount_ewf.py fuse:warning library too old

### ISSUE THREAD

**Issue by vptgeg** [sans-dfir/sift#43]
Hello,

when i try to mount an Encase Image, i recieve this message:
mount_ewf.py whatever.E01 /mnt/ewf
ewfmount 20140608

fuse: warning: library too old, some operations may not not work
root@siftworkstation:/mnt/hgfs/Cases/test#

used the vmware-image.

**Comment by ekristen** [comment]
Try and use the bootstrap script to upgrade. There should also be an upgrade script on your desktop.

**Comment by ekristen** [comment]
Unable to validate/re-produce. Please let me know if you continue to see this problem and feel free to re-open the issue.
