### ISSUE TITLE
Volatility problem in /usr/bin

### ISSUE THREAD

**Issue by dptom** [sans-dfir/sift#46]
Just working with SIFT 3.0 on Ubuntu. Looks like there is a broken link in /usr/bin

lrwxrwxrwx 1 root root 12 Mar 13  2014 vol.py -> /usr/bin/vol

No such file as /usr/bin/vol. Not certain if this is a problem for others. I'm going to update the volatility and fix this in my version.

**Comment by ekristen** [comment]
Just resolved this in the sift-bootstrap script.
