### ISSUE TITLE
Tzworks license expired

### ISSUE THREAD

**Issue by nwf9** [sans-dfir/sift#47]
Hi guys,

The last utilisation day was the 02 feb 2015 , it's possible to extend the education license ?

many thanks

**Comment by ekristen** [comment]
@SANS-SIFT do we have a new license that we can use to update the vmware appliance with?

**Comment by SANS-SIFT** [comment]
Not at this point.  They are not going to do the demo license any longer.

**Comment by ekristen** [comment]
@nwf9 unfortunately this is not going to be fixed. The tools are actually being removed from the next version.
