### ISSUE TITLE
vanilla 14.04 bootstrap triggers dconf errors

### ISSUE THREAD

**Issue by ekristen** [sans-dfir/sift#48]
During the post-install script, seven of the following errors were displayed (three for each of two PIDs, one for a third PID):
(process:<%PID%>): dconf-CRITICAL **: unable to create file '/home/user/.cache/dconf/user': Permission denied. dconf will not work properly.

No other package management utilities running at the time.

**Comment by z3ndrag0n** [comment]
Doing a 14.04 install later today, will chase down and should have something back shortly.

Thanks and regards,
Barry

**Comment by z3ndrag0n** [comment]
Can confirm that these errors are false as the file already exists. Can strace the process to get to the source of the issue or we can accept them as false alarms.

Cheers,
Barry

**Comment by ekristen** [comment]
bump. Did you get anywhere with troubleshooting? I can't reliably reproduce.

**Comment by z3ndrag0n** [comment]
I have some time this afternoon - I'll have a look then with strace; as I said above it's fairly clear they're false positives as the command is blindly trying to create a file that already exists.

**Comment by ekristen** [comment]
The latest bootstrap script suppresses these messages. I have not been able to determine yet why they occur. The changes still take place even when the errors show up.
