### ISSUE TITLE
Volatility will not install

### ISSUE THREAD

**Issue by Moonman1** [sans-dfir/sift#49]
Volatility can not process volatility_2.3.1-7_all.deb (Image Attached, Any help with this issue is appreciated)

dpkg: error processing archive /var/cache/apt/archives/volatility_2.3.1-7_all.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/volatility/protos.py', which is also in package python-volatility 2.4-trust1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package volatility-profiles.
Preparing to unpack .../volatility-profiles_20140130-1_all.deb ...
Unpacking volatility-profiles (20140130-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/volatility_2.3.1-7_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
![volatility_error](https://cloud.githubusercontent.com/assets/11199180/6378726/2a6598de-bcfb-11e4-83b0-14775c068b3b.JPG)

**Comment by ekristen** [comment]
For whatever reason it seems your apt repositories are not correct. The latest version in the sift repo is 2.4 and it comes installed.

**Comment by Moonman1** [comment]
I just downloaded and opened the ovf file from the sift website and got the exact same error
![volatility2_error](https://cloud.githubusercontent.com/assets/11199180/6379333/7e7803e0-bcff-11e4-8c59-6d6080a558b4.JPG)

**Comment by ekristen** [comment]
Why are you trying to install volatility? It's already installed, or at least should be. 

The package name we use is python-volatility from our sift repo, not volatility.

**Comment by ekristen** [comment]
bump
