### ISSUE TITLE
Please add Timesketch

### ISSUE THREAD

**Issue by SANS-SIFT** [sans-dfir/sift#50]
https://github.com/google/timesketch

**Comment by SANS-SIFT** [comment]
This installation guide is based on Ubuntu 14.04LTS.

1) Install Elasticsearch
Download the DEB from the official site
https://www.elasticsearch.org/overview/elkdownloads/
Install Java (Elasticsearch is written in Java)
$ sudo apt-get install openjdk-7-jre-headless
Install the downloaded Elasticsearch DEB
$ sudo dpkg -i elasticsearchXXX.deb
Configure Elasticsearch
This is up to your specific environment, but if you run elastic on the same box as Timesketch you should lock it down to only listen to localhost.
The configuration for Elasticsearch is located in /etc/elasticsearch/elasticsearch.yaml
2) Install Timesketch

$ apt-get install python-pip python-dev git
$ git clone https://github.com/google/timesketch.git
$ cd timesketch
$ sudo pip install .
$ sudo cp timesketch.conf /etc/
Edit /etc/timesketch.conf
Generate a SECRET_KEY
Choose where to store your database
$ tsctl add_user -u <username>
$ tsctl runserver

**Comment by ekristen** [comment]
Requires #51 be completed first.

**Comment by ekristen** [comment]
Will be in the next release

**Comment by berggren** [comment]
Hi, I'm the author of Timesketch. Let me know if there is anything I can help with to make this happen.

**Comment by ekristen** [comment]
It is in the latest bootstrap script. We are going through tests and then will be cutting a new VM image.
