### ISSUE TITLE
Add openioc_scan 

### ISSUE THREAD

**Issue by SIFT-OWNER** [sans-dfir/sift#54]
Consider adding back the Didier Stevens PDF parsing tools (pdf-parser, pdfid, etc.)

Add openioc_scan Volatility plugin (python modules required): http://takahiroharuyama.github.io/blog/2014/08/15/fast-malware-triage-using-openioc-scan-volatility-plugin/

Can you ensure we download and test that openioc_scan plugin?

**Comment by ekristen** [comment]
Didier Stevens PDF tools was added and resolved by issues #56
