### ISSUE TITLE
Add packerid, install python-magic, pescanner, pdf-tools, and pdfid

### ISSUE THREAD

**Issue by SANS-SIFT** [sans-dfir/sift#56]
http://handlers.sans.org/jclausing/packerid.py
https://github.com/ahupp/python-magic
http://blog.didierstevens.com/programs/pdf-tools/

**Comment by ekristen** [comment]
PDF Tools: https://github.com/sans-dfir/sift-files/commit/95e87464993e215da8ce592591b1723891bd038f

**Comment by ekristen** [comment]
Complete
