### ISSUE TITLE
VMware cannot be used after upgrading of SIFT 3.0

### ISSUE THREAD

**Issue by ricci3** [sans-dfir/sift#57]
I'm using SIFT 3.0 VM guest OS on Mac OS X 10.10 with VMFusion. 

The share folder shared by VM host can be accessed by SIFT 3.0 VM Guest OS. But after upgrade and update of SIFT 3.0 using apt-get, the VM share folder disappeared and vmhgfs cannot operate properly. Nothing can be seen in the /mnt/hgfs folder.

I have tried to install vmware tools, but it cannot work. Please advise what is the missing configuration or should we not upgrade the system?

Thx

**Comment by ricci3** [comment]
This is the error message found in VM compilation:

In file included from /usr/src/linux-headers-3.13.0-46-generic/arch/x86/include/asm/percpu.h:44:0,
                 from /usr/src/linux-headers-3.13.0-46-generic/arch/x86/include/asm/preempt.h:5,
                 from include/linux/preempt.h:18,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/mm.h:8,
                 from include/linux/pagemap.h:7,
                 from /tmp/modconfig-htlRja/vmhgfs-only/inode.c:29:
/tmp/modconfig-htlRja/vmhgfs-only/inode.c: In function ‘HgfsPermission’:
include/linux/kernel.h:793:27: error: ‘struct dentry’ has no member named ‘d_alias’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                           ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:708:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(*(pos)), member);\
             ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/kernel.h:793:48: warning: initialization from incompatible pointer type [enabled by default]
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:708:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(*(pos)), member);\
             ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from /usr/src/linux-headers-3.13.0-46-generic/include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /tmp/modconfig-htlRja/vmhgfs-only/./shared/driver-config.h:71,
                 from /tmp/modconfig-htlRja/vmhgfs-only/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:794:29: note: in expansion of macro ‘offsetof’
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:708:13: note: in expansion of macro ‘hlist_entry_safe’
  for (pos = hlist_entry_safe((head)->first, typeof(*(pos)), member);\
             ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/preempt.h:10:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/mm.h:8,
                 from include/linux/pagemap.h:7,
                 from /tmp/modconfig-htlRja/vmhgfs-only/inode.c:29:
include/linux/list.h:710:35: error: ‘struct dentry’ has no member named ‘d_alias’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
                                   ^
include/linux/list.h:697:12: note: in definition of macro ‘hlist_entry_safe’
  ({ typeof(ptr) ____ptr = (ptr); \
            ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/list.h:710:35: error: ‘struct dentry’ has no member named ‘d_alias’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
                                   ^
include/linux/list.h:697:28: note: in definition of macro ‘hlist_entry_safe’
  ({ typeof(ptr) ____ptr = (ptr); \
                            ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from /usr/src/linux-headers-3.13.0-46-generic/arch/x86/include/asm/percpu.h:44:0,
                 from /usr/src/linux-headers-3.13.0-46-generic/arch/x86/include/asm/preempt.h:5,
                 from include/linux/preempt.h:18,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:4,
                 from include/linux/mm.h:8,
                 from include/linux/pagemap.h:7,
                 from /tmp/modconfig-htlRja/vmhgfs-only/inode.c:29:
include/linux/kernel.h:793:27: error: ‘struct dentry’ has no member named ‘d_alias’
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                           ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:710:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
             ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
include/linux/kernel.h:793:48: warning: initialization makes pointer from integer without a cast [enabled by default]
  const typeof( ((type *)0)->member ) *__mptr = (ptr); \
                                                ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:710:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
             ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
In file included from include/linux/compiler-gcc.h:106:0,
                 from include/linux/compiler.h:54,
                 from include/uapi/linux/stddef.h:1,
                 from include/linux/stddef.h:4,
                 from /usr/src/linux-headers-3.13.0-46-generic/include/uapi/linux/posix_types.h:4,
                 from include/uapi/linux/types.h:13,
                 from include/linux/types.h:5,
                 from /tmp/modconfig-htlRja/vmhgfs-only/./shared/driver-config.h:71,
                 from /tmp/modconfig-htlRja/vmhgfs-only/inode.c:26:
include/linux/compiler-gcc4.h:14:34: error: ‘struct dentry’ has no member named ‘d_alias’
 #define __compiler_offsetof(a,b) __builtin_offsetof(a,b)
                                  ^
include/linux/stddef.h:17:31: note: in expansion of macro ‘__compiler_offsetof’
 #define offsetof(TYPE,MEMBER) __compiler_offsetof(TYPE,MEMBER)
                               ^
include/linux/kernel.h:794:29: note: in expansion of macro ‘offsetof’
  (type *)( (char *)__mptr - offsetof(type,member) );})
                             ^
include/linux/list.h:687:40: note: in expansion of macro ‘container_of’
 #define hlist_entry(ptr, type, member) container_of(ptr,type,member)
                                        ^
include/linux/list.h:698:15: note: in expansion of macro ‘hlist_entry’
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
               ^
include/linux/list.h:710:13: note: in expansion of macro ‘hlist_entry_safe’
       pos = hlist_entry_safe((pos)->member.next, typeof(*(pos)), member))
             ^
/tmp/modconfig-htlRja/vmhgfs-only/inode.c:1920:7: note: in expansion of macro ‘hlist_for_each_entry’
       hlist_for_each_entry(dentry,
       ^
make[2]: *** [/tmp/modconfig-htlRja/vmhgfs-only/inode.o] Error 1
make[1]: *** [_module_/tmp/modconfig-htlRja/vmhgfs-only] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-46-generic'
make: *** [vmhgfs.ko] Error 2
make: Leaving directory `/tmp/modconfig-htlRja/vmhgfs-only'

**Comment by ekristen** [comment]
Upgrading is fine. This is a VMWare issue not a SIFT issue.

* Check out your VMWare compatibility settings. 
* Ensure you install the right kernel headers and kernel dev packages before trying to upgrade or install vmware tools.

**Comment by ekristen** [comment]
Have you been able to take a look at this anymore?

**Comment by runeespe** [comment]
Hi,


Just chiming in here, to let you know I am facing the same issue just now.

A freshly downloaded SIFT appliance yesterday, installed VMWare tools fine, shared folders working.
This morning, Ubuntu wanted to update, I let it.
VMWare tools features stopped working, reinstalled.
I get same error as above when it comes to recompiling the vmhgfs.

**Comment by runeespe** [comment]
FYI:

This worked for me:
https://communities.vmware.com/message/2482598

*Though I had to re-run the vmware-config-tools.pl manually, as the script in that link runs it silently and it skips the recompiling of the vmhgfs since it was not installed (which is what we're trying to solve here :-) )

**Comment by ekristen** [comment]
Thanks @runeespe - glad you found a solution.
