### ISSUE TITLE
Properly keeping SIFT up to date

### ISSUE THREAD

**Issue by DigiAngel** [sans-dfir/sift#61]
Topic says it...is doing a sudo apt-get update && sudo apt-get dist-upgrade the only thing I need to do to make sure my SIFT on Ubuntu 14.04 stays up to date?  Thank you.

**Comment by ekristen** [comment]
There should be an update.sh script on your desktop, that'll do a system wide package update and make sure you have the latest sift files too.

**Comment by ekristen** [comment]
If it is not there you can run the bootstrap script with the `-u` option for upgrade only.

**Comment by DigiAngel** [comment]
Thanks for the response.  I do not have an update.sh, and bootstrap.sh -u does not appear to work:
~~~
root@siftworkstation:/home# ./bootstrap.sh -u
./bootstrap.sh: 153: ./bootstrap.sh: Syntax error: Bad function name
root@siftworkstation:/home# vi bootstrap.sh
root@siftworkstation:/home# sh bootstrap.sh -u
bootstrap.sh: 153: bootstrap.sh: Syntax error: Bad function name

**Comment by ekristen** [comment]
You have to use bash. I fixed the default shell for the script to be bash.

**Comment by DigiAngel** [comment]
That did the trick:
~~~
[14:01:53 bleh@sift:~$] sudo ./bootstrap.sh -u
[sudo] password for bleh:

 * INFO: SIFT Update
 * INFO: All other options will be ignored!
 * INFO: This could take a few minutes ...
 * INFO: Updating your APT Repositories ...
 * INFO: Installing Python Software Properies ...
 * INFO: Enabling Universal Repository ...
 * INFO: Enabling Elastic Repository ...
 * INFO: Adding Ubuntu Tweak Repository
 * INFO: Adding SIFT Repository: stable
 * INFO: Updating Repository Package List ...
...
~~~

Thanks so much!

**Comment by zappeee** [comment]
When I'm running this I get

 * INFO: SIFT VM: Installing SIFT Files
./bootstrap.sh: line 457: cd: /tmp/sift-files: No such file or directory

**Comment by ekristen** [comment]
I need to see your install or update log, most likely it was unable to check out the Git repo and that's why that error occurred
