### ISSUE TITLE
SIFT 3.0 attempting to monitor all network traffic at boot.  

### ISSUE THREAD

**Issue by socialcred** [sans-dfir/sift#62]
In addition to the silent tor daemon starting and connecting to the tor network at boot, I noticed another disturbing issue in a brand new SIFT 3.0 machine I built using bootstrap yesterday.  The machine attempts to monitor all network traffic startup.  I haven't identified what daemon is doing that, but it is obviously a major security concern.  Having the ability to sniff traffic is important, but having a forensics machine configured to do that at boot up without specific documentation is troubling.  Can you identify the tool that is doing that so that it can be disabled?

**Comment by ekristen** [comment]
I don't recall of the top of my head, but I'll find out and we can document it to.

**Comment by ekristen** [comment]
`nfdump` is the package.

`sudo update-rc.d nfdump disable`

**Comment by ekristen** [comment]
@socialcred does this address your concern? Many people find this tool useful, we are looking at how we can install but disable it by default.

**Comment by ekristen** [comment]
@SANS-SIFT should we just disable `nfdump` from being installed and let people who want it install it manually? 

We are unable to prevent the service from starting up without rewriting the entire nfdump project each time there is an update to remove the service scripts.

The other option would be to add another flag to the bootstrap script '-e' (extra) or something that can signify the more "invasive" packages and install them.

**Comment by ekristen** [comment]
If this is still an issue, we'll come back to it.
