### ISSUE TITLE
[SALTSTACK] - sudo cast install teamdfir/sift-saltstack gives 404 error

### ISSUE THREAD

**Issue by garr3ttmjo** [sans-dfir/sift#622]
<img width="992" alt="image" src="https://github.com/teamdfir/sift/assets/108881417/8337f984-1bed-4efe-8a20-865242be6746">

sudo cast install teamdfir/sift-saltstack command runs but fails with 404 error when it reaches saltstack-installer.

**Comment by ekristen** [comment]
Please turn on debug logging using `-l debug` or event `-l trace` copy and paste is preferred over screenshots. I'll check the tooling out while we are at it.

**Comment by ekristen** [comment]
@garr3ttmjo please also provide `cast --version` -- I've tested the latest version and it seems to be working just fine.

**Comment by ekristen** [comment]
Also what architecture are you on?

**Comment by ekristen** [comment]
My guess is that you are on an ARM based architecture which there currently isn't support for.  I'll take a note to put an error message in to handle that specifically where possible.

**Comment by ekristen** [comment]
@garr3ttmjo any chance to look at the above?

**Comment by garr3ttmjo** [comment]
Hi Erik,

Sorry for the late reply. Thank you for your help looking into this. You
are right it is because I am on ARM architecture that it is not working.

Thanks,
Garrett

**Comment by ekristen** [comment]
Unfortunately we still can't support ARM infrastructure has many of the tools are simply not built for it. We are working on it, but it's a slow road.
