### ISSUE TITLE
[SALTSTACK] - Python 2 ??

### ISSUE THREAD

**Issue by coinsan** [sans-dfir/sift#625]
Does Sift-saltstack install python2 even though it is end of life?

Where in the readme does it mention the location of any forums?

**Comment by ekristen** [comment]
It may. Many tools are not python3 compatible last time we checked, our hope is to stop using it but haven't said we'd not install specific tools. 

With the 24.04 update coming we will be evaluating tools that depend on python2 for continue inclusion.

**Comment by coinsan** [comment]
I know of corporations that have a block on any technology product(utility) that uses python2.

Thank you your hard work !!!
