### ISSUE TITLE
[SALTSTACK] - Installer Failure

### ISSUE THREAD

**Issue by harrywat** [sans-dfir/sift#626]
We have been building on an automated, weekly basis SIFT workstations with the recent versions of Ubuntu 22.04
However as of two weeks ago we're seeing build failures.

Running manually ``` sudo cast install --mode=server teamdfir/sift-saltstack ```

The most recent fail state reported with:

```
WARN[2711] first failed state                            comment="One or more requisite failed: sift.packages.aws-cli.aws-cli-install" component=installer run_num=226 sls=sift.packages.aws-cli
INFO[2711] statistics                                    component=installer failed=8 success=565 total=573
INFO[2711] salt-call completed but had failed states     component=installer
FATA[2711] salt-call completed but had failed states
```

Is there also a way to validate by installing an earlier saltstack version to confirm the issue is related to recent updates?

**Comment by ekristen** [comment]
There was a bug in the recent build, that should be fixed. I also ask that you download and update to the latest `cast` binary.

**Comment by harrywat** [comment]
Thanks for the reply. I've just run with no-cache and confirm I'm pulling v2024.02.25 but hit the same issue, with the same fail count.  I'm using the latest cast cast-v0.14.21-linux-amd64

Running the install with debug level set I receive:

```
WARN[0418] first failed state                            comment="Specified sha256 checksum for /tmp/awscli-exe-linux-x86_64.zip (77c6c3d1ac23638b07a02587ed6b1d4adc84c561c9ecc7df1ff3778e43a4b49b) does not match actual checksum (c939005170508b19f53730ead3e15b959ec2d9d078a44668e43275864d73ef2f)" component=installer run_num=223 sls=sift.packages.aws-cli
INFO[0418] statistics                                    component=installer failed=8 success=565 total=573
INFO[0418] salt-call completed but had failed states     component=installer
FATA[0418] salt-call completed but had failed states
```

**Comment by ekristen** [comment]
ok, I can fix this in short order. I might pull aws-cli in the short term here. It seems it's changing too frequently.

**Comment by ekristen** [comment]
ok 2024.02.29 is published, temporarily disabled aws-cli until I can address it's volatility.

**Comment by harrywat** [comment]
Thanks for the quick response, I can confirm builds are now running successfully on 2024.02.29
