### ISSUE TITLE
[SALTSTACK] - 404 when running command "sudo cast install teamdfir/sift-saltstack"

### ISSUE THREAD

**Issue by NORMA-Ole** [sans-dfir/sift#629]
Installing on Ubuntu VM rosetta emulation
Tried both without cloning the repo to VM and with cloning repo to VM. 
Also tried running as root with sudo su. 

![Screenshot 2024-06-12 at 13 27 44](https://github.com/teamdfir/sift/assets/134364746/0f3f2a36-1de4-48cc-b27e-7859a1cc2c88)

**Comment by ekristen** [comment]
ARM64 is not yet supported.
