### ISSUE TITLE
Live DVD

### ISSUE THREAD

**Issue by rudi127** [sans-dfir/sift#63]
Hi,

Would it be possible to get the SIFT as live dvd ?

It tried to do it myself from a VM and remastersys but it doesn't work.
The VM is working fine.

I would like to start the live dvd on my PC to train with my own data.

Thanks in advance.

Rudi.

**Comment by ekristen** [comment]
It might be possible. I'll talk to Rob Lee about it. I'll leave this ticket open in the mean time.

**Comment by bgenidy** [comment]
Hi Rudi,
I believe the following link would be able to help you.
https://www.turnkeylinux.org/blog/convert-vm-iso

Basically after creating a virtual disk you can convert it to an iso and from there you should be able to make it bootable using conventional methods.

Hope that helps.

**Comment by rudi127** [comment]
Thanks a lot.

It seems that the package tklpatch isn't available on Ubuntu 14.04LTS.

Now, SIFT is installed on a dual boot PC ( WIN 7 & Ubuntu ).

**Comment by rudi127** [comment]
Hi,

Just to tell you it's working.
I've found a version of remastersys at the following link : 
https://ryandanny.wordpress.com/2015/04/25/install-remastersys-di-ubuntu-14-04/
The system was installed already and with the commands below, I've got the live DVD.
sudo remastersys dist cdfs
sudo remastersys dist iso sift.iso

**Comment by ekristen** [comment]
Fantastic
