### ISSUE TITLE
Latest version of Ubuntu errors

### ISSUE THREAD

**Issue by adamf007** [sans-dfir/sift#630]
I am trying to install the SIFT system using CAST from within the latest version of Ubuntu workstation as the instructions state, but get the following message
WARN[0000] using unauthenticated github client, could result in API rate limiting 
INFO[0001] checking operating system support             component=distro owner=teamdfir repo=sift-saltstack
FATA[0001] operating system is not supported 

Any suggestions in how to see what it is puking on?

**Comment by digitalsleuth** [comment]
Hi Adam, at this time SIFT only supports Ubuntu 20 and 22. If you use one of those versions, you should be good to go.

**Comment by ekristen** [comment]
Closing in favor of #638 , please follow that issue for updates.
