### ISSUE TITLE
[SALTSTACK] -salt-call completed but had failed states

### ISSUE THREAD

**Issue by howardgitalong** [sans-dfir/sift#631]
Trying tsalt-call completed but had failed stateso install the SFIT cli in WSL2 on a Windows 10 machine; runs quite a while but ends with
"salt-call completed but had failed states "

**Comment by BladeRunner117** [comment]
I have the same issue right now, noticed docker was within the error and I do not have docker installed on WSL so I am installing and retrying. 

Update: Worked but new error message for out-of-date SSL certs, installing new certs and attempting again.
Update: Current error 

WARN[0331] first failed state                            
comment="One or more requisite failed: sift.packages.docker.sift-package-docker" component=installer run_num=223 sls=sift.packages

**Comment by ekristen** [comment]
Depending on the environment some scripts may fail to install. A full log would identify which ones are failing. Only the things that fail are failed, SIFT does not revert in the event of a singular failure.
