### ISSUE TITLE
Having Issues installing this on latest ubuntu under WSL

### ISSUE THREAD

**Issue by Parashudhara** [sans-dfir/sift#633]
root@TestVM:/# sudo cast install teamdfir/sift-saltstack
WARN[0000] using unauthenticated github client, could result in API rate limiting
INFO[0000] checking operating system support             component=distro owner=teamdfir repo=sift-saltstack
INFO[0000] operating system is supported                 component=distro owner=teamdfir repo=sift-saltstack
INFO[0000] rendering manifest                            component=distro owner=teamdfir repo=sift-saltstack
FATA[0000] template: pillar_template:1: function "default" not defined

I am running 

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Comment by ekristen** [comment]
Interesting, thank you for the report. I will take a look.

**Comment by ekristen** [comment]
Can't immediately reproduce it. What version of cast are you using?

**Comment by Parashudhara** [comment]
@ekristen  Thanks for the tip. Changing cast version to latest one did solved this.
