### ISSUE TITLE
install appears to stall

### ISSUE THREAD

**Issue by knight-scott** [sans-dfir/sift#634]
when using `sudo cast install teamdfir/sift-saltstack `the install appears to just hang after working for a bit. It's been more than an hour since any output or visible action. 

I'm not sure what to attach to help with diagnoses. I'm installing on a vm with Ubuntu 20.04.6.

**Comment by ekristen** [comment]
I should introduce a timeout feature. Sometimes it looses track due to how the output is captured and can occasionally hang. Have you tried stopping and running again?

**Comment by knight-scott** [comment]
Not yet. I wasn't sure if I was just being impatient. I will try to restart the process.

**Comment by knight-scott** [comment]
I got a few failures that time with the following output:
```

WARN[0225] first failed state                            comment="An exception occurred in this state: Traceback (most recent call last): File \\salt/state.py\\, line 2276, in call ret = self.states[cdata[\\full\\]]( File \\salt/loader/lazy.py\\, line 149, in __call__ return self.loader.run(run_func, *args, **kwargs) File \\salt/loader/lazy.py\\, line 1228, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File \\salt/loader/lazy.py\\, line 1243, in _run_as return _func_or_method(*args, **kwargs) File \\salt/loader/lazy.py\\, line 1276, in wrapper return f(*args, **kwargs) File \\/tmp/_MEIw0TwH1/salt/states/pkg.py\\, line 1698, in installed result = _find_install_targets( File \\/tmp/_MEIw0TwH1/salt/states/pkg.py\\, line 712, in _find_install_targets resolved_latest = __salt__[\\pkg.latest_version\\]( File \\salt/loader/lazy.py\\, line 149, in __call__ return self.loader.run(run_func, *args, **kwargs) File \\salt/loader/lazy.py\\, line 1228, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File \\salt/loader/lazy.py\\, line 1243, in _run_as return _func_or_method(*args, **kwargs) File \\/tmp/_MEIw0TwH1/salt/modules/aptpkg.py\\, line 474, in latest_version refresh_db(cache_valid_time) File \\/tmp/_MEIw0TwH1/salt/modules/aptpkg.py\\, line 599, in refresh_db raise CommandExecutionError(comment) salt.exceptions.CommandExecutionError: E: Release file for http://us.archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease is not valid yet (invalid for another 14min 12s). Updates for this repository will not be applied. E: Release file for http://ppa.launchpad.net/gift/stable/ubuntu/dists/focal/InRelease is not valid yet (invalid for another 3min 35s). Updates for this repository will not be applied. E: Release file for https://ppa.launchpadcontent.net/gift/stable/ubuntu/dists/focal/InRelease is not valid yet (invalid for another 3min 35s). Updates for this repository will not be applied. E: Release file for https://ppa.launchpadcontent.net/remnux/stable/ubuntu/dists/focal/InRelease is not valid yet (invalid for another 3min 43s). Updates for this repository will not be applied. " component=installer run_num=165 sls=sift.packages.python3-dfvfs
INFO[0225] statistics                                    component=installer failed=6 success=667 total=673
INFO[0225] salt-call completed but had failed states     component=installer
FATA[0225] salt-call completed but had failed states    
siftforensics@siftworkstation: ~

```

**Comment by knight-scott** [comment]
I attempted the install again and it appeared successful as the desktop background changed to the SIFT desktop image, however the time is 7 hours ahead of my local time. I rebooted the workstation and it appears to have reverted to the same state it was in before the new install. I repeated this twice with the same result; the vm time is still 7 hours ahead of the host, but that is the only sign that the install had any impact and each time I reboot the vm from the CLI, it appears to negate the SIFT install.

**Comment by knight-scott** [comment]
[saltstack.log](https://github.com/user-attachments/files/16404133/saltstack.log)

the install seems to work but rebooting the machine appears to revert it still. Not sure if I'm missing something, but is there a way to verify the SIFT install as successful?

**Comment by ekristen** [comment]
@knight-scott what do you mean by "appears to revert it still" -- the install command is idempotent, it will always try and run all the scripts to ensure everything is in the right state. There is no this file exists, therefore it is installed type approach.
