### ISSUE TITLE
[arm64] problems installing SIFT with cast

### ISSUE THREAD

**Issue by D2TZC4BP69N9R76H** [sans-dfir/sift#635]
Hi!

I downloaded ubuntu desktop 22.04 02 Desktop in Parallels and used cast to install SIFT workstation.

However, I get the following error:
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/f4ddfe9d-fce7-4436-b0ed-81876b6c7b80">

**uname -a returns:**
Linux ubuntu-linux-22-04-02-desktop 5.15.0-118-generic #128-Ubuntu SMP Fri Jul 5 09:30:28 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Cast version:**
cast version v0.14.44

Thanks in advance!

**Comment by forensicator0x10** [comment]
I am also getting the above error. Any help with this issue would be appreciated! : )

**Comment by ekristen** [comment]
Top priority for me to fix, trying to do it today.

**Comment by ekristen** [comment]
@D2TZC4BP69N9R76H @forensicator0x10 what architecture are you on? AMD64 or ARM64?

**Comment by ekristen** [comment]
I just saw the uname, I missed it the first time. Currently ARM64 is not supported.  We do need to fix the saltstack portion, but there's about 50% of the packages installed by SIFT that are only available for AMD64 at the moment.

**Comment by ekristen** [comment]
ARM64 just isn't supported at this time, closing in favor of #592 please follow that issue for updates.
