### ISSUE TITLE
[SALTSTACK] - Install SIFT Workstation

### ISSUE THREAD

**Issue by cobbst** [sans-dfir/sift#639]
I'm trying to install SIFT Workstation. When running the following command sudo cast install teamdfir/sift - it throws and error of 404 Not found.

Any suggestion, on a work around to be able to install Sift Workstation on Ubuntu 20.4 would be great.

**Comment by digitalsleuth** [comment]
Hi @cobbst , we are actively working on a fix for this. The issue resolves around the installation of Saltstack, which has recently shifted it's infrastructure to a new platform. We will let you know once this is addressed.

**Comment by cobbst** [comment]
> Hi @cobbst , we are actively working on a fix for this. The issue resolves around the installation of Saltstack, which has recently shifted it's infrastructure to a new platform. We will let you know once this is addressed.

Thanks for the update!

**Comment by ekristen** [comment]
@cobbst -- please try this version, should resolve the issue, but if not please let me know. I'm doing further testing as we speak - https://github.com/ekristen/cast/releases/tag/v0.14.52

**Comment by cobbst** [comment]
> @cobbst -- please try this version, should resolve the issue, but if not please let me know. I'm doing further testing as we speak - https://github.com/ekristen/cast/releases/tag/v0.14.52

@ekristen  -- I will give this a try later today when I get home. Fingers crossed as I can't wait to get Sift install to start learning :-)

**Comment by cobbst** [comment]
> @cobbst -- please try this version, should resolve the issue, but if not please let me know. I'm doing further testing as we speak - https://github.com/ekristen/cast/releases/tag/v0.14.52

@ekristen  -- Hi, So Ran the command again and got further, but now a new error open /etc/apt/keyrings/salt-archive-keyring-2023.pgp: no such file or directory

**Comment by cobbst** [comment]
> > @cobbst -- please try this version, should resolve the issue, but if not please let me know. I'm doing further testing as we speak - https://github.com/ekristen/cast/releases/tag/v0.14.52
> 
> @ekristen -- I will give this a try later today when I get home. Fingers crossed as I can't wait to get Sift install to start learning :-)

 @ekristen  - Hi, I'm good to go. I didn't know i had to create the directory first. Once i created the directory and reran the command Sift installed. Thanks for your assistance with this.

**Comment by ekristen** [comment]
You didn't run into any errors?

**Comment by magustin-telus** [comment]
@ekristen I had to create the dir that @cobbst had to create with v0.14.53 of cast. I am also getting this error with ubuntu 20.04

`level=warning msg=\"first failed state\" comment=\"One or more requisite failed: sift.python-packages.volatility.sift-python-volatility-community-plugins\" component=installer run_num=286 sls=sift.python-packages.volatility", "time=\"2024-11-02T06:15:39Z\" level=info msg=statistics component=installer failed=44 success=531 total=575",`.

is there a way to specify the tag for a specific version of sift when using cast?

**Comment by ekristen** [comment]
Try running again I just published an update.

Yes you can specify version with cast, if you run again it'll pick up the latest which should work, at least in testing is does, still running some larger tests.

**Comment by ekristen** [comment]
Also please not that nothing gets rolled back in failure so it's a partial install regardless and in this case 90% installed.

**Comment by magustin-telus** [comment]
@ekristen , I am now receiving this error:

`Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ERROR: Cannot install python-registry==1.3.0 and python-registry==1.3.1 because these package versions have conflicting dependencies. `

**Comment by ekristen** [comment]
Interesting, looking into it

**Comment by magustin-telus** [comment]
thanks!
Just to add context, I am doing an install every time with a freshly provisioned compute image

**Comment by cobbst** [comment]
I didn't. SIFT installed successfully. Another question, will there be work
for the same process for adding REMnux to SIFT Workstation.

**Comment by digitalsleuth** [comment]
Hi @cobbst , adding REMnux to SIFT works with the same process as with installing SIFT. You can use `cast` to install REMnux alongside SIFT.

**Comment by ekristen** [comment]
closing this in favor of #641
