### ISSUE TITLE
Best Ubuntu Distro for SIFT

### ISSUE THREAD

**Issue by DigiAngel** [sans-dfir/sift#64]
Topic says it...Xubuntu?  Lubuntu?  Standard Ubuntu with Unity?  Thank you.

**Comment by ekristen** [comment]
Hi @DigiAngel 

I can guarantee that the SIFT bootstrap will work with Ubuntu 14.04 Desktop beyond that there is no guarantees. If you decide to try any of the other variants please let me know how it goes.

**Comment by DigiAngel** [comment]
Thank you...I will go just with the stock ubuntu 14.04 Desktop with Unity.
