### ISSUE TITLE
Temporary failure in name resolution error. Cannot connect to network (VirtialBox)

### ISSUE THREAD

**Issue by adufault5** [sans-dfir/sift#640]
I had to redownload my VMs in virtualbox, to include SIFT and now I am getting the error temporary failure in name resolution. I did not have this error before.  I've tried to change the resolve.conf file as well as the configurations on the VirtualBox settings, but no luck. How did you fix it?

I tired all the different network options in the VirtualBox, so I feel very stuck.

**Comment by ekristen** [comment]
We currently do no testing against virtualbox. Have you confirmed if there's a network adapter and ping to your local gateway or to an internet resource using an IP works?
