### ISSUE TITLE
One or more requisite failed: sift.python-packages.analyzemft.analyzemft

### ISSUE THREAD

**Issue by mbell85** [sans-dfir/sift#642]
Running into the following problem when installing SIFT on Ubuntu 22.04 ...

`WARN[0114] first failed state                            comment="One or more requisite failed: sift.python-packages.analyzemft.analyzemft" component=installer run_num=292 sls=sift.python-packages
INFO[0114] statistics                                    component=installer failed=4 success=569 total=573
INFO[0114] salt-call completed but had failed states     component=installer
FATA[0114] salt-call completed but had failed states`

Any guidance appreciated.

**Comment by ekristen** [comment]
Please see https://github.com/teamdfir/sift/issues/641
