### ISSUE TITLE
mounting issue

### ISSUE THREAD

**Issue by Lou511** [sans-dfir/sift#67]
I used the mounting syntax, listed in the SIFT cheat sheet, and received an error message indicating that I had to specify the file system type.  When I did specify the type, I then encountered a "bad fs type, bad block on loop0..." error.  I subsequently used mounting syntax I found on a non-SIFT forum, and it worked.  Here is the syntax I followed:

sudo mount -o loop,offset=65536 \-t vfat cfreds_2015_data_leakage_rm#2.dd /mnt/windows_mount

This is different than what I found on the cheat sheet, and different than what I've seen on tutorial videos related to mounting files into SIFT.  I would like to know if anyone else has experienced the same issue.

Although the above syntax appeared to work, I could not see the data when I cd'd into the mount point.  I then tried to umount the file, but the system returned a "loop0 device busy" error.  I had to use fuser -km to forcefully unmount the file, which did work for me.  Is this an issue anyone has encountered?

**Comment by ekristen** [comment]
Hi @Lou511 - you'd probably have better luck asking these types of questions on SANS DFIR mailing list.
