### ISSUE TITLE
Add CRITS to project

### ISSUE THREAD

**Issue by SANS-SIFT** [sans-dfir/sift#73]
https://github.com/crits/crits/wiki

CRITs is designed to work on a 64-bit architecture of Ubuntu or RHEL6 using Python 2.7. Installation has beta support for OSX using Homebrew. It is also possible to install CRITs on CentOS.

If you require the use of a 32-bit OS, you will need to download 32-bit versions of the pre-compiled dependencies.

The following instructions assume you are running Ubuntu or RHEL6 64-bit with Python 2.7. If you are on RHEL which does not come with Python 2.7, you will need to install it. If you do, ensure all python library dependencies are installed using Python 2.7. Also, make sure you install mod_wsgi against the Python 2.7 install if you are looking to use Apache. More information on this can be found in the Github wiki at https://github.com/crits/crits/wiki/Common-Questions.

Quick install using bootstrap

CRITs comes with a bootstrap script which will help you:

Install all of the dependencies.
Configure CRITs for database connectivity and your first admin user.
Get MongoDB running with default settings.
Use Django's runserver to quickly get you up and running with the CRITs interface.
Just run the following:

```
sh script/bootstrap
```

Once you've run bootstrap once, do not use it again to get the runserver going, you'll be going through the install process again. Instead use the server script:

```
sh script/server
```

**Comment by ekristen** [comment]
Need https://github.com/JamesHabben/evolve/issues/14 to be addressed to make this project fit in better with SIFT.

**Comment by frbapolkosnik** [comment]
Please ping me if you guys run into any issues with CRITs. Thanks!

**Comment by seli176xh** [comment]
Using CRITs for the first time. Trying to load data?

**Comment by ekristen** [comment]
It's been decided this is not going to be added to the next release of SIFT.
