### ISSUE TITLE
Problem updating SIFT

### ISSUE THREAD

**Issue by trietptm** [sans-dfir/sift#75]
I receive the following errors when I run update-sift:
 * ERROR: Install Failure: python-plaso (Error Code: 100)
 * ERROR: Install Failure: mantaray (Error Code: 100)
 * ERROR: Install Failure: elasticsearch (Error Code: 100)

When I update them manually, I received these errors:
sansforensics@siftworkstation:~$ sudo apt-get install python-plaso
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-plaso is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-plaso' has no installation candidate

sansforensics@siftworkstation:~$ sudo apt-get install mantaray
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mantaray : Depends: python-plaso but it is not installable
E: Unable to correct problems, you have held broken packages.

sansforensics@siftworkstation:~$ sudo apt-get install elasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package elasticsearch

**Comment by ekristen** [comment]
Please ensure you use the latest bootstrap script from the master branch. If you still have problems, please upload your sift-install.log as a gist on github and link to it. Thank you.

**Comment by ekristen** [comment]
All updates and installs should be resolved .. https://github.com/sans-dfir/sift/issues/70
