### ISSUE TITLE
Running autopsy as install user fails.

### ISSUE THREAD

**Issue by ekristen** [sans-dfir/sift#77]
`/var/lib/autopsy` is owned by root, should be by the user who bootstraps the VM.

**Comment by ekristen** [comment]
Running `chown -R user:user /var/lib/autopsy` should fix this problem.

**Comment by Noxcivis** [comment]
Not having much success with that...  
![image](https://cloud.githubusercontent.com/assets/1217084/9291614/c8070a44-4399-11e5-8bdb-73ccc98ba22a.png)

I am logged in with a user account of "simon".

**Comment by Noxcivis** [comment]
Not having much success with that...

![image](https://cloud.githubusercontent.com/assets/1217084/9291617/fc979896-4399-11e5-8695-000bdb6d3b1e.png)

**Comment by ekristen** [comment]
`chown -R simon:simon /var/lib/autopsy` the other option is to `sudo autopsy` (this runs it as root though)

**Comment by Noxcivis** [comment]
The above worked.  Thanks !

**Comment by Massmare** [comment]
i have the same problem with autopsy
![screenshot from 2016-12-29 15 49 08](https://cloud.githubusercontent.com/assets/24807828/21547529/90bc41fa-cdde-11e6-834b-ed0c05c85565.png)
