### ISSUE TITLE
SIFT VM resizing whenever a terminal window is opened

### ISSUE THREAD

**Issue by ds379** [sans-dfir/sift#79]
I'm having an issue with the SANS SIFT Linux workstation(running in VMWare) where whenever I open a new terminal within the virtual machine, the entire VMWare window resizes. If you have it full screen, it will stay full screen but change the resolution. Interestingly, the same thing happens when you switch user accounts through the command line(ie, by typing sudo -su.) I've looked through both VMWare and CompizConfig in the SIFT VM, to no avail.
The host machines are a Mac OS X 10.7 and a Windows 7 box, running VMWare Fusion and VMWare Workstation 11.1.1 respectively. The guests are of course SANS Sift Workstation v3, downloaded directly from the SANS website, transferred over and installed. As such they're the latest version I believe.
Any help would be greatly appreciated!

**Comment by ekristen** [comment]
I'm not really sure how to help. This sounds like a VMWare Tools issue possibly. I've never seen this behavior before. 

We can leave the ticket open and see if anyone else has seen this.

**Comment by jklipsch** [comment]
I have the exact issue! I think it has to do w/ Terminal. No other apps in the VM resize the resolution. 

I haven't this tried this solution, but maybe it'll help.

http://ubuntuforums.org/showthread.php?t=2214825

**Comment by wdrone** [comment]
There is a line in the .bashrc file that resizes the resolution. I don't know why it is there but removing it will fix the issue.

**Comment by ekristen** [comment]
Interesting, this must be something that VMware does.

**Comment by JohnEbert** [comment]
Using VMware Workstation 10.0.7, SIFT 3 from SANS download, Windows 10. I dropped back from VMware 11 because it was pernicious in not being able to recover from the problem as defined by the OP opening post on this issue. In VM 10.0.7 at least I can change the VM Autosize view to Center Guest and then change it back to Autosize Autofit Guest and the screen reorganizes as it should.

**Comment by wdrone** [comment]
John - did you try removing the line from .bashrc? Prior to finding the fix I used the keyboard shortcuts to toggle between full screen and window modes to get VMWare Fusion to recover.

**Comment by JohnEbert** [comment]
Yes, I tried the line removal in .bashrc however the issue remains and in fact would not resize the screen correctly when I had a terminal session open and used VM View to toggle Autosize as before. I'm restoring my .bashrc as it was. Also, I have four entries in it as follows:
    alias display-med='xrandr --output Virtual1 --mode 1024x768'
    alias display-large='xrandr --output Virtual1 --mode 1280x1024'
    alias display-xl='xrandr --output Virtual1 --mode 1600x1200'
    alias display-xxl='xrandr --output Virtual1 --mode 1920x1440'

**Comment by jklipsch** [comment]
ekristen, that worked for me! OMFreakinG! It has bugging me forever! I just commented out that line. Thank you so much!
