### ISSUE TITLE
SIFT Workstation 3.0 - TOR daemon installed and running ?

### ISSUE THREAD

**Issue by UmbrielSecurity** [sans-dfir/sift#8]
Hello,

I'm using the SIFT Workstation 3.0 (Ubuntu) and I was alarmed to discover that this workstation not only had the TOR daemon installed, but it is configured to automatically start at boot time.

I think it's hard to justify the presence (let alone execution) of a TOR daemon on a forensics workstation.

Imagine my surprise when the Information Security team approached me that a TOR daemon was running on my forensics server...

![image](https://cloud.githubusercontent.com/assets/7646539/3029578/ac8f40a0-e036-11e3-90e0-6915ea501323.png)

Please remove (or at least disable) TOR from the workstation in future versions.

Thanks

**Comment by coonsmatthew** [comment]
Hello, 

I just installed the SIFT package on a pre-installed instance of Ubuntu using the bootstrap script. At this point, TOR is still included in the SIFT package and configured to start on system boot. Just wanted to give everyone a heads up.

**Comment by ekristen** [comment]
TOR is still installed however the service is disabled by default.

**Comment by coonsmatthew** [comment]
Hmm, ok. Well, when I installed the SIFT package using the Bootstrap script the tor service was set to start on boot. One of my colleges noticed tor traffic from my PC and I checked the service and it was running. Perhaps the tor service is set to not start automatically for the SIFT VM or ISO, but is set to start automatically when the SIFT packages are installed on an existing Ubuntu instance?

**Comment by socialcred** [comment]
The TOR daemon was still configured to run at boot and at run levels 1-5 on a bootstrap SIFT 3.0 machine I just built yesterday.  I had to disable it by using the sysv-rc-conf tool.  I also noticed that the SIFT is trying to monitor all network traffic at boot.  Does anyone know which daemon is doing that?  That also should be disabled by default.

**Comment by ekristen** [comment]
Removed. You'll need to run `apt-get remove torsocks`
