### ISSUE TITLE
Plaso no longer installed after update-sift

### ISSUE THREAD

**Issue by esecrpm** [sans-dfir/sift#80]
Starting from the SIFT appliance, ran REMnux install, rebooted, ran update-sift, ran update-remnux, rebooted.  After reboot, plaso is no longer found (log2timeline.py: command not found).

Attempted to install manually:
sansforensics@siftworkstation:~$ sudo apt-get install python-plaso
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-plaso : Depends: python-dfvfs but it is not going to be installed
                Depends: pytsk3 but it is not going to be installed
                Recommends: pyelasticsearch but it is not installable
E: Unable to correct problems, you have held broken packages.

Showing the relavant(?) lines in sift-install.log (can provide if needed):
The following extra packages will be installed:
  libtsk libtsk-dev
The following packages will be REMOVED:
  python-dfvfs python-plaso pytsk3
The following packages will be upgraded:
  libtsk libtsk-dev sleuthkit
3 upgraded, 0 newly installed, 3 to remove and 3 not upgraded.
Need to get 7,493 kB of archives.
After this operation, 36.7 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/sift/stable/ubuntu/ trusty/main sleuthkit amd64 4.1.30.4-1sift1~trusty [4,808 kB]
Get:2 http://ppa.launchpad.net/sift/stable/ubuntu/ trusty/main libtsk-dev amd64 4.1.30.4-1sift1~trusty [2,166 kB]
Get:3 http://ppa.launchpad.net/sift/stable/ubuntu/ trusty/main libtsk amd64 4.1.30.4-1sift1~trusty [519 kB]
Fetched 7,493 kB in 14s (503 kB/s)
(Reading database ... 239039 files and directories currently installed.)
Removing python-plaso (1.3.0-2ppa1~trusty) ...

**Comment by ekristen** [comment]
Please re-run the bootstrap script from the github repository. It should correct these problems.

**Comment by DigiAngel** [comment]
Same here as of a second ago:

* ERROR: Install Failure: python-plaso (Error Code: 100)
* ERROR: Install Failure: pytsk3 (Error Code: 100)
* ERROR: Install Failure: mantaray (Error Code: 100)

This was done using update-sift

**Comment by ekristen** [comment]
This has temporarily been fixed. Reverted to using Sleuthkit from GIFT repository (it does not support libewf)

To fix this, you may have to force remove sleuthkit and then re-run the update and try and re-install plaso.

**Comment by ekristen** [comment]
You'll need to run `apt-get update`, you may also need to run `apt-get clean` and `apt-get purge` to clear out the caches.

**Comment by DigiAngel** [comment]
Giving this a go now...thanks so much Erik.

**Comment by esecrpm** [comment]
Thanks Erik, log2timeline is back!  No ewf support in tsk just as you mentioned.

Followed the steps you outlined above:
sudo apt-get remove sleuthkit
sudo apt-get update
sudo apt-get clean
sudo apt-get purge
(and for good measure, I also ran sudo apt-get autoremove)
wget --quiet -O - https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i -s -y

**Comment by ekristen** [comment]
Good to hear. I'm working on the libewf problem.

**Comment by DigiAngel** [comment]
Confirming that all things are looking good...even Mantaray got installed...woo hoo!  Thanks Erik...always appreciate your hard work.
