### ISSUE TITLE
rekall 1.4.0 prereqs missing

### ISSUE THREAD

**Issue by clausing** [sans-dfir/sift#81]
Now that rekall is at 1.4.0 it requires a bunch of additional packages (all appear to be available via pip so far, I don't have it working yet myself) that aren't installed and the bigger issue that the default Ubuntu 12.04 and 14.04 version of python-dateutil is 1.5 and rekall 1.4.0 now requires >= 2.0.

**Comment by clausing** [comment]
Yup, all the prereqs are there in pip.

A change is required to set python default to 'utf8' rather than 'ascii' (add the following code to the top of /usr/lib/python2.7/site-customize.py, this is required to get gnureadline to build)

import sys  
reload(sys)  
sys.setdefaultencoding('utf8')

Then the following will  result in a version of rekall that runs (I haven't actually tried examining any images with it yet)

   $ sudo pip install --upgrade python_dateutil
   $ sudo pip install gnureadline
   $ sudo pip install traitlets
   $ sudo pip install pickleshare

**Comment by clausing** [comment]
Oops, forgot, you also (at least on 14.04) have to add libncurse5-dev (also for gnureadline)

$ apt-get install libncurses5-dev

**Comment by ekristen** [comment]
@clausing thanks for the report, I'll take a look and update the bootstrap script accordingly. Pull Requests are always welcome!

**Comment by ekristen** [comment]
Should be resolved
