### ISSUE TITLE
Help on using the log2timeline command instead of the .py

### ISSUE THREAD

**Issue by DW2054** [sans-dfir/sift#82]
I want to run the log2timeline against a E01 file set; with winsrv, PST, log file, fingerprinting.  I believe I have that setup correctly, but where do I point the command to the .E01?  For this example we will call it whole_disk.e01.  With plaso command it was obvious.  Or does this command only run against live systems?

Command:
log2timeline -f winsrv -w example_output_winsrv.csv -z PST8PDT -log example_output_WINSRV.LOG -c

Thank you.

**Comment by wdrone** [comment]
https://github.com/log2timeline/plaso/wiki/Upgrading-From-0.x-Branch

The link above indicates that the old perl version did not work on images. You need to mount the partition on the image of interest. The link has details or you can use the cheat sheet in SIFT. 

Essentially this:

# ewfmount /your.E01 /mnt/ewf

# mount -o ro,loop,...... /mnt/ewf/ewf1 /mnt/windows_mount

# log2timeline options /mnt/windows_mount
