### ISSUE TITLE
Autopsy Forensic Browser 2.24 not able to recognize EO1 image files 

### ISSUE THREAD

**Issue by rikjones** [sans-dfir/sift#84]
Autopsy Forensic Browser 2.24 not able to recognize EO1 image files. 

This is not a split file. This worked in a previous version of SIFT. but not the most current version.

The following error is presented:
'''''''''''''''''''''''''''''''''
Warning: Autopsy could not determine the volume system type for the disk image (i.e. the type of partition table).
Please select the type from the list below or reclassify the image as a volume image instead of as a disk image.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

I am able to open the image and mount it with xmount, so it is not corrupt.

**Comment by ekristen** [comment]
@rikjones this really isn't a SIFT question for a sleuthkit/autopsy folks. I would try and find a mailing list and ask there, or ask on the DFIR mailing list.

These repos are about creating and maintaining SIFT in its entirety.
