### ISSUE TITLE
log2timeline parser error-Win Security evtx file

### ISSUE THREAD

**Issue by GFraz** [sans-dfir/sift#85]
Hello,
I'm receiving an error when running log2timeline against a Windows 7 Enterprise security.evtx.  Please see the attached screenshot.  It appears there is a character that is not recognized. I'm using log2timeline version 0.66 that is included in the SIFT 3 VM.  I updated SIFT.  

If I used -f to identify the format, log2timeline quits.  If I allow log2timeline to guess the format (no -f), it finishes with errors.  

Your assistance is much appreciated.  Thanks.  

![log2timelineerror](https://cloud.githubusercontent.com/assets/15094490/10436380/073bc466-70f4-11e5-8326-573092831ee5.png)

**Comment by ekristen** [comment]
@GFraz Hello. Your question is better asked on the DFIR mailing list. This repository is dedicated to the building, management and maintenance of the SIFT workstation itself, very few people monitor this regarding tool problems. 

Cheers

**Comment by wdrone** [comment]
@GFraz Post this as an issue in the Log2timeline/Plaso repo. https://github.com/log2timeline/plaso Log2Timeline has some unicode handling issues that still need to be ironed out.

**Comment by ekristen** [comment]
@wdrone thanks for helping out.
