### ISSUE TITLE
Scalpel make fail on SIFT, what to make of recompile with -fPIC

### ISSUE THREAD

**Issue by JohnEbert** [sans-dfir/sift#86]
I don't know what to do with this "recompile with -fPIC" error generated near the end of the make

root@siftworkstation:/home/sansforensics/Downloads/scalpel-master# make, any ideas?
Making all in src
make[1]: Entering directory `/home/sansforensics/Downloads/scalpel-master/src'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/sansforensics/Downloads/scalpel-master/src'
Making all in man
make[1]: Entering directory`/home/sansforensics/Downloads/scalpel-master/man'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/home/sansforensics/Downloads/scalpel-master/man'
Making all in jni
make[1]: Entering directory `/home/sansforensics/Downloads/scalpel-master/jni'
/bin/bash ../libtool --tag=CXX   --mode=link g++  -g -O2   -o libscalpel_jni.la -rpath /usr/local/lib libscalpel_jni.lo ../src/libscalpel.la -ltre -lpthread -lm 
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  .libs/libscalpel_jni.o   ../src/.libs/libscalpel.a -ltre -lpthread -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o  -O2   -Wl,-soname -Wl,libscalpel_jni.so.0 -o .libs/libscalpel_jni.so.0.0.0
/usr/bin/ld: ../src/.libs/libscalpel.a(scalpel.o): relocation R_X86_64_32 against`.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../src/.libs/libscalpel.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: **\* [libscalpel_jni.la] Error 1
make[1]: Leaving directory `/home/sansforensics/Downloads/scalpel-master/jni'
make: **\* [all-recursive] Error 1

**Comment by ekristen** [comment]
So you are trying to install your own version of scapel?

**Comment by JohnEbert** [comment]
I was trying to raise scalpel up from 1.6 to version 2.

**Comment by z3ndrag0n** [comment]
recompile with -fPIC simply means use this switch for the compiler in order to generate Position Independent Code (i.e. relocatable code). It means the linker barfed when trying to relocate code that wasn't relocatable.

Hope this helps!
Barry

**Comment by JohnEbert** [comment]
I'll try again with -fPIC and try to update results here.

**Comment by ekristen** [comment]
@JohnEbert thoughts?

**Comment by JohnEbert** [comment]
Initially I tired to ./bootstrap but received ./bootstrap: aclocal: not
found, so I did apt-get install automake.
A subsequent ./bootstrap produced questionable results regarding the object
'subdir-objects' option.
I will presume this is not critical and try the next step of .configure

root@siftworkstation:/home/sansforensics/Downloads/scalpel-master#
./bootstrap
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:7: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms
are deprecated.  For more info, see:
configure.ac:7:
http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
configure.ac:6: installing './compile'
Makefile.am:12: warning: source file 'src/scalpel_exec.cpp' is in a
subdirectory,
Makefile.am:12: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the
'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding
output
automake: object file(s) will be placed in the top-level directory.
However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same
subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout
your
automake: project, to avoid future incompatibilities.

**Comment by JohnEbert** [comment]
My first run of ./configure produced some concerns. I will need to install
libtre and libtre-dev

/home/sansforensics/Downloads/scalpel-master/missing: Unknown
`--is-lightweight' option
Try `/home/sansforensics/Downloads/scalpel-master/missing --help' for more
information
configure: WARNING: 'missing' script is too old or missing

and
configure: error: Scalpel requires libtre and libtre-dev. See
http://laurikari.net/tre/.

**Comment by JohnEbert** [comment]
I'm stumbling on how t install tre. I downloaded the master from Github but
there are no build instructions, so trying to figure that out.

**Comment by JohnEbert** [comment]
It appears that "make" finished but scalpel still comes back as version 1.6.
Drat.

**Comment by mr5z** [comment]
any follow up for this thread? I'm having the same issue. Although I have downloaded already the packages of libtre but now able to install them :|

**Comment by JohnEbert** [comment]
I gave up and had to move on. Sorry, I'm just a user, not a dev. Good luck.
