### ISSUE TITLE
update-sift; stalls; log2timeline now does not work

### ISSUE THREAD

**Issue by conma293** [sans-dfir/sift#87]
trying to update SIFT, stalls on -
* INFO: Installed Python Package: unicodecsv

then log2timeline - 
log2timeline.py /cases/artifact_analysis/win7-32_nromanoff/vsstimelines/vssinfowin7-32_nromanoff-PlasoVSS.dump win7-32-nromanoff-c-drive.E01 
[INFO] Data files will be loaded from /usr/share/plaso by default.
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 676, in <module>
    if not Main():
  File "/usr/bin/log2timeline.py", line 662, in Main
    tool.ProcessSources()
  File "/usr/bin/log2timeline.py", line 558, in ProcessSources
    scan_context = self.ScanSource()
  File "/usr/lib/python2.7/dist-packages/plaso/cli/storage_media_tool.py", line 952, in ScanSource
    scan_node = scan_context.GetRootScanNode()
AttributeError: 'SourceScannerContext' object has no attribute 'GetRootScanNode'

**Comment by ekristen** [comment]
Everything seems to work ok for me. If you can send along the sift-install.log from your home directory that would help troubleshooting.

**Comment by ekristen** [comment]
If you are still seeing this issue, please feel free to re-open
