### ISSUE TITLE
"usr/local/src/windows-perl" is empty

### ISSUE THREAD

**Issue by LuigiRanzato** [sans-dfir/sift#88]
hi guys,

i'm looking for regtime.pl file inside "usr/local/src/windows-perl", but the dir "windows-perl" is not present 

What I've wrong?

thanks

**Comment by JohnEbert** [comment]
Try /usr/share/regripper/plugins/regtime.pl

I used # locate regtime.pl to find it. It is also in
/usr/share/windows-perl folder

**Comment by LuigiRanzato** [comment]
Thanks John,

my goal was to compare several registry hives, and I found an old example: 
https://5thsentinel.wordpress.com/2009/06/07/sans-sift-using-regtime-pl/

Is this the same file?
given the strange file location, for a moment I believed that it was not the regripper plugin

**Comment by JohnEbert** [comment]
You would have to compare the two files in a text editor or some other
tool. Maybe  "diff" could tell yes or no at least. Google diff maybe to
learn more or just examine the two files. I expect they may differ only by
version maybe.

**Comment by LuigiRanzato** [comment]
Thanks John, very helpful

**Comment by ekristen** [comment]
@JohnEbert thanks for helping out!

**Comment by JohnEbert** [comment]
Happy to be able to...
