### ISSUE TITLE
The Sleuth Kit is not compiled with support for ewf images

### ISSUE THREAD

**Issue by eoyslebo** [sans-dfir/sift#89]
Many tools (including photorec and plaso) that come bundled with SIFT support working directly on E01 files. This is possible with TSK, but it needs to be compiled against libewf.

```
tsk_loaddb -i list
Supported image format types:
        raw (Single or split raw file (dd))
```
```
tsk_loaddb -i ewf imagefile.E01
Unsupported image type: ewf
```

**Comment by ekristen** [comment]
@eoyslebo you are right. We are working on a new an updated version that supports libewf again.

**Comment by ekristen** [comment]
https://github.com/sans-dfir/sift/issues/78

**Comment by ekristen** [comment]
This should be fixed.
