### ISSUE TITLE
Volatility2.5

### ISSUE THREAD

**Issue by dlylefl** [sans-dfir/sift#91]
Just created new SIFT Workstation and get an error when trying to run Volatility 2.5. I noticed on my other SIFT workstation it's running Volatility 2.4

Exception: Object EditBox has already been defined by <class 'volatility.plugins.gui.editbox.Editbox'>

**Comment by ekristen** [comment]
Remove: /usr/lib/python2.7/dist-packages/volatility/plugins/editbox.py(c)

**Comment by dlylefl** [comment]
Thanks!

David Lyle
Level II Systems Engineer

Southeastern Grocers LLC
5050 Edgewood Court, Jacksonville, FL 32254
T. 904.370.6153
davidlyle@segrocers.com<mailto:davidlyle@segrocers.com>
www.segrocers.com<http://www.segrocers.com/>
[cid:0837DCB7-8CD1-49B9-9CDE-1B04D6297E6D]

**Comment by icaman** [comment]
Hi,  
I removed the file as you recomanded, but the error looks the same and also the lines:

sansforensics@siftworkstation:~$ volatility 
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 149, in main
    registry.register_global_options(config, commands.Command)
  File "/usr/lib/python2.7/dist-packages/volatility/registry.py", line 157, in register_global_options
    for m in get_plugin_classes(cls, True).values():
  File "/usr/lib/python2.7/dist-packages/volatility/registry.py", line 152, in get_plugin_classes
    raise Exception("Object {0} has already been defined by {1}".format(name, plugin))
Exception: Object EditBox has already been defined by <class 'volatility.plugins.editbox.EditBox'>

Thanks

**Comment by dlylefl** [comment]
I ended up just going back to Volatility 2.4

**Comment by ekristen** [comment]
Did you remove the .pyc file too? That did resolve the error for me. I can take another look though. 

Erik

**Comment by icaman** [comment]
I removed all editbox.py* files, I works! :)

Thank you, Erik!

**Comment by ekristen** [comment]
Awesome. Good to hear

**Comment by dlylefl** [comment]
ekristen quick question, how do I add a Plugin for example malsysproc. I copied to the volatility plugins directory but not working.

**Comment by dlylefl** [comment]
Removing editbox worked for me as well. Back to using 2.5
