### ISSUE TITLE
extract_mft_record_slack.py - broken shebang

### ISSUE THREAD

**Issue by PoorBillionaire** [sans-dfir/sift#93]
Greetings--

The extract_mft_record_slack.py tool on the SIFT workstation uses a shebang which points to /bin/python as the location of the Python symlink:

```
#!/bin/python

#    This file is part of INDXParse.
#
#   Copyright 2014 Will Ballenthin <william.ballenthin@mandiant.com>
#                    while at FireEye <http://www.FireEye.com>
```

...however on the SIFT workstation, Python has been configured to place its symlink at /usr/bin/python:

```
sansforensics@siftworkstation:~$ which python
/usr/bin/python
```

This causes an issue if one is running the script as executable - which it is in SIFT:

```
sansforensics@siftworkstation:~$ extract_mft_record_slack.py test
bash: /usr/local/bin/extract_mft_record_slack.py: /bin/python: bad interpreter: 
No such file or directory
```

It looks like Willi's development environment has the Python symlink residing at /bin/python - it is probably just a holdover from that:

https://github.com/williballenthin/INDXParse/blob/master/extract_mft_record_slack.py

Adam

**Comment by ekristen** [comment]
Fixed!

**Comment by ekristen** [comment]
Thanks!
