### ISSUE TITLE
TSK: Supported Image Formats

### ISSUE THREAD

**Issue by diogo-fernan** [sans-dfir/sift#97]
Hey guys,

I performed and installation of the SIFT workstation via the bootstrap script on a new Ubuntu 14.04 VirtualBox virtual machine. After installation, it appears that TSK lacks support for all image formats, except raw. The following is the output of `mmls -i list` or `fls -i list`:

> 
> Supported image format types:
> 	raw (Single or split raw file (dd))

I tried removing and installing the `sleuthkit` package manually via `apt-get`, but to no avail.

Has anyone faced this before? Any suggestion for fixing? Thanks

**Comment by JohnEbert** [comment]
Hi
You say you use VirtualBox. I use VMware to host the machine. I ran the
same commands against my vmdk version of SIFT-distro version 3 hosted by
VMware 12.0 Pro and they *reported more support than you report*, support
such as for AFF etcetera on the following install:

root@siftworkstation:/home/sansforensics# *uname -a*
Linux *siftworkstation 3.13.0-44-generic* #73-Ubuntu SMP Tue Dec 16
00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@siftworkstation:/home/sansforensics# cat /etc/lsb-release
DISTRIB_ID=*Ubuntu*
DISTRIB_RELEASE=*14.04*
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"

I followed the following instructions, so I suppose our installs are
similar:
1. Download Ubuntu 14.04 ISO file and install Ubuntu 14.04 on any system.
-> http://www.ubuntu.com/download/desktop
2. Once installed, open a terminal and run "*wget --quiet -O -
https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh
<https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh> |
sudo bash -s -- -i -s -y*"
3. Congrats -- you now have a SIFT workstation!!

**Comment by ekristen** [comment]
That's interesting John. I'm able to reproduce @diogo-fernan problems. Let me dive in a bit more.

**Comment by diogo-fernan** [comment]
@ekristen, did you progress with your investigation?

**Comment by ekristen** [comment]
I was able to confirm this on a build, why and how to fix is still unknown.

**Comment by ekristen** [comment]
I've reached out to the collaborator who is building sleuthkit for feedback, will update as soon as possible.

**Comment by ekristen** [comment]
Looks like the sleuthkit we get from the GIFT repo is designed to purely work with plaso and doesn't support any other image formats. I'll work on building a new version.

**Comment by diogo-fernan** [comment]
Good news! Thanks @ekristen.

**Comment by ekristen** [comment]
I've published a new version `4.2.0-11sift1-trusty` that is compiled with `libewf`, `afflib` and `zlib` current it resides in the development PPA for SIFT.

1. `sudo add-apt-repository -u ppa:sift/dev`
2. `sudo apt-get update`
3. `sudo apt-get install sleuthkit`

After you've tested you'll probably want to remove the sift/dev ppa from your apt sources. 

@diogo-fernan @JohnEbert if you could both take a look and let me know, if it checks out with you two, then I'll move it over to the `stable` SIFT repo and it'll become the new default for install and upgrade.

**Comment by JohnEbert** [comment]
It appears correct here, there more than only RAW as format types (see below.) I did a sudo apt-get remove -y sleuthkit and then your instructions to add the repository, update, and add. This is the result in SIFT 3.0 from the VM downloaded previously from SANS. The version now reports 4.2.0, which was before 4.1.3.

sansforensics@siftworkstation:~$ mmls -V
The Sleuth Kit ver 4.2.0
sansforensics@siftworkstation:~$ mmls -i list
Supported image format types:
	raw (Single or split raw file (dd))
	aff (Advanced Forensic Format)
	afd (AFF Multiple File)
	afm (AFF with external metadata)
	afflib (All AFFLIB image formats (including beta ones))
	ewf (Expert Witness format (encase))

**Comment by ekristen** [comment]
The package is being moved to the stable branch. Thanks.

**Comment by diogo-fernan** [comment]
The updated package resolved the issue for me. Thanks @ekristen.
