### ISSUE TITLE
PEFILE out of sync with current plaso version 1.4

### ISSUE THREAD

**Issue by SANS-SIFT** [sans-dfir/sift#98]
sansforensics@siftworkstation:/cases/win7-32-nromanoff-c-drive$ log2timeline.py plaso.dump c-drive.E01 
Checking availability and versions of plaso dependencies.
[FAILURE]   pefile version: 1.2.10-114 is too old, 1.2.10-139 or later required.

**Comment by ekristen** [comment]
I'll have to grab the c-drive.E01 to test, but look at the latest packages available if you do a `update-sift` or `sudo apt-get install python-pefile` should resolve it.

**Comment by lautriv** [comment]
I've run into this issue as well. I think that it's because pefile is installed in both `/usr/local/lib/python2.7/dist-packages` and `/usr/lib/python2.7/dist-packages`. The first directory is earlier on the path and has the older version installed.

    sansforensics@siftworkstation:~$ dpkg -l | grep python-pefile 
    ii  python-pefile 1.2.10-139-1ppa1~trusty all          Python module to read  with PE (Portable Executable) files.

Removing pefile from `/usr/local/lib/python2.7/dist-packages/` resolved the issue for me.

**Comment by ekristen** [comment]
That dpkg version is 1.2.10-139, so that doesn't make much sense.

**Comment by lautriv** [comment]
1.2.10-139 was installed by apt-get in `/usr/lib/python2.7/dist-packages`. However, 1.2.10-114 was present in `/usr/local/lib/python2.7/dist-packages`. I included the output from dpkg to illustrate that I had the latest version available. 

Just FYI I was running this from a VM provided in a FOR508 class, so it might not be an issue if the bootstrap doesn't install modules into `/usr/local/lib/python2.7`

**Comment by ekristen** [comment]
ah, probably just need to pip remove then maybe ... let me see if I have both on my system.

**Comment by NoahJaehnert** [comment]
I ran into this same issue after upgrading my SIFT workstation today. As @lautriv mentioned, removing pefile from  /usr/local/lib/python2.7/dist-packages/ resolved the issue.

**Comment by ekristen** [comment]
@NoahJaehnert thanks for the information

**Comment by ekristen** [comment]
Out of date and stale, closing.
